services:
  hubplay:
    build: .
    image: ghcr.io/alexzafra13/hubplay_demo:latest
    container_name: hubplay
    ports:
      - "8097:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      # Map your media folders here:
      - /mnt/media:/media:ro
    environment:
      - TZ=Europe/Madrid
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
