// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel_overrides.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const applyChannelOverride = `-- name: ApplyChannelOverride :execrows

UPDATE channels SET tvg_id = ?
WHERE library_id = ? AND stream_url = ?
`

type ApplyChannelOverrideParams struct {
	TvgID     sql.NullString `json:"tvg_id"`
	LibraryID string         `json:"library_id"`
	StreamUrl string         `json:"stream_url"`
}

// ApplyChannelOverride is the per-row hook the post-import pass uses.
// Returns rows affected so the caller can count "actually applied"
// vs orphan (stream_url no longer in playlist).
func (q *Queries) ApplyChannelOverride(ctx context.Context, arg ApplyChannelOverrideParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, applyChannelOverride, arg.TvgID, arg.LibraryID, arg.StreamUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteChannelOverride = `-- name: DeleteChannelOverride :exec
DELETE FROM channel_overrides WHERE library_id = ? AND stream_url = ?
`

type DeleteChannelOverrideParams struct {
	LibraryID string `json:"library_id"`
	StreamUrl string `json:"stream_url"`
}

func (q *Queries) DeleteChannelOverride(ctx context.Context, arg DeleteChannelOverrideParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelOverride, arg.LibraryID, arg.StreamUrl)
	return err
}

const getChannelOverride = `-- name: GetChannelOverride :one
SELECT library_id, stream_url, tvg_id, created_at, updated_at
FROM channel_overrides
WHERE library_id = ? AND stream_url = ?
`

type GetChannelOverrideParams struct {
	LibraryID string `json:"library_id"`
	StreamUrl string `json:"stream_url"`
}

func (q *Queries) GetChannelOverride(ctx context.Context, arg GetChannelOverrideParams) (ChannelOverride, error) {
	row := q.db.QueryRowContext(ctx, getChannelOverride, arg.LibraryID, arg.StreamUrl)
	var i ChannelOverride
	err := row.Scan(
		&i.LibraryID,
		&i.StreamUrl,
		&i.TvgID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelOverridesByLibrary = `-- name: ListChannelOverridesByLibrary :many
SELECT stream_url, tvg_id
FROM channel_overrides
WHERE library_id = ?
`

type ListChannelOverridesByLibraryRow struct {
	StreamUrl string `json:"stream_url"`
	TvgID     string `json:"tvg_id"`
}

func (q *Queries) ListChannelOverridesByLibrary(ctx context.Context, libraryID string) ([]ListChannelOverridesByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelOverridesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelOverridesByLibraryRow{}
	for rows.Next() {
		var i ListChannelOverridesByLibraryRow
		if err := rows.Scan(&i.StreamUrl, &i.TvgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelOverride = `-- name: UpsertChannelOverride :exec

INSERT INTO channel_overrides (library_id, stream_url, tvg_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(library_id, stream_url) DO UPDATE SET
   tvg_id     = excluded.tvg_id,
   updated_at = excluded.updated_at
`

type UpsertChannelOverrideParams struct {
	LibraryID string    `json:"library_id"`
	StreamUrl string    `json:"stream_url"`
	TvgID     string    `json:"tvg_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Manual channel edits keyed by stream URL so they survive an M3U
// refresh (channel UUIDs are regenerated on every import).
//
// Table schema: migrations/sqlite/009_channel_overrides.sql.
// Composite PK: (library_id, stream_url).
func (q *Queries) UpsertChannelOverride(ctx context.Context, arg UpsertChannelOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelOverride,
		arg.LibraryID,
		arg.StreamUrl,
		arg.TvgID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
