// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel_watch_history.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteChannelWatch = `-- name: DeleteChannelWatch :exec
DELETE FROM channel_watch_history WHERE user_id = ? AND stream_url = ?
`

type DeleteChannelWatchParams struct {
	UserID    string `json:"user_id"`
	StreamUrl string `json:"stream_url"`
}

func (q *Queries) DeleteChannelWatch(ctx context.Context, arg DeleteChannelWatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelWatch, arg.UserID, arg.StreamUrl)
	return err
}

const listChannelWatchHistoryByUser = `-- name: ListChannelWatchHistoryByUser :many

SELECT c.id, c.library_id, c.name, c.number,
       COALESCE(c.group_name,'') AS group_name,
       COALESCE(c.logo_url,'') AS logo_url, c.stream_url,
       COALESCE(c.tvg_id,'') AS tvg_id,
       COALESCE(c.language,'') AS language,
       COALESCE(c.country,'') AS country,
       c.is_active, c.added_at,
       h.last_watched_at
FROM   channel_watch_history h
JOIN   channels c ON c.stream_url = h.stream_url
WHERE  h.user_id = ?
  AND  c.is_active = 1
ORDER BY h.last_watched_at DESC, c.library_id ASC
LIMIT  ?
`

type ListChannelWatchHistoryByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

type ListChannelWatchHistoryByUserRow struct {
	ID            string        `json:"id"`
	LibraryID     string        `json:"library_id"`
	Name          string        `json:"name"`
	Number        sql.NullInt64 `json:"number"`
	GroupName     string        `json:"group_name"`
	LogoUrl       string        `json:"logo_url"`
	StreamUrl     string        `json:"stream_url"`
	TvgID         string        `json:"tvg_id"`
	Language      string        `json:"language"`
	Country       string        `json:"country"`
	IsActive      bool          `json:"is_active"`
	AddedAt       time.Time     `json:"added_at"`
	LastWatchedAt time.Time     `json:"last_watched_at"`
}

// ListChannelWatchHistoryByUser joins onto active channels in
// recency order. Filters applied in SQL so the handler cannot
// accidentally bypass them: c.is_active = 1 (deactivated channels
// drop off the rail), and orphan history rows (stream_url no longer
// in any playlist) are joined out naturally.
//
// limit is doubled at the call site to absorb stream_url duplicates
// across libraries; the repo dedupes in Go.
func (q *Queries) ListChannelWatchHistoryByUser(ctx context.Context, arg ListChannelWatchHistoryByUserParams) ([]ListChannelWatchHistoryByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelWatchHistoryByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelWatchHistoryByUserRow{}
	for rows.Next() {
		var i ListChannelWatchHistoryByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Number,
			&i.GroupName,
			&i.LogoUrl,
			&i.StreamUrl,
			&i.TvgID,
			&i.Language,
			&i.Country,
			&i.IsActive,
			&i.AddedAt,
			&i.LastWatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordChannelWatch = `-- name: RecordChannelWatch :exec

INSERT INTO channel_watch_history (user_id, stream_url, last_watched_at)
VALUES (?, ?, ?)
ON CONFLICT(user_id, stream_url) DO UPDATE SET
   last_watched_at = excluded.last_watched_at
`

type RecordChannelWatchParams struct {
	UserID        string    `json:"user_id"`
	StreamUrl     string    `json:"stream_url"`
	LastWatchedAt time.Time `json:"last_watched_at"`
}

// Per-user "continue watching" history for LiveTV channels.
//
// Table schema: migrations/sqlite/012_channel_watch_history.sql.
// Composite PK: (user_id, stream_url).
//
// Keyed by stream_url so the rail survives M3U refreshes (channel
// UUIDs regenerate). The list query joins back to `channels` by
// stream_url at read time.
func (q *Queries) RecordChannelWatch(ctx context.Context, arg RecordChannelWatchParams) error {
	_, err := q.db.ExecContext(ctx, recordChannelWatch, arg.UserID, arg.StreamUrl, arg.LastWatchedAt)
	return err
}
