// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel_favorites.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const addChannelFavorite = `-- name: AddChannelFavorite :exec

INSERT INTO user_channel_favorites (user_id, channel_id, created_at)
VALUES (?, ?, ?)
ON CONFLICT(user_id, channel_id) DO NOTHING
`

type AddChannelFavoriteParams struct {
	UserID    string    `json:"user_id"`
	ChannelID string    `json:"channel_id"`
	CreatedAt time.Time `json:"created_at"`
}

// Per-user IPTV channel favorites.
//
// Table schema: migrations/sqlite/006_channel_favorites.sql.
// PK: (user_id, channel_id).
func (q *Queries) AddChannelFavorite(ctx context.Context, arg AddChannelFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addChannelFavorite, arg.UserID, arg.ChannelID, arg.CreatedAt)
	return err
}

const isChannelFavorite = `-- name: IsChannelFavorite :one
SELECT 1
FROM user_channel_favorites
WHERE user_id = ? AND channel_id = ?
LIMIT 1
`

type IsChannelFavoriteParams struct {
	UserID    string `json:"user_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) IsChannelFavorite(ctx context.Context, arg IsChannelFavoriteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isChannelFavorite, arg.UserID, arg.ChannelID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listChannelFavorites = `-- name: ListChannelFavorites :many
SELECT channel_id, created_at
FROM user_channel_favorites
WHERE user_id = ?
ORDER BY created_at DESC
`

type ListChannelFavoritesRow struct {
	ChannelID string    `json:"channel_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListChannelFavorites(ctx context.Context, userID string) ([]ListChannelFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelFavoritesRow{}
	for rows.Next() {
		var i ListChannelFavoritesRow
		if err := rows.Scan(&i.ChannelID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelFavoritesWithChannel = `-- name: ListChannelFavoritesWithChannel :many
SELECT c.id, c.library_id, c.name, c.number,
       COALESCE(c.group_name, '') AS group_name,
       COALESCE(c.logo_url, '') AS logo_url, c.stream_url,
       COALESCE(c.tvg_id, '') AS tvg_id,
       COALESCE(c.language, '') AS language,
       COALESCE(c.country, '') AS country,
       c.is_active, c.added_at, f.created_at AS favorited_at
FROM user_channel_favorites f
JOIN channels c ON c.id = f.channel_id
WHERE f.user_id = ? AND c.is_active = 1
ORDER BY f.created_at DESC
`

type ListChannelFavoritesWithChannelRow struct {
	ID          string        `json:"id"`
	LibraryID   string        `json:"library_id"`
	Name        string        `json:"name"`
	Number      sql.NullInt64 `json:"number"`
	GroupName   string        `json:"group_name"`
	LogoUrl     string        `json:"logo_url"`
	StreamUrl   string        `json:"stream_url"`
	TvgID       string        `json:"tvg_id"`
	Language    string        `json:"language"`
	Country     string        `json:"country"`
	IsActive    bool          `json:"is_active"`
	AddedAt     time.Time     `json:"added_at"`
	FavoritedAt time.Time     `json:"favorited_at"`
}

func (q *Queries) ListChannelFavoritesWithChannel(ctx context.Context, userID string) ([]ListChannelFavoritesWithChannelRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelFavoritesWithChannel, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelFavoritesWithChannelRow{}
	for rows.Next() {
		var i ListChannelFavoritesWithChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Number,
			&i.GroupName,
			&i.LogoUrl,
			&i.StreamUrl,
			&i.TvgID,
			&i.Language,
			&i.Country,
			&i.IsActive,
			&i.AddedAt,
			&i.FavoritedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelFavorite = `-- name: RemoveChannelFavorite :exec
DELETE FROM user_channel_favorites
WHERE user_id = ? AND channel_id = ?
`

type RemoveChannelFavoriteParams struct {
	UserID    string `json:"user_id"`
	ChannelID string `json:"channel_id"`
}

func (q *Queries) RemoveChannelFavorite(ctx context.Context, arg RemoveChannelFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeChannelFavorite, arg.UserID, arg.ChannelID)
	return err
}
