// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channels.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createChannel = `-- name: CreateChannel :exec

INSERT INTO channels (id, library_id, name, number, group_name, logo_url,
    stream_url, tvg_id, language, country, is_active, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateChannelParams struct {
	ID        string         `json:"id"`
	LibraryID string         `json:"library_id"`
	Name      string         `json:"name"`
	Number    sql.NullInt64  `json:"number"`
	GroupName sql.NullString `json:"group_name"`
	LogoUrl   sql.NullString `json:"logo_url"`
	StreamUrl string         `json:"stream_url"`
	TvgID     sql.NullString `json:"tvg_id"`
	Language  sql.NullString `json:"language"`
	Country   sql.NullString `json:"country"`
	IsActive  bool           `json:"is_active"`
	AddedAt   time.Time      `json:"added_at"`
}

// IPTV channels per library.
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE channels).
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.ExecContext(ctx, createChannel,
		arg.ID,
		arg.LibraryID,
		arg.Name,
		arg.Number,
		arg.GroupName,
		arg.LogoUrl,
		arg.StreamUrl,
		arg.TvgID,
		arg.Language,
		arg.Country,
		arg.IsActive,
		arg.AddedAt,
	)
	return err
}

const deleteChannelsByLibrary = `-- name: DeleteChannelsByLibrary :exec
DELETE FROM channels WHERE library_id = ?
`

func (q *Queries) DeleteChannelsByLibrary(ctx context.Context, libraryID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannelsByLibrary, libraryID)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, library_id, name, number, COALESCE(group_name, '') AS group_name,
       COALESCE(logo_url, '') AS logo_url, stream_url, COALESCE(tvg_id, '') AS tvg_id,
       COALESCE(language, '') AS language, COALESCE(country, '') AS country,
       is_active, added_at
FROM channels
WHERE id = ?
`

type GetChannelByIDRow struct {
	ID        string        `json:"id"`
	LibraryID string        `json:"library_id"`
	Name      string        `json:"name"`
	Number    sql.NullInt64 `json:"number"`
	GroupName string        `json:"group_name"`
	LogoUrl   string        `json:"logo_url"`
	StreamUrl string        `json:"stream_url"`
	TvgID     string        `json:"tvg_id"`
	Language  string        `json:"language"`
	Country   string        `json:"country"`
	IsActive  bool          `json:"is_active"`
	AddedAt   time.Time     `json:"added_at"`
}

func (q *Queries) GetChannelByID(ctx context.Context, id string) (GetChannelByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChannelByID, id)
	var i GetChannelByIDRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.Number,
		&i.GroupName,
		&i.LogoUrl,
		&i.StreamUrl,
		&i.TvgID,
		&i.Language,
		&i.Country,
		&i.IsActive,
		&i.AddedAt,
	)
	return i, err
}

const listActiveChannelsByLibrary = `-- name: ListActiveChannelsByLibrary :many
SELECT id, library_id, name, number, COALESCE(group_name, '') AS group_name,
       COALESCE(logo_url, '') AS logo_url, stream_url, COALESCE(tvg_id, '') AS tvg_id,
       COALESCE(language, '') AS language, COALESCE(country, '') AS country,
       is_active, added_at
FROM channels
WHERE library_id = ? AND is_active = 1
ORDER BY number, name
`

type ListActiveChannelsByLibraryRow struct {
	ID        string        `json:"id"`
	LibraryID string        `json:"library_id"`
	Name      string        `json:"name"`
	Number    sql.NullInt64 `json:"number"`
	GroupName string        `json:"group_name"`
	LogoUrl   string        `json:"logo_url"`
	StreamUrl string        `json:"stream_url"`
	TvgID     string        `json:"tvg_id"`
	Language  string        `json:"language"`
	Country   string        `json:"country"`
	IsActive  bool          `json:"is_active"`
	AddedAt   time.Time     `json:"added_at"`
}

func (q *Queries) ListActiveChannelsByLibrary(ctx context.Context, libraryID string) ([]ListActiveChannelsByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveChannelsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveChannelsByLibraryRow{}
	for rows.Next() {
		var i ListActiveChannelsByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Number,
			&i.GroupName,
			&i.LogoUrl,
			&i.StreamUrl,
			&i.TvgID,
			&i.Language,
			&i.Country,
			&i.IsActive,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelGroups = `-- name: ListChannelGroups :many
SELECT DISTINCT group_name
FROM channels
WHERE library_id = ? AND group_name != ''
ORDER BY group_name
`

func (q *Queries) ListChannelGroups(ctx context.Context, libraryID string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listChannelGroups, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var group_name sql.NullString
		if err := rows.Scan(&group_name); err != nil {
			return nil, err
		}
		items = append(items, group_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByLibrary = `-- name: ListChannelsByLibrary :many
SELECT id, library_id, name, number, COALESCE(group_name, '') AS group_name,
       COALESCE(logo_url, '') AS logo_url, stream_url, COALESCE(tvg_id, '') AS tvg_id,
       COALESCE(language, '') AS language, COALESCE(country, '') AS country,
       is_active, added_at
FROM channels
WHERE library_id = ?
ORDER BY number, name
`

type ListChannelsByLibraryRow struct {
	ID        string        `json:"id"`
	LibraryID string        `json:"library_id"`
	Name      string        `json:"name"`
	Number    sql.NullInt64 `json:"number"`
	GroupName string        `json:"group_name"`
	LogoUrl   string        `json:"logo_url"`
	StreamUrl string        `json:"stream_url"`
	TvgID     string        `json:"tvg_id"`
	Language  string        `json:"language"`
	Country   string        `json:"country"`
	IsActive  bool          `json:"is_active"`
	AddedAt   time.Time     `json:"added_at"`
}

func (q *Queries) ListChannelsByLibrary(ctx context.Context, libraryID string) ([]ListChannelsByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsByLibraryRow{}
	for rows.Next() {
		var i ListChannelsByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.Number,
			&i.GroupName,
			&i.LogoUrl,
			&i.StreamUrl,
			&i.TvgID,
			&i.Language,
			&i.Country,
			&i.IsActive,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelActive = `-- name: SetChannelActive :execrows
UPDATE channels SET is_active = ? WHERE id = ?
`

type SetChannelActiveParams struct {
	IsActive bool   `json:"is_active"`
	ID       string `json:"id"`
}

func (q *Queries) SetChannelActive(ctx context.Context, arg SetChannelActiveParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setChannelActive, arg.IsActive, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
