// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chapters.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteChaptersByItem = `-- name: DeleteChaptersByItem :exec
DELETE FROM chapters WHERE item_id = ?
`

func (q *Queries) DeleteChaptersByItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteChaptersByItem, itemID)
	return err
}

const insertChapter = `-- name: InsertChapter :exec
INSERT INTO chapters (item_id, start_ticks, end_ticks, title, image_path)
VALUES (?, ?, ?, ?, ?)
`

type InsertChapterParams struct {
	ItemID     string `json:"item_id"`
	StartTicks int64  `json:"start_ticks"`
	EndTicks   int64  `json:"end_ticks"`
	Title      sql.NullString `json:"title"`
	ImagePath  sql.NullString `json:"image_path"`
}

func (q *Queries) InsertChapter(ctx context.Context, arg InsertChapterParams) error {
	_, err := q.db.ExecContext(ctx, insertChapter,
		arg.ItemID, arg.StartTicks, arg.EndTicks, arg.Title, arg.ImagePath,
	)
	return err
}

const listChaptersByItem = `-- name: ListChaptersByItem :many
SELECT item_id, start_ticks, end_ticks, COALESCE(title, '') AS title,
       COALESCE(image_path, '') AS image_path
FROM chapters
WHERE item_id = ?
ORDER BY start_ticks ASC
`

type ListChaptersByItemRow struct {
	ItemID     string `json:"item_id"`
	StartTicks int64  `json:"start_ticks"`
	EndTicks   int64  `json:"end_ticks"`
	Title      string `json:"title"`
	ImagePath  string `json:"image_path"`
}

func (q *Queries) ListChaptersByItem(ctx context.Context, itemID string) ([]ListChaptersByItemRow, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChaptersByItemRow{}
	for rows.Next() {
		var i ListChaptersByItemRow
		if err := rows.Scan(&i.ItemID, &i.StartTicks, &i.EndTicks, &i.Title, &i.ImagePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
