// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlc

import (
	"context"
)

const getCollectionByID = `-- name: GetCollectionByID :one

SELECT id, tmdb_id, name, overview, poster_url, backdrop_url, created_at
FROM collections
WHERE id = ?
`

// Movie collections (sagas).
//
// Schema: migrations/sqlite/033_collections.sql.
// Keyed by tmdb_id (UNIQUE) so the same X-Men / MCU / Toy Story
// saga collapses across every member movie regardless of name drift.
func (q *Queries) GetCollectionByID(ctx context.Context, id string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Name,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getCollectionByTMDBID = `-- name: GetCollectionByTMDBID :one
SELECT id, tmdb_id, name, overview, poster_url, backdrop_url, created_at
FROM collections
WHERE tmdb_id = ?
`

func (q *Queries) GetCollectionByTMDBID(ctx context.Context, tmdbID int64) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByTMDBID, tmdbID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Name,
		&i.Overview,
		&i.PosterUrl,
		&i.BackdropUrl,
		&i.CreatedAt,
	)
	return i, err
}
