// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: device_codes.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const approveDeviceCode = `-- name: ApproveDeviceCode :exec
UPDATE device_codes
SET    user_id = ?,
       approved_at = ?
WHERE  user_code = ?
  AND  user_id IS NULL
  AND  expires_at > ?
`

type ApproveDeviceCodeParams struct {
	UserID     sql.NullString `json:"user_id"`
	ApprovedAt sql.NullTime   `json:"approved_at"`
	UserCode   string         `json:"user_code"`
	ExpiresAt  time.Time      `json:"expires_at"`
}

func (q *Queries) ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) error {
	_, err := q.db.ExecContext(ctx, approveDeviceCode,
		arg.UserID,
		arg.ApprovedAt,
		arg.UserCode,
		arg.ExpiresAt,
	)
	return err
}

const consumeDeviceCode = `-- name: ConsumeDeviceCode :exec
UPDATE device_codes
SET    consumed_at = ?
WHERE  device_code = ?
  AND  consumed_at IS NULL
`

type ConsumeDeviceCodeParams struct {
	ConsumedAt sql.NullTime `json:"consumed_at"`
	DeviceCode string       `json:"device_code"`
}

func (q *Queries) ConsumeDeviceCode(ctx context.Context, arg ConsumeDeviceCodeParams) error {
	_, err := q.db.ExecContext(ctx, consumeDeviceCode, arg.ConsumedAt, arg.DeviceCode)
	return err
}

const deleteExpiredDeviceCodes = `-- name: DeleteExpiredDeviceCodes :exec
DELETE FROM device_codes
WHERE expires_at < ?
   OR consumed_at IS NOT NULL
`

func (q *Queries) DeleteExpiredDeviceCodes(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredDeviceCodes, expiresAt)
	return err
}

const getDeviceCodeByDeviceCode = `-- name: GetDeviceCodeByDeviceCode :one
SELECT device_code, user_code, device_name, user_id, expires_at, created_at, approved_at, consumed_at, last_polled_at
FROM   device_codes
WHERE  device_code = ?
`

func (q *Queries) GetDeviceCodeByDeviceCode(ctx context.Context, deviceCode string) (DeviceCode, error) {
	row := q.db.QueryRowContext(ctx, getDeviceCodeByDeviceCode, deviceCode)
	var i DeviceCode
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.DeviceName,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.ConsumedAt,
		&i.LastPolledAt,
	)
	return i, err
}

const getDeviceCodeByUserCode = `-- name: GetDeviceCodeByUserCode :one
SELECT device_code, user_code, device_name, user_id, expires_at, created_at, approved_at, consumed_at, last_polled_at
FROM   device_codes
WHERE  user_code = ?
`

func (q *Queries) GetDeviceCodeByUserCode(ctx context.Context, userCode string) (DeviceCode, error) {
	row := q.db.QueryRowContext(ctx, getDeviceCodeByUserCode, userCode)
	var i DeviceCode
	err := row.Scan(
		&i.DeviceCode,
		&i.UserCode,
		&i.DeviceName,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.ConsumedAt,
		&i.LastPolledAt,
	)
	return i, err
}

const insertDeviceCode = `-- name: InsertDeviceCode :exec
INSERT INTO device_codes (
    device_code, user_code, device_name, expires_at, created_at
) VALUES (
    ?, ?, ?, ?, ?
)
`

type InsertDeviceCodeParams struct {
	DeviceCode string    `json:"device_code"`
	UserCode   string    `json:"user_code"`
	DeviceName string    `json:"device_name"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertDeviceCode,
		arg.DeviceCode,
		arg.UserCode,
		arg.DeviceName,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const touchDeviceCodePollAt = `-- name: TouchDeviceCodePollAt :exec
UPDATE device_codes
SET    last_polled_at = ?
WHERE  device_code = ?
`

type TouchDeviceCodePollAtParams struct {
	LastPolledAt sql.NullTime `json:"last_polled_at"`
	DeviceCode   string       `json:"device_code"`
}

func (q *Queries) TouchDeviceCodePollAt(ctx context.Context, arg TouchDeviceCodePollAtParams) error {
	_, err := q.db.ExecContext(ctx, touchDeviceCodePollAt, arg.LastPolledAt, arg.DeviceCode)
	return err
}
