// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: epg_programs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const cleanupOldPrograms = `-- name: CleanupOldPrograms :execrows
DELETE FROM epg_programs WHERE end_time < ?
`

func (q *Queries) CleanupOldPrograms(ctx context.Context, endTime time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, cleanupOldPrograms, endTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEPGProgramsByChannel = `-- name: DeleteEPGProgramsByChannel :exec
DELETE FROM epg_programs WHERE channel_id = ?
`

func (q *Queries) DeleteEPGProgramsByChannel(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteEPGProgramsByChannel, channelID)
	return err
}

const getNowPlaying = `-- name: GetNowPlaying :one
SELECT id, channel_id, title, COALESCE(description, '') AS description,
       COALESCE(category, '') AS category, COALESCE(icon_url, '') AS icon_url,
       start_time, end_time
FROM epg_programs
WHERE channel_id = ? AND start_time <= ? AND end_time > ?
LIMIT 1
`

type GetNowPlayingParams struct {
	ChannelID string    `json:"channel_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type GetNowPlayingRow struct {
	ID          string    `json:"id"`
	ChannelID   string    `json:"channel_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	IconUrl     string    `json:"icon_url"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
}

func (q *Queries) GetNowPlaying(ctx context.Context, arg GetNowPlayingParams) (GetNowPlayingRow, error) {
	row := q.db.QueryRowContext(ctx, getNowPlaying, arg.ChannelID, arg.StartTime, arg.EndTime)
	var i GetNowPlayingRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.IconUrl,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const insertEPGProgram = `-- name: InsertEPGProgram :exec

INSERT INTO epg_programs (id, channel_id, title, description, category, icon_url, start_time, end_time)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEPGProgramParams struct {
	ID          string         `json:"id"`
	ChannelID   string         `json:"channel_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	IconUrl     sql.NullString `json:"icon_url"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
}

// Electronic program guide entries per channel.
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE epg_programs).
// NOTE: BulkSchedule uses dynamic IN() and remains as raw SQL in the adapter.
func (q *Queries) InsertEPGProgram(ctx context.Context, arg InsertEPGProgramParams) error {
	_, err := q.db.ExecContext(ctx, insertEPGProgram,
		arg.ID,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.IconUrl,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}

const listSchedule = `-- name: ListSchedule :many
SELECT id, channel_id, title, COALESCE(description, '') AS description,
       COALESCE(category, '') AS category, COALESCE(icon_url, '') AS icon_url,
       start_time, end_time
FROM epg_programs
WHERE channel_id = ? AND end_time > ? AND start_time < ?
ORDER BY start_time
`

type ListScheduleParams struct {
	ChannelID string    `json:"channel_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

type ListScheduleRow struct {
	ID          string    `json:"id"`
	ChannelID   string    `json:"channel_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	IconUrl     string    `json:"icon_url"`
	StartTime   time.Time `json:"start_time"`
	EndTime     time.Time `json:"end_time"`
}

func (q *Queries) ListSchedule(ctx context.Context, arg ListScheduleParams) ([]ListScheduleRow, error) {
	rows, err := q.db.QueryContext(ctx, listSchedule, arg.ChannelID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleRow{}
	for rows.Next() {
		var i ListScheduleRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.IconUrl,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
