// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: external_ids.sql

package sqlc

import (
	"context"
)

const countExternalIDsByItem = `-- name: CountExternalIDsByItem :one
SELECT COUNT(*) AS cnt
FROM external_ids
WHERE item_id = ?
`

func (q *Queries) CountExternalIDsByItem(ctx context.Context, itemID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExternalIDsByItem, itemID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getExternalIDByProvider = `-- name: GetExternalIDByProvider :one
SELECT item_id, provider, external_id
FROM external_ids
WHERE item_id = ? AND provider = ?
`

type GetExternalIDByProviderParams struct {
	ItemID   string `json:"item_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetExternalIDByProvider(ctx context.Context, arg GetExternalIDByProviderParams) (ExternalID, error) {
	row := q.db.QueryRowContext(ctx, getExternalIDByProvider, arg.ItemID, arg.Provider)
	var i ExternalID
	err := row.Scan(&i.ItemID, &i.Provider, &i.ExternalID)
	return i, err
}

const listExternalIDsByItem = `-- name: ListExternalIDsByItem :many
SELECT item_id, provider, external_id
FROM external_ids
WHERE item_id = ?
`

func (q *Queries) ListExternalIDsByItem(ctx context.Context, itemID string) ([]ExternalID, error) {
	rows, err := q.db.QueryContext(ctx, listExternalIDsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalID{}
	for rows.Next() {
		var i ExternalID
		if err := rows.Scan(&i.ItemID, &i.Provider, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExternalID = `-- name: UpsertExternalID :exec

INSERT INTO external_ids (item_id, provider, external_id)
VALUES (?, ?, ?)
ON CONFLICT(item_id, provider) DO UPDATE SET external_id = excluded.external_id
`

type UpsertExternalIDParams struct {
	ItemID     string `json:"item_id"`
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

// External ID mappings (tmdb, imdb, tvdb, ...) for items.
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE external_ids).
// PK: (item_id, provider).
func (q *Queries) UpsertExternalID(ctx context.Context, arg UpsertExternalIDParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalID, arg.ItemID, arg.Provider, arg.ExternalID)
	return err
}
