// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: images.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createImage = `-- name: CreateImage :exec

INSERT INTO images (id, item_id, type, path, width, height, blurhash, provider, is_primary, is_locked, added_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateImageParams struct {
	ID        string         `json:"id"`
	ItemID    string         `json:"item_id"`
	Type      string         `json:"type"`
	Path      string         `json:"path"`
	Width     sql.NullInt64  `json:"width"`
	Height    sql.NullInt64  `json:"height"`
	Blurhash  sql.NullString `json:"blurhash"`
	Provider  sql.NullString `json:"provider"`
	IsPrimary sql.NullBool   `json:"is_primary"`
	IsLocked  sql.NullBool   `json:"is_locked"`
	AddedAt   time.Time      `json:"added_at"`
}

// Image assets (poster, backdrop, thumb, logo, banner) per item.
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE images)
// + migration 013_image_lock.sql (is_locked column).
// NOTE: GetPrimaryURLs uses dynamic IN() and remains raw SQL in the adapter.
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.ID,
		arg.ItemID,
		arg.Type,
		arg.Path,
		arg.Width,
		arg.Height,
		arg.Blurhash,
		arg.Provider,
		arg.IsPrimary,
		arg.IsLocked,
		arg.AddedAt,
	)
	return err
}

const deleteImageByID = `-- name: DeleteImageByID :exec
DELETE FROM images WHERE id = ?
`

func (q *Queries) DeleteImageByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImageByID, id)
	return err
}

const deleteImagesByItem = `-- name: DeleteImagesByItem :exec
DELETE FROM images WHERE item_id = ?
`

func (q *Queries) DeleteImagesByItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteImagesByItem, itemID)
	return err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, item_id, type, path, COALESCE(width, 0) AS width, COALESCE(height, 0) AS height,
       COALESCE(blurhash, '') AS blurhash, COALESCE(provider, '') AS provider,
       is_primary, is_locked, added_at
FROM images
WHERE id = ?
`

type GetImageByIDRow struct {
	ID        string       `json:"id"`
	ItemID    string       `json:"item_id"`
	Type      string       `json:"type"`
	Path      string       `json:"path"`
	Width     int64        `json:"width"`
	Height    int64        `json:"height"`
	Blurhash  string       `json:"blurhash"`
	Provider  string       `json:"provider"`
	IsPrimary sql.NullBool `json:"is_primary"`
	IsLocked  sql.NullBool `json:"is_locked"`
	AddedAt   time.Time    `json:"added_at"`
}

func (q *Queries) GetImageByID(ctx context.Context, id string) (GetImageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i GetImageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Type,
		&i.Path,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Provider,
		&i.IsPrimary,
		&i.IsLocked,
		&i.AddedAt,
	)
	return i, err
}

const getPrimaryImage = `-- name: GetPrimaryImage :one
SELECT id, item_id, type, path, COALESCE(width, 0) AS width, COALESCE(height, 0) AS height,
       COALESCE(blurhash, '') AS blurhash, COALESCE(provider, '') AS provider,
       is_primary, is_locked, added_at
FROM images
WHERE item_id = ? AND type = ? AND is_primary = 1
`

type GetPrimaryImageParams struct {
	ItemID string `json:"item_id"`
	Type   string `json:"type"`
}

type GetPrimaryImageRow struct {
	ID        string       `json:"id"`
	ItemID    string       `json:"item_id"`
	Type      string       `json:"type"`
	Path      string       `json:"path"`
	Width     int64        `json:"width"`
	Height    int64        `json:"height"`
	Blurhash  string       `json:"blurhash"`
	Provider  string       `json:"provider"`
	IsPrimary sql.NullBool `json:"is_primary"`
	IsLocked  sql.NullBool `json:"is_locked"`
	AddedAt   time.Time    `json:"added_at"`
}

func (q *Queries) GetPrimaryImage(ctx context.Context, arg GetPrimaryImageParams) (GetPrimaryImageRow, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryImage, arg.ItemID, arg.Type)
	var i GetPrimaryImageRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Type,
		&i.Path,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Provider,
		&i.IsPrimary,
		&i.IsLocked,
		&i.AddedAt,
	)
	return i, err
}

const hasLockedImageForKind = `-- name: HasLockedImageForKind :one
SELECT COUNT(*) > 0 AS has_lock FROM images
WHERE item_id = ? AND type = ? AND is_locked = 1
`

type HasLockedImageForKindParams struct {
	ItemID string `json:"item_id"`
	Type   string `json:"type"`
}

func (q *Queries) HasLockedImageForKind(ctx context.Context, arg HasLockedImageForKindParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasLockedImageForKind, arg.ItemID, arg.Type)
	var hasLock bool
	err := row.Scan(&hasLock)
	return hasLock, err
}

const listImagesByItem = `-- name: ListImagesByItem :many
SELECT id, item_id, type, path, COALESCE(width, 0) AS width, COALESCE(height, 0) AS height,
       COALESCE(blurhash, '') AS blurhash, COALESCE(provider, '') AS provider,
       is_primary, is_locked, added_at
FROM images
WHERE item_id = ?
ORDER BY is_primary DESC, type
`

type ListImagesByItemRow struct {
	ID        string       `json:"id"`
	ItemID    string       `json:"item_id"`
	Type      string       `json:"type"`
	Path      string       `json:"path"`
	Width     int64        `json:"width"`
	Height    int64        `json:"height"`
	Blurhash  string       `json:"blurhash"`
	Provider  string       `json:"provider"`
	IsPrimary sql.NullBool `json:"is_primary"`
	IsLocked  sql.NullBool `json:"is_locked"`
	AddedAt   time.Time    `json:"added_at"`
}

func (q *Queries) ListImagesByItem(ctx context.Context, itemID string) ([]ListImagesByItemRow, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImagesByItemRow{}
	for rows.Next() {
		var i ListImagesByItemRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Type,
			&i.Path,
			&i.Width,
			&i.Height,
			&i.Blurhash,
			&i.Provider,
			&i.IsPrimary,
			&i.IsLocked,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImageLocked = `-- name: SetImageLocked :exec
UPDATE images SET is_locked = ? WHERE id = ?
`

type SetImageLockedParams struct {
	IsLocked sql.NullBool `json:"is_locked"`
	ID       string       `json:"id"`
}

func (q *Queries) SetImageLocked(ctx context.Context, arg SetImageLockedParams) error {
	_, err := q.db.ExecContext(ctx, setImageLocked, arg.IsLocked, arg.ID)
	return err
}

const setImagePrimary = `-- name: SetImagePrimary :exec
UPDATE images SET is_primary = 1 WHERE id = ? AND item_id = ? AND type = ?
`

type SetImagePrimaryParams struct {
	ID     string `json:"id"`
	ItemID string `json:"item_id"`
	Type   string `json:"type"`
}

func (q *Queries) SetImagePrimary(ctx context.Context, arg SetImagePrimaryParams) error {
	_, err := q.db.ExecContext(ctx, setImagePrimary, arg.ID, arg.ItemID, arg.Type)
	return err
}

const unsetPrimaryImages = `-- name: UnsetPrimaryImages :exec
UPDATE images SET is_primary = 0 WHERE item_id = ? AND type = ?
`

type UnsetPrimaryImagesParams struct {
	ItemID string `json:"item_id"`
	Type   string `json:"type"`
}

func (q *Queries) UnsetPrimaryImages(ctx context.Context, arg UnsetPrimaryImagesParams) error {
	_, err := q.db.ExecContext(ctx, unsetPrimaryImages, arg.ItemID, arg.Type)
	return err
}
