// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: iptv_scheduled_jobs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteIPTVScheduledJob = `-- name: DeleteIPTVScheduledJob :exec
DELETE FROM iptv_scheduled_jobs WHERE library_id = ? AND kind = ?
`

type DeleteIPTVScheduledJobParams struct {
	LibraryID string `json:"library_id"`
	Kind      string `json:"kind"`
}

func (q *Queries) DeleteIPTVScheduledJob(ctx context.Context, arg DeleteIPTVScheduledJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteIPTVScheduledJob, arg.LibraryID, arg.Kind)
	return err
}

const getIPTVScheduledJob = `-- name: GetIPTVScheduledJob :one
SELECT library_id, kind, interval_hours, enabled,
       last_run_at, last_status, last_error,
       last_duration_ms, created_at, updated_at
FROM iptv_scheduled_jobs
WHERE library_id = ? AND kind = ?
`

type GetIPTVScheduledJobParams struct {
	LibraryID string `json:"library_id"`
	Kind      string `json:"kind"`
}

func (q *Queries) GetIPTVScheduledJob(ctx context.Context, arg GetIPTVScheduledJobParams) (IptvScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, getIPTVScheduledJob, arg.LibraryID, arg.Kind)
	var i IptvScheduledJob
	err := row.Scan(
		&i.LibraryID,
		&i.Kind,
		&i.IntervalHours,
		&i.Enabled,
		&i.LastRunAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastDurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledIPTVScheduledJobs = `-- name: ListEnabledIPTVScheduledJobs :many

SELECT library_id, kind, interval_hours, enabled,
       last_run_at, last_status, last_error,
       last_duration_ms, created_at, updated_at
FROM iptv_scheduled_jobs
WHERE enabled = 1
ORDER BY last_run_at ASC NULLS FIRST
`

// Workers hot query. Filtered by enabled in SQL; due-ness is
// computed in Go (see ListDue) because date arithmetic on the
// multi-format-tolerant column would invite the same Scan problem
// we work around elsewhere.
func (q *Queries) ListEnabledIPTVScheduledJobs(ctx context.Context) ([]IptvScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledIPTVScheduledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IptvScheduledJob{}
	for rows.Next() {
		var i IptvScheduledJob
		if err := rows.Scan(
			&i.LibraryID,
			&i.Kind,
			&i.IntervalHours,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIPTVScheduledJobsByLibrary = `-- name: ListIPTVScheduledJobsByLibrary :many

SELECT library_id, kind, interval_hours, enabled,
       last_run_at, last_status, last_error,
       last_duration_ms, created_at, updated_at
FROM iptv_scheduled_jobs
WHERE library_id = ?
ORDER BY kind ASC
`

// Scheduled IPTV jobs (per-library M3U + EPG refresh automation).
//
// Table schema: migrations/sqlite/011_iptv_scheduled_jobs.sql.
// Composite PK: (library_id, kind in {'m3u_refresh','epg_refresh'}).
//
// Time handling: callers MUST normalise time.Time values to UTC
// before passing them in (see iptv_schedule_repository.go). The
// modernc.org/sqlite driver serialises time.Time with named-zone
// locations using a format the default Scan cannot parse, so we
// treat UTC-on-write as a hard contract. Reads land into stdlib
// time.Time / sql.NullTime without coerceSQLiteTime needing to
// intervene.
func (q *Queries) ListIPTVScheduledJobsByLibrary(ctx context.Context, libraryID string) ([]IptvScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listIPTVScheduledJobsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IptvScheduledJob{}
	for rows.Next() {
		var i IptvScheduledJob
		if err := rows.Scan(
			&i.LibraryID,
			&i.Kind,
			&i.IntervalHours,
			&i.Enabled,
			&i.LastRunAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastDurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordIPTVScheduledJobRun = `-- name: RecordIPTVScheduledJobRun :exec
UPDATE iptv_scheduled_jobs SET
    last_run_at      = ?,
    last_status      = ?,
    last_error       = ?,
    last_duration_ms = ?,
    updated_at       = ?
WHERE library_id = ? AND kind = ?
`

type RecordIPTVScheduledJobRunParams struct {
	LastRunAt      sql.NullTime `json:"last_run_at"`
	LastStatus     string       `json:"last_status"`
	LastError      string       `json:"last_error"`
	LastDurationMs int64        `json:"last_duration_ms"`
	UpdatedAt      time.Time    `json:"updated_at"`
	LibraryID      string       `json:"library_id"`
	Kind           string       `json:"kind"`
}

func (q *Queries) RecordIPTVScheduledJobRun(ctx context.Context, arg RecordIPTVScheduledJobRunParams) error {
	_, err := q.db.ExecContext(ctx, recordIPTVScheduledJobRun,
		arg.LastRunAt,
		arg.LastStatus,
		arg.LastError,
		arg.LastDurationMs,
		arg.UpdatedAt,
		arg.LibraryID,
		arg.Kind,
	)
	return err
}

const upsertIPTVScheduledJob = `-- name: UpsertIPTVScheduledJob :exec

INSERT INTO iptv_scheduled_jobs (library_id, kind, interval_hours, enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(library_id, kind) DO UPDATE SET
   interval_hours = excluded.interval_hours,
   enabled        = excluded.enabled,
   updated_at     = excluded.updated_at
`

type UpsertIPTVScheduledJobParams struct {
	LibraryID     string    `json:"library_id"`
	Kind          string    `json:"kind"`
	IntervalHours int64     `json:"interval_hours"`
	Enabled       bool      `json:"enabled"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// Preserves last_* fields by design: only the configuration
// (interval_hours / enabled) and updated_at change. The history
// (last_run_at, last_status, ...) survives reconfiguration.
func (q *Queries) UpsertIPTVScheduledJob(ctx context.Context, arg UpsertIPTVScheduledJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertIPTVScheduledJob,
		arg.LibraryID,
		arg.Kind,
		arg.IntervalHours,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
