// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: items.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countItemsByLibrary = `-- name: CountItemsByLibrary :one
SELECT COUNT(*) AS cnt FROM items WHERE library_id = ?
`

func (q *Queries) CountItemsByLibrary(ctx context.Context, libraryID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByLibrary, libraryID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createItem = `-- name: CreateItem :exec

INSERT INTO items (id, library_id, parent_id, type, title, sort_title, original_title,
    year, path, size, duration_ticks, container, fingerprint, season_number, episode_number,
    community_rating, content_rating, premiere_date, added_at, updated_at, is_available)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateItemParams struct {
	ID              string          `json:"id"`
	LibraryID       string          `json:"library_id"`
	ParentID        sql.NullString  `json:"parent_id"`
	Type            string          `json:"type"`
	Title           string          `json:"title"`
	SortTitle       string          `json:"sort_title"`
	OriginalTitle   sql.NullString  `json:"original_title"`
	Year            sql.NullInt64   `json:"year"`
	Path            sql.NullString  `json:"path"`
	Size            sql.NullInt64   `json:"size"`
	DurationTicks   sql.NullInt64   `json:"duration_ticks"`
	Container       sql.NullString  `json:"container"`
	Fingerprint     sql.NullString  `json:"fingerprint"`
	SeasonNumber    sql.NullInt64   `json:"season_number"`
	EpisodeNumber   sql.NullInt64   `json:"episode_number"`
	CommunityRating sql.NullFloat64 `json:"community_rating"`
	ContentRating   sql.NullString  `json:"content_rating"`
	PremiereDate    sql.NullTime    `json:"premiere_date"`
	AddedAt         time.Time       `json:"added_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	IsAvailable     bool            `json:"is_available"`
}

// Items (movies, series, seasons, episodes, albums, etc.).
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE items).
// NOTE: List and LatestItems use dynamic WHERE/FTS/cursor and stay raw SQL.
func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) error {
	_, err := q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.LibraryID,
		arg.ParentID,
		arg.Type,
		arg.Title,
		arg.SortTitle,
		arg.OriginalTitle,
		arg.Year,
		arg.Path,
		arg.Size,
		arg.DurationTicks,
		arg.Container,
		arg.Fingerprint,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.CommunityRating,
		arg.ContentRating,
		arg.PremiereDate,
		arg.AddedAt,
		arg.UpdatedAt,
		arg.IsAvailable,
	)
	return err
}

const deleteItem = `-- name: DeleteItem :execrows
DELETE FROM items WHERE id = ?
`

func (q *Queries) DeleteItem(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteItem, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteItemsByLibrary = `-- name: DeleteItemsByLibrary :exec
DELETE FROM items WHERE library_id = ?
`

func (q *Queries) DeleteItemsByLibrary(ctx context.Context, libraryID string) error {
	_, err := q.db.ExecContext(ctx, deleteItemsByLibrary, libraryID)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, library_id, parent_id, type, title, sort_title, original_title,
       year, path, size, duration_ticks, container, fingerprint, season_number,
       episode_number, community_rating, content_rating, premiere_date,
       added_at, updated_at, is_available
FROM items
WHERE id = ?
`

func (q *Queries) GetItemByID(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortTitle,
		&i.OriginalTitle,
		&i.Year,
		&i.Path,
		&i.Size,
		&i.DurationTicks,
		&i.Container,
		&i.Fingerprint,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.CommunityRating,
		&i.ContentRating,
		&i.PremiereDate,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.IsAvailable,
	)
	return i, err
}

const getItemByPath = `-- name: GetItemByPath :one
SELECT id, library_id, parent_id, type, title, sort_title, original_title,
       year, path, size, duration_ticks, container, fingerprint, season_number,
       episode_number, community_rating, content_rating, premiere_date,
       added_at, updated_at, is_available
FROM items
WHERE path = ?
`

func (q *Queries) GetItemByPath(ctx context.Context, path sql.NullString) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByPath, path)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ParentID,
		&i.Type,
		&i.Title,
		&i.SortTitle,
		&i.OriginalTitle,
		&i.Year,
		&i.Path,
		&i.Size,
		&i.DurationTicks,
		&i.Container,
		&i.Fingerprint,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.CommunityRating,
		&i.ContentRating,
		&i.PremiereDate,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.IsAvailable,
	)
	return i, err
}

const getItemChildren = `-- name: GetItemChildren :many
SELECT id, library_id, parent_id, type, title, sort_title, original_title,
       year, path, size, duration_ticks, container, season_number, episode_number,
       community_rating, added_at, updated_at, is_available
FROM items
WHERE parent_id = ?
ORDER BY COALESCE(season_number, 0), COALESCE(episode_number, 0), sort_title
`

type GetItemChildrenRow struct {
	ID              string          `json:"id"`
	LibraryID       string          `json:"library_id"`
	ParentID        sql.NullString  `json:"parent_id"`
	Type            string          `json:"type"`
	Title           string          `json:"title"`
	SortTitle       string          `json:"sort_title"`
	OriginalTitle   sql.NullString  `json:"original_title"`
	Year            sql.NullInt64   `json:"year"`
	Path            sql.NullString  `json:"path"`
	Size            sql.NullInt64   `json:"size"`
	DurationTicks   sql.NullInt64   `json:"duration_ticks"`
	Container       sql.NullString  `json:"container"`
	SeasonNumber    sql.NullInt64   `json:"season_number"`
	EpisodeNumber   sql.NullInt64   `json:"episode_number"`
	CommunityRating sql.NullFloat64 `json:"community_rating"`
	AddedAt         time.Time       `json:"added_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	IsAvailable     bool            `json:"is_available"`
}

func (q *Queries) GetItemChildren(ctx context.Context, parentID sql.NullString) ([]GetItemChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, getItemChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetItemChildrenRow{}
	for rows.Next() {
		var i GetItemChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ParentID,
			&i.Type,
			&i.Title,
			&i.SortTitle,
			&i.OriginalTitle,
			&i.Year,
			&i.Path,
			&i.Size,
			&i.DurationTicks,
			&i.Container,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.CommunityRating,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :execrows
UPDATE items SET title = ?, sort_title = ?, original_title = ?,
       year = ?, size = ?, duration_ticks = ?, container = ?,
       fingerprint = ?, season_number = ?, episode_number = ?,
       community_rating = ?, content_rating = ?,
       premiere_date = ?, updated_at = ?, is_available = ?
WHERE id = ?
`

type UpdateItemParams struct {
	Title           string          `json:"title"`
	SortTitle       string          `json:"sort_title"`
	OriginalTitle   sql.NullString  `json:"original_title"`
	Year            sql.NullInt64   `json:"year"`
	Size            sql.NullInt64   `json:"size"`
	DurationTicks   sql.NullInt64   `json:"duration_ticks"`
	Container       sql.NullString  `json:"container"`
	Fingerprint     sql.NullString  `json:"fingerprint"`
	SeasonNumber    sql.NullInt64   `json:"season_number"`
	EpisodeNumber   sql.NullInt64   `json:"episode_number"`
	CommunityRating sql.NullFloat64 `json:"community_rating"`
	ContentRating   sql.NullString  `json:"content_rating"`
	PremiereDate    sql.NullTime    `json:"premiere_date"`
	UpdatedAt       time.Time       `json:"updated_at"`
	IsAvailable     bool            `json:"is_available"`
	ID              string          `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateItem,
		arg.Title,
		arg.SortTitle,
		arg.OriginalTitle,
		arg.Year,
		arg.Size,
		arg.DurationTicks,
		arg.Container,
		arg.Fingerprint,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.CommunityRating,
		arg.ContentRating,
		arg.PremiereDate,
		arg.UpdatedAt,
		arg.IsAvailable,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
