// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: library_epg_sources.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createLibraryEPGSource = `-- name: CreateLibraryEPGSource :exec
INSERT INTO library_epg_sources
    (id, library_id, catalog_id, url, priority, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateLibraryEPGSourceParams struct {
	ID        string         `json:"id"`
	LibraryID string         `json:"library_id"`
	CatalogID sql.NullString `json:"catalog_id"`
	Url       string         `json:"url"`
	Priority  int64          `json:"priority"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) CreateLibraryEPGSource(ctx context.Context, arg CreateLibraryEPGSourceParams) error {
	_, err := q.db.ExecContext(ctx, createLibraryEPGSource,
		arg.ID,
		arg.LibraryID,
		arg.CatalogID,
		arg.Url,
		arg.Priority,
		arg.CreatedAt,
	)
	return err
}

const deleteLibraryEPGSource = `-- name: DeleteLibraryEPGSource :exec
DELETE FROM library_epg_sources WHERE id = ?
`

func (q *Queries) DeleteLibraryEPGSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLibraryEPGSource, id)
	return err
}

const getLibraryEPGSourceByID = `-- name: GetLibraryEPGSourceByID :one
SELECT id, library_id, COALESCE(catalog_id,'') AS catalog_id,
       url, priority, last_refreshed_at,
       COALESCE(last_status,'') AS last_status,
       COALESCE(last_error,'') AS last_error,
       last_program_count, last_channel_count, created_at
FROM library_epg_sources
WHERE id = ?
`

type GetLibraryEPGSourceByIDRow struct {
	ID               string       `json:"id"`
	LibraryID        string       `json:"library_id"`
	CatalogID        string       `json:"catalog_id"`
	Url              string       `json:"url"`
	Priority         int64        `json:"priority"`
	LastRefreshedAt  sql.NullTime `json:"last_refreshed_at"`
	LastStatus       string       `json:"last_status"`
	LastError        string       `json:"last_error"`
	LastProgramCount int64        `json:"last_program_count"`
	LastChannelCount int64        `json:"last_channel_count"`
	CreatedAt        time.Time    `json:"created_at"`
}

func (q *Queries) GetLibraryEPGSourceByID(ctx context.Context, id string) (GetLibraryEPGSourceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLibraryEPGSourceByID, id)
	var i GetLibraryEPGSourceByIDRow
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.CatalogID,
		&i.Url,
		&i.Priority,
		&i.LastRefreshedAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastProgramCount,
		&i.LastChannelCount,
		&i.CreatedAt,
	)
	return i, err
}

const listLibraryEPGSourcesByLibrary = `-- name: ListLibraryEPGSourcesByLibrary :many

SELECT id, library_id, COALESCE(catalog_id,'') AS catalog_id,
       url, priority, last_refreshed_at,
       COALESCE(last_status,'') AS last_status,
       COALESCE(last_error,'') AS last_error,
       last_program_count, last_channel_count, created_at
FROM library_epg_sources
WHERE library_id = ?
ORDER BY priority ASC, created_at ASC
`

type ListLibraryEPGSourcesByLibraryRow struct {
	ID               string       `json:"id"`
	LibraryID        string       `json:"library_id"`
	CatalogID        string       `json:"catalog_id"`
	Url              string       `json:"url"`
	Priority         int64        `json:"priority"`
	LastRefreshedAt  sql.NullTime `json:"last_refreshed_at"`
	LastStatus       string       `json:"last_status"`
	LastError        string       `json:"last_error"`
	LastProgramCount int64        `json:"last_program_count"`
	LastChannelCount int64        `json:"last_channel_count"`
	CreatedAt        time.Time    `json:"created_at"`
}

// Per-library EPG source list (multi-provider XMLTV configuration).
//
// Table schema: migrations/sqlite/007_library_epg_sources.sql.
// PK: (id). UNIQUE on (library_id, url) so a duplicate add raises a
// detectable constraint failure that the repo maps to
// ErrEPGSourceAlreadyAttached.
//
// COALESCE columns: catalog_id, last_refreshed_at, last_status and
// last_error are all nullable in storage. Reading them back with
// COALESCE keeps the consumer code free of NullString / NullTime
// branching except for last_refreshed_at, which still needs zero-
// value detection (we cannot tell "never refreshed" from an empty
// string). Falling back to sql.NullTime there.
func (q *Queries) ListLibraryEPGSourcesByLibrary(ctx context.Context, libraryID string) ([]ListLibraryEPGSourcesByLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryEPGSourcesByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryEPGSourcesByLibraryRow{}
	for rows.Next() {
		var i ListLibraryEPGSourcesByLibraryRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.CatalogID,
			&i.Url,
			&i.Priority,
			&i.LastRefreshedAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastProgramCount,
			&i.LastChannelCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextLibraryEPGSourcePriority = `-- name: NextLibraryEPGSourcePriority :one
SELECT COALESCE(MAX(priority), -1) AS max_priority
FROM library_epg_sources
WHERE library_id = ?
`

// The default-priority slot for a freshly-added source: one past the
// current max, so it runs last and can be reordered from the UI.
// COALESCE returns -1 for "no rows yet" so the repo can lift it to 0
// without splitting NullInt branches.
func (q *Queries) NextLibraryEPGSourcePriority(ctx context.Context, libraryID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, nextLibraryEPGSourcePriority, libraryID)
	var max_priority interface{}
	err := row.Scan(&max_priority)
	return max_priority, err
}

const recordLibraryEPGSourceRefresh = `-- name: RecordLibraryEPGSourceRefresh :exec
UPDATE library_epg_sources SET
    last_refreshed_at  = ?,
    last_status        = ?,
    last_error         = ?,
    last_program_count = ?,
    last_channel_count = ?
WHERE id = ?
`

type RecordLibraryEPGSourceRefreshParams struct {
	LastRefreshedAt  sql.NullTime   `json:"last_refreshed_at"`
	LastStatus       sql.NullString `json:"last_status"`
	LastError        sql.NullString `json:"last_error"`
	LastProgramCount int64          `json:"last_program_count"`
	LastChannelCount int64          `json:"last_channel_count"`
	ID               string         `json:"id"`
}

func (q *Queries) RecordLibraryEPGSourceRefresh(ctx context.Context, arg RecordLibraryEPGSourceRefreshParams) error {
	_, err := q.db.ExecContext(ctx, recordLibraryEPGSourceRefresh,
		arg.LastRefreshedAt,
		arg.LastStatus,
		arg.LastError,
		arg.LastProgramCount,
		arg.LastChannelCount,
		arg.ID,
	)
	return err
}

const updateLibraryEPGSourcePriority = `-- name: UpdateLibraryEPGSourcePriority :exec
UPDATE library_epg_sources SET priority = ?
WHERE id = ? AND library_id = ?
`

type UpdateLibraryEPGSourcePriorityParams struct {
	Priority  int64  `json:"priority"`
	ID        string `json:"id"`
	LibraryID string `json:"library_id"`
}

func (q *Queries) UpdateLibraryEPGSourcePriority(ctx context.Context, arg UpdateLibraryEPGSourcePriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateLibraryEPGSourcePriority, arg.Priority, arg.ID, arg.LibraryID)
	return err
}
