// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: libraries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteLibrary = `-- name: DeleteLibrary :execrows
DELETE FROM libraries WHERE id = ?
`

func (q *Queries) DeleteLibrary(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLibrary, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePathsByLibrary = `-- name: DeletePathsByLibrary :exec
DELETE FROM library_paths WHERE library_id = ?
`

func (q *Queries) DeletePathsByLibrary(ctx context.Context, libraryID string) error {
	_, err := q.db.ExecContext(ctx, deletePathsByLibrary, libraryID)
	return err
}

const getLibraryByID = `-- name: GetLibraryByID :one
SELECT id, name, content_type, scan_mode, COALESCE(scan_interval, '6h') AS scan_interval,
       COALESCE(m3u_url, '') AS m3u_url, COALESCE(epg_url, '') AS epg_url,
       COALESCE(refresh_interval, '24h') AS refresh_interval,
       created_at, updated_at
FROM libraries
WHERE id = ?
`

type GetLibraryByIDRow struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	ContentType     string    `json:"content_type"`
	ScanMode        string    `json:"scan_mode"`
	ScanInterval    string    `json:"scan_interval"`
	M3uUrl          string    `json:"m3u_url"`
	EpgUrl          string    `json:"epg_url"`
	RefreshInterval string    `json:"refresh_interval"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetLibraryByID(ctx context.Context, id string) (GetLibraryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLibraryByID, id)
	var i GetLibraryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContentType,
		&i.ScanMode,
		&i.ScanInterval,
		&i.M3uUrl,
		&i.EpgUrl,
		&i.RefreshInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantLibraryAccess = `-- name: GrantLibraryAccess :exec
INSERT OR IGNORE INTO library_access (user_id, library_id) VALUES (?, ?)
`

type GrantLibraryAccessParams struct {
	UserID    string `json:"user_id"`
	LibraryID string `json:"library_id"`
}

func (q *Queries) GrantLibraryAccess(ctx context.Context, arg GrantLibraryAccessParams) error {
	_, err := q.db.ExecContext(ctx, grantLibraryAccess, arg.UserID, arg.LibraryID)
	return err
}

const insertLibrary = `-- name: InsertLibrary :exec

INSERT INTO libraries (id, name, content_type, scan_mode, scan_interval,
    m3u_url, epg_url, refresh_interval, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertLibraryParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	ContentType     string         `json:"content_type"`
	ScanMode        string         `json:"scan_mode"`
	ScanInterval    sql.NullString `json:"scan_interval"`
	M3uUrl          sql.NullString `json:"m3u_url"`
	EpgUrl          sql.NullString `json:"epg_url"`
	RefreshInterval sql.NullString `json:"refresh_interval"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

// Library management (media libraries, paths, access control).
//
// Tables: libraries, library_paths, library_access.
func (q *Queries) InsertLibrary(ctx context.Context, arg InsertLibraryParams) error {
	_, err := q.db.ExecContext(ctx, insertLibrary,
		arg.ID,
		arg.Name,
		arg.ContentType,
		arg.ScanMode,
		arg.ScanInterval,
		arg.M3uUrl,
		arg.EpgUrl,
		arg.RefreshInterval,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertLibraryPath = `-- name: InsertLibraryPath :exec
INSERT INTO library_paths (library_id, path) VALUES (?, ?)
`

type InsertLibraryPathParams struct {
	LibraryID string `json:"library_id"`
	Path      string `json:"path"`
}

func (q *Queries) InsertLibraryPath(ctx context.Context, arg InsertLibraryPathParams) error {
	_, err := q.db.ExecContext(ctx, insertLibraryPath, arg.LibraryID, arg.Path)
	return err
}

const listAllPaths = `-- name: ListAllPaths :many
SELECT library_id, path FROM library_paths ORDER BY library_id, path
`

func (q *Queries) ListAllPaths(ctx context.Context) ([]LibraryPath, error) {
	rows, err := q.db.QueryContext(ctx, listAllPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryPath{}
	for rows.Next() {
		var i LibraryPath
		if err := rows.Scan(&i.LibraryID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, content_type, scan_mode, COALESCE(scan_interval, '6h') AS scan_interval,
       COALESCE(m3u_url, '') AS m3u_url, COALESCE(epg_url, '') AS epg_url,
       COALESCE(refresh_interval, '24h') AS refresh_interval,
       created_at, updated_at
FROM libraries
ORDER BY name
`

type ListLibrariesRow struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	ContentType     string    `json:"content_type"`
	ScanMode        string    `json:"scan_mode"`
	ScanInterval    string    `json:"scan_interval"`
	M3uUrl          string    `json:"m3u_url"`
	EpgUrl          string    `json:"epg_url"`
	RefreshInterval string    `json:"refresh_interval"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListLibraries(ctx context.Context) ([]ListLibrariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibrariesRow{}
	for rows.Next() {
		var i ListLibrariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentType,
			&i.ScanMode,
			&i.ScanInterval,
			&i.M3uUrl,
			&i.EpgUrl,
			&i.RefreshInterval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibrariesForUser = `-- name: ListLibrariesForUser :many
SELECT l.id, l.name, l.content_type, l.scan_mode,
       COALESCE(l.scan_interval, '6h') AS scan_interval,
       COALESCE(l.m3u_url, '') AS m3u_url,
       COALESCE(l.epg_url, '') AS epg_url,
       COALESCE(l.refresh_interval, '24h') AS refresh_interval,
       l.created_at, l.updated_at
FROM libraries l
LEFT JOIN library_access la ON la.library_id = l.id AND la.user_id = ?
WHERE la.user_id IS NOT NULL
   OR NOT EXISTS (SELECT 1 FROM library_access WHERE library_id = l.id)
ORDER BY l.name
`

type ListLibrariesForUserRow struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	ContentType     string    `json:"content_type"`
	ScanMode        string    `json:"scan_mode"`
	ScanInterval    string    `json:"scan_interval"`
	M3uUrl          string    `json:"m3u_url"`
	EpgUrl          string    `json:"epg_url"`
	RefreshInterval string    `json:"refresh_interval"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListLibrariesForUser(ctx context.Context, userID string) ([]ListLibrariesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibrariesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibrariesForUserRow{}
	for rows.Next() {
		var i ListLibrariesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentType,
			&i.ScanMode,
			&i.ScanInterval,
			&i.M3uUrl,
			&i.EpgUrl,
			&i.RefreshInterval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathsByLibrary = `-- name: ListPathsByLibrary :many
SELECT path FROM library_paths WHERE library_id = ? ORDER BY path
`

func (q *Queries) ListPathsByLibrary(ctx context.Context, libraryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPathsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLibraryAccess = `-- name: RevokeLibraryAccess :exec
DELETE FROM library_access WHERE user_id = ? AND library_id = ?
`

type RevokeLibraryAccessParams struct {
	UserID    string `json:"user_id"`
	LibraryID string `json:"library_id"`
}

func (q *Queries) RevokeLibraryAccess(ctx context.Context, arg RevokeLibraryAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokeLibraryAccess, arg.UserID, arg.LibraryID)
	return err
}

const updateLibrary = `-- name: UpdateLibrary :execrows
UPDATE libraries SET name = ?, content_type = ?, scan_mode = ?, scan_interval = ?,
       m3u_url = ?, epg_url = ?, refresh_interval = ?, updated_at = ?
WHERE id = ?
`

type UpdateLibraryParams struct {
	Name            string         `json:"name"`
	ContentType     string         `json:"content_type"`
	ScanMode        string         `json:"scan_mode"`
	ScanInterval    sql.NullString `json:"scan_interval"`
	M3uUrl          sql.NullString `json:"m3u_url"`
	EpgUrl          sql.NullString `json:"epg_url"`
	RefreshInterval sql.NullString `json:"refresh_interval"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLibrary,
		arg.Name,
		arg.ContentType,
		arg.ScanMode,
		arg.ScanInterval,
		arg.M3uUrl,
		arg.EpgUrl,
		arg.RefreshInterval,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
