// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ActivityLog struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Type      string         `json:"type"`
	ItemID    sql.NullString `json:"item_id"`
	Severity  sql.NullString `json:"severity"`
	Message   string         `json:"message"`
	DataJson  sql.NullString `json:"data_json"`
	CreatedAt time.Time      `json:"created_at"`
}

type AncestorID struct {
	ItemID     string `json:"item_id"`
	AncestorID string `json:"ancestor_id"`
}

type ApiKey struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	KeyHash   string       `json:"key_hash"`
	CreatedBy string       `json:"created_by"`
	CreatedAt time.Time    `json:"created_at"`
	LastUsed  sql.NullTime `json:"last_used"`
}

type Channel struct {
	ID        string         `json:"id"`
	LibraryID string         `json:"library_id"`
	Name      string         `json:"name"`
	Number    sql.NullInt64  `json:"number"`
	GroupName sql.NullString `json:"group_name"`
	LogoUrl   sql.NullString `json:"logo_url"`
	StreamUrl string         `json:"stream_url"`
	TvgID     sql.NullString `json:"tvg_id"`
	Language  sql.NullString `json:"language"`
	Country   sql.NullString `json:"country"`
	IsActive  bool           `json:"is_active"`
	AddedAt   time.Time      `json:"added_at"`
}

type Chapter struct {
	ItemID     string         `json:"item_id"`
	StartTicks int64          `json:"start_ticks"`
	EndTicks   int64          `json:"end_ticks"`
	Title      sql.NullString `json:"title"`
	ImagePath  sql.NullString `json:"image_path"`
}

type EpgProgram struct {
	ID          string         `json:"id"`
	ChannelID   string         `json:"channel_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	IconUrl     sql.NullString `json:"icon_url"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
}

type ExternalID struct {
	ItemID     string `json:"item_id"`
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

type Image struct {
	ID        string         `json:"id"`
	ItemID    string         `json:"item_id"`
	Type      string         `json:"type"`
	Path      string         `json:"path"`
	Width     sql.NullInt64  `json:"width"`
	Height    sql.NullInt64  `json:"height"`
	Blurhash  sql.NullString `json:"blurhash"`
	Provider  sql.NullString `json:"provider"`
	IsPrimary sql.NullBool   `json:"is_primary"`
	AddedAt   time.Time      `json:"added_at"`
}

type Item struct {
	ID              string          `json:"id"`
	LibraryID       string          `json:"library_id"`
	ParentID        sql.NullString  `json:"parent_id"`
	Type            string          `json:"type"`
	Title           string          `json:"title"`
	SortTitle       string          `json:"sort_title"`
	OriginalTitle   sql.NullString  `json:"original_title"`
	Year            sql.NullInt64   `json:"year"`
	Path            sql.NullString  `json:"path"`
	Size            sql.NullInt64   `json:"size"`
	DurationTicks   sql.NullInt64   `json:"duration_ticks"`
	Container       sql.NullString  `json:"container"`
	Fingerprint     sql.NullString  `json:"fingerprint"`
	SeasonNumber    sql.NullInt64   `json:"season_number"`
	EpisodeNumber   sql.NullInt64   `json:"episode_number"`
	CommunityRating sql.NullFloat64 `json:"community_rating"`
	ContentRating   sql.NullString  `json:"content_rating"`
	PremiereDate    sql.NullTime    `json:"premiere_date"`
	AddedAt         time.Time       `json:"added_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	IsAvailable     bool            `json:"is_available"`
}

type ItemPerson struct {
	ItemID        string         `json:"item_id"`
	PersonID      string         `json:"person_id"`
	Role          string         `json:"role"`
	CharacterName sql.NullString `json:"character_name"`
	SortOrder     sql.NullInt64  `json:"sort_order"`
}

type ItemValue struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Value      string `json:"value"`
	CleanValue string `json:"clean_value"`
}

type ItemValueMap struct {
	ItemID  string `json:"item_id"`
	ValueID string `json:"value_id"`
}

type ItemsFt struct {
	Title         string `json:"title"`
	OriginalTitle string `json:"original_title"`
}

type JwtSigningKey struct {
	ID        string       `json:"id"`
	Secret    string       `json:"secret"`
	CreatedAt time.Time    `json:"created_at"`
	RetiredAt sql.NullTime `json:"retired_at"`
}

type Library struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	ContentType     string         `json:"content_type"`
	ScanMode        string         `json:"scan_mode"`
	ScanInterval    sql.NullString `json:"scan_interval"`
	M3uUrl          sql.NullString `json:"m3u_url"`
	EpgUrl          sql.NullString `json:"epg_url"`
	RefreshInterval sql.NullString `json:"refresh_interval"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type LibraryAccess struct {
	UserID    string `json:"user_id"`
	LibraryID string `json:"library_id"`
}

type LibraryPath struct {
	LibraryID string `json:"library_id"`
	Path      string `json:"path"`
}

type MediaSegment struct {
	ID         string `json:"id"`
	ItemID     string `json:"item_id"`
	Type       string `json:"type"`
	StartTicks int64  `json:"start_ticks"`
	EndTicks   int64  `json:"end_ticks"`
}

type MediaStream struct {
	ItemID            string          `json:"item_id"`
	StreamIndex       int64           `json:"stream_index"`
	StreamType        string          `json:"stream_type"`
	Codec             sql.NullString  `json:"codec"`
	Profile           sql.NullString  `json:"profile"`
	Bitrate           sql.NullInt64   `json:"bitrate"`
	Width             sql.NullInt64   `json:"width"`
	Height            sql.NullInt64   `json:"height"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	HdrType           sql.NullString  `json:"hdr_type"`
	ColorSpace        sql.NullString  `json:"color_space"`
	Channels          sql.NullInt64   `json:"channels"`
	SampleRate        sql.NullInt64   `json:"sample_rate"`
	Language          sql.NullString  `json:"language"`
	Title             sql.NullString  `json:"title"`
	IsDefault         sql.NullBool    `json:"is_default"`
	IsForced          sql.NullBool    `json:"is_forced"`
	IsHearingImpaired sql.NullBool    `json:"is_hearing_impaired"`
}

type Metadata struct {
	ItemID     string         `json:"item_id"`
	Overview   sql.NullString `json:"overview"`
	Tagline    sql.NullString `json:"tagline"`
	Studio     sql.NullString `json:"studio"`
	GenresJson sql.NullString `json:"genres_json"`
	TagsJson   sql.NullString `json:"tags_json"`
}

type Person struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Type      sql.NullString `json:"type"`
	ThumbPath sql.NullString `json:"thumb_path"`
}

type Provider struct {
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	Version    string         `json:"version"`
	Status     string         `json:"status"`
	Priority   int64          `json:"priority"`
	ConfigJson sql.NullString `json:"config_json"`
	ApiKey     sql.NullString `json:"api_key"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Session struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	DeviceName       string         `json:"device_name"`
	DeviceID         string         `json:"device_id"`
	IpAddress        sql.NullString `json:"ip_address"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	CreatedAt        time.Time      `json:"created_at"`
	LastActiveAt     time.Time      `json:"last_active_at"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

type TrickplayInfo struct {
	ItemID     string `json:"item_id"`
	Width      int64  `json:"width"`
	Height     int64  `json:"height"`
	TileWidth  int64  `json:"tile_width"`
	TileHeight int64  `json:"tile_height"`
	ThumbCount int64  `json:"thumb_count"`
	IntervalMs int64  `json:"interval_ms"`
	SpritePath string `json:"sprite_path"`
}

type User struct {
	ID                  string         `json:"id"`
	Username            string         `json:"username"`
	DisplayName         string         `json:"display_name"`
	PasswordHash        string         `json:"password_hash"`
	AvatarPath          sql.NullString `json:"avatar_path"`
	Role                string         `json:"role"`
	IsActive            bool           `json:"is_active"`
	MaxSessions         int64          `json:"max_sessions"`
	SubtitleLanguage    sql.NullString `json:"subtitle_language"`
	AudioLanguage       sql.NullString `json:"audio_language"`
	MaxStreamingQuality sql.NullString `json:"max_streaming_quality"`
	EnableAutoPlay      bool           `json:"enable_auto_play"`
	Theme               sql.NullString `json:"theme"`
	CreatedAt           time.Time      `json:"created_at"`
	LastLoginAt         sql.NullTime   `json:"last_login_at"`
}

type UserDatum struct {
	UserID              string        `json:"user_id"`
	ItemID              string        `json:"item_id"`
	PositionTicks       sql.NullInt64 `json:"position_ticks"`
	PlayCount           sql.NullInt64 `json:"play_count"`
	Completed           sql.NullBool  `json:"completed"`
	IsFavorite          sql.NullBool  `json:"is_favorite"`
	Liked               sql.NullBool  `json:"liked"`
	AudioStreamIndex    sql.NullInt64 `json:"audio_stream_index"`
	SubtitleStreamIndex sql.NullInt64 `json:"subtitle_stream_index"`
	LastPlayedAt        sql.NullTime  `json:"last_played_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

type WebhookConfig struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Url          string         `json:"url"`
	Method       string         `json:"method"`
	EventsJson   string         `json:"events_json"`
	HeadersJson  sql.NullString `json:"headers_json"`
	BodyTemplate sql.NullString `json:"body_template"`
	RetryCount   sql.NullInt64  `json:"retry_count"`
	TimeoutSec   sql.NullInt64  `json:"timeout_sec"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
}

type WebhookLog struct {
	ID           string         `json:"id"`
	WebhookID    string         `json:"webhook_id"`
	EventType    string         `json:"event_type"`
	Status       string         `json:"status"`
	ResponseCode sql.NullInt64  `json:"response_code"`
	ResponseBody sql.NullString `json:"response_body"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
}
