// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUnreadNotificationsForUser = `-- name: CountUnreadNotificationsForUser :one
SELECT COUNT(*) FROM notifications
WHERE user_id = ? AND read_at IS NULL
`

// Lo consulta el badge del header cada vez que llega un evento de
// notification.created por SSE. El indice parcial sobre read_at IS NULL
// (migration 049) hace que esto sea O(1) incluso con miles de leidas
// acumuladas.
func (q *Queries) CountUnreadNotificationsForUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotificationsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldReadNotifications = `-- name: DeleteOldReadNotifications :execrows
DELETE FROM notifications
WHERE read_at IS NOT NULL AND read_at < ?
`

// Limpieza periodica: borrar las leidas con mas de 30 dias para que
// la tabla no crezca sin limite. Las no-leidas se conservan siempre.
func (q *Queries) DeleteOldReadNotifications(ctx context.Context, readAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldReadNotifications, readAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertNotification = `-- name: InsertNotification :exec

INSERT INTO notifications
    (id, user_id, kind, title, body, link, payload, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNotificationParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Kind      string    `json:"kind"`
	Title     string    `json:"title"`
	Body      string    `json:"body"`
	Link      string    `json:"link"`
	Payload   string    `json:"payload"`
	CreatedAt time.Time `json:"created_at"`
}

// Notifications: inbox por usuario. Feature-agnostico - el discriminador
// es la columna `kind` (string libre) y el `payload` JSON. Schema en
// migrations/sqlite/049.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.ExecContext(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, kind, title, body, link, payload, created_at, read_at
FROM notifications
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListNotificationsForUserParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

// Listado del dropdown: ultimas N notificaciones del usuario, mas
// recientes arriba. El frontend pagina con limit alto (50) - el
// dropdown solo muestra ~10, pero el "ver todas" usa la misma query.
func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Payload,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsReadForUser = `-- name: MarkAllNotificationsReadForUser :execrows
UPDATE notifications
SET read_at = ?
WHERE user_id = ? AND read_at IS NULL
`

type MarkAllNotificationsReadForUserParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	UserID string       `json:"user_id"`
}

func (q *Queries) MarkAllNotificationsReadForUser(ctx context.Context, arg MarkAllNotificationsReadForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsReadForUser, arg.ReadAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications
SET read_at = ?
WHERE id = ? AND user_id = ? AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ReadAt sql.NullTime `json:"read_at"`
	ID     string       `json:"id"`
	UserID string       `json:"user_id"`
}

// execrows: el handler distingue "ya estaba leida o no existia" de
// "marcada ahora" para no devolver 404 espurio.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, arg.ReadAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
