// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: people.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPerson = `-- name: CreatePerson :exec
INSERT INTO people (id, name, type, thumb_path) VALUES (?, ?, ?, ?)
`

type CreatePersonParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	ThumbPath string `json:"thumb_path"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) error {
	_, err := q.db.ExecContext(ctx, createPerson, arg.ID, arg.Name, arg.Type, arg.ThumbPath)
	return err
}

const deleteItemPeople = `-- name: DeleteItemPeople :exec
DELETE FROM item_people WHERE item_id = ?
`

// Clear an item's existing cast/crew before re-inserting. Avoids
// having to diff the new list against the old one — re-scans cost a
// few writes per item rather than a comparison pass. The composite
// PK on item_people means simple DELETE WHERE item_id = ? is the
// whole story.
func (q *Queries) DeleteItemPeople(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteItemPeople, itemID)
	return err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, name, COALESCE(type, '') AS type, COALESCE(thumb_path, '') AS thumb_path
FROM people
WHERE id = ?
`

type GetPersonByIDRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	ThumbPath string `json:"thumb_path"`
}

func (q *Queries) GetPersonByID(ctx context.Context, id string) (GetPersonByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonByID, id)
	var i GetPersonByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Type, &i.ThumbPath)
	return i, err
}

const getPersonByName = `-- name: GetPersonByName :one
SELECT id, name, COALESCE(type, '') AS type, COALESCE(thumb_path, '') AS thumb_path
FROM people
WHERE name = ?
LIMIT 1
`

type GetPersonByNameRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	ThumbPath string `json:"thumb_path"`
}

func (q *Queries) GetPersonByName(ctx context.Context, name string) (GetPersonByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getPersonByName, name)
	var i GetPersonByNameRow
	err := row.Scan(&i.ID, &i.Name, &i.Type, &i.ThumbPath)
	return i, err
}

const insertItemPerson = `-- name: InsertItemPerson :exec
INSERT INTO item_people (item_id, person_id, role, character_name, sort_order)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(item_id, person_id, role) DO UPDATE SET
    character_name = excluded.character_name,
    sort_order = excluded.sort_order
`

type InsertItemPersonParams struct {
	ItemID        string `json:"item_id"`
	PersonID      string `json:"person_id"`
	Role          string `json:"role"`
	CharacterName string `json:"character_name"`
	SortOrder     int64  `json:"sort_order"`
}

func (q *Queries) InsertItemPerson(ctx context.Context, arg InsertItemPersonParams) error {
	_, err := q.db.ExecContext(ctx, insertItemPerson,
		arg.ItemID,
		arg.PersonID,
		arg.Role,
		arg.CharacterName,
		arg.SortOrder,
	)
	return err
}

const listItemPeople = `-- name: ListItemPeople :many
SELECT
    ip.person_id,
    ip.role,
    COALESCE(ip.character_name, '') AS character_name,
    COALESCE(ip.sort_order, 0) AS sort_order,
    p.name,
    COALESCE(p.type, '') AS person_type,
    COALESCE(p.thumb_path, '') AS thumb_path
FROM item_people ip
JOIN people p ON p.id = ip.person_id
WHERE ip.item_id = ?
ORDER BY ip.sort_order ASC, p.name ASC
`

type ListItemPeopleRow struct {
	PersonID      string `json:"person_id"`
	Role          string `json:"role"`
	CharacterName string `json:"character_name"`
	SortOrder     int64  `json:"sort_order"`
	Name          string `json:"name"`
	PersonType    string `json:"person_type"`
	ThumbPath     string `json:"thumb_path"`
}

// Returns the cast/crew rows for an item joined with the person
// record so the caller gets one struct per row. Ordered by
// sort_order so TMDb's "billing position" ranking surfaces directly
// to the UI without a client-side sort.
func (q *Queries) ListItemPeople(ctx context.Context, itemID string) ([]ListItemPeopleRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemPeople, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemPeopleRow
	for rows.Next() {
		var i ListItemPeopleRow
		if err := rows.Scan(
			&i.PersonID,
			&i.Role,
			&i.CharacterName,
			&i.SortOrder,
			&i.Name,
			&i.PersonType,
			&i.ThumbPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilmographyByPerson = `-- name: ListFilmographyByPerson :many
SELECT
    i.id AS item_id,
    i.type,
    i.title,
    i.year,
    ip.role,
    COALESCE(ip.character_name, '') AS character_name,
    COALESCE(ip.sort_order, 0) AS sort_order
FROM item_people ip
JOIN items i ON i.id = ip.item_id
WHERE ip.person_id = ?
  AND i.type IN ('movie', 'series')
  AND i.is_available = 1
ORDER BY COALESCE(i.year, 0) DESC, i.title ASC, ip.sort_order ASC
`

type ListFilmographyByPersonRow struct {
	ItemID        string        `json:"item_id"`
	Type          string        `json:"type"`
	Title         string        `json:"title"`
	Year          sql.NullInt64 `json:"year"`
	Role          string        `json:"role"`
	CharacterName string        `json:"character_name"`
	SortOrder     int64         `json:"sort_order"`
}

// Filmography: every movie + series this person has a direct credit
// on. Episode-level credits drop through for now (parent series
// usually carries the same person at the top level — TMDb is
// consistent there). Sorted newest-first; rows for the same item
// but different role (e.g. actor + writer on the same movie) are
// returned both — the caller dedupes keeping the lowest sort_order.
func (q *Queries) ListFilmographyByPerson(ctx context.Context, personID string) ([]ListFilmographyByPersonRow, error) {
	rows, err := q.db.QueryContext(ctx, listFilmographyByPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilmographyByPersonRow
	for rows.Next() {
		var i ListFilmographyByPersonRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Type,
			&i.Title,
			&i.Year,
			&i.Role,
			&i.CharacterName,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPersonThumbPath = `-- name: SetPersonThumbPath :exec
UPDATE people SET thumb_path = ? WHERE id = ?
`

type SetPersonThumbPathParams struct {
	ThumbPath string `json:"thumb_path"`
	ID        string `json:"id"`
}

func (q *Queries) SetPersonThumbPath(ctx context.Context, arg SetPersonThumbPathParams) error {
	_, err := q.db.ExecContext(ctx, setPersonThumbPath, arg.ThumbPath, arg.ID)
	return err
}
