// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: providers.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE name = ?
`

func (q *Queries) DeleteProvider(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteProvider, name)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT name, type, version, status, priority,
       config_json, api_key, created_at, updated_at
FROM providers
WHERE name = ?
`

func (q *Queries) GetProvider(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRowContext(ctx, getProvider, name)
	var i Provider
	err := row.Scan(
		&i.Name,
		&i.Type,
		&i.Version,
		&i.Status,
		&i.Priority,
		&i.ConfigJson,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProviders = `-- name: ListActiveProviders :many
SELECT name, type, version, status, priority,
       config_json, api_key, created_at, updated_at
FROM providers
WHERE status = 'active'
ORDER BY priority, name
`

func (q *Queries) ListActiveProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listActiveProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Version,
			&i.Status,
			&i.Priority,
			&i.ConfigJson,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT name, type, version, status, priority,
       config_json, api_key, created_at, updated_at
FROM providers
ORDER BY priority, name
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Version,
			&i.Status,
			&i.Priority,
			&i.ConfigJson,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByType = `-- name: ListProvidersByType :many
SELECT name, type, version, status, priority,
       config_json, api_key, created_at, updated_at
FROM providers
WHERE type = ? AND status = 'active'
ORDER BY priority, name
`

func (q *Queries) ListProvidersByType(ctx context.Context, type_ string) ([]Provider, error) {
	rows, err := q.db.QueryContext(ctx, listProvidersByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Version,
			&i.Status,
			&i.Priority,
			&i.ConfigJson,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderStatus = `-- name: SetProviderStatus :execrows
UPDATE providers
SET status = ?, updated_at = ?
WHERE name = ?
`

type SetProviderStatusParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

func (q *Queries) SetProviderStatus(ctx context.Context, arg SetProviderStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProviderStatus, arg.Status, arg.UpdatedAt, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProvider = `-- name: UpsertProvider :exec

INSERT INTO providers (
    name, type, version, status, priority,
    config_json, api_key, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    type = excluded.type,
    version = excluded.version,
    status = excluded.status,
    priority = excluded.priority,
    config_json = excluded.config_json,
    api_key = excluded.api_key,
    updated_at = excluded.updated_at
`

type UpsertProviderParams struct {
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	Version    string         `json:"version"`
	Status     string         `json:"status"`
	Priority   int64          `json:"priority"`
	ConfigJson sql.NullString `json:"config_json"`
	ApiKey     sql.NullString `json:"api_key"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// Provider configurations (TMDb, Fanart, OpenSubtitles, ...).
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE providers).
// Runtime registry + api-key sourcing lives in internal/provider/manager.go.
func (q *Queries) UpsertProvider(ctx context.Context, arg UpsertProviderParams) error {
	_, err := q.db.ExecContext(ctx, upsertProvider,
		arg.Name,
		arg.Type,
		arg.Version,
		arg.Status,
		arg.Priority,
		arg.ConfigJson,
		arg.ApiKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
