// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	// JWT signing keys for rotation with overlap.
	//
	// Table schema lives in migrations/sqlite/004_jwt_signing_keys.sql.
	// The repository (signing_key_repository.go) is a thin adapter around
	// these queries. Rotation/overlap policy lives in internal/auth/keystore.go.
	CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error
	DeleteRetiredSigningKeysBefore(ctx context.Context, retiredAt sql.NullTime) (int64, error)
	GetSigningKey(ctx context.Context, id string) (JwtSigningKey, error)
	ListActiveSigningKeys(ctx context.Context) ([]JwtSigningKey, error)
	ListSigningKeys(ctx context.Context) ([]JwtSigningKey, error)
	SetSigningKeyRetiredAt(ctx context.Context, arg SetSigningKeyRetiredAtParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
