// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountExternalIDsByItem(ctx context.Context, itemID string) (int64, error)
	CountSessionsByUser(ctx context.Context, userID string) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Auth sessions: one row per active login (refresh token lives here hashed).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE sessions).
	// Rotation/max-sessions policy lives in internal/auth/service.go.
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// JWT signing keys for rotation with overlap.
	//
	// Table schema lives in migrations/sqlite/004_jwt_signing_keys.sql.
	// The repository (signing_key_repository.go) is a thin adapter around
	// these queries. Rotation/overlap policy lives in internal/auth/keystore.go.
	CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAllSessionsByUser(ctx context.Context, userID string) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	// Media stream tracks (video, audio, subtitle) per item.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE media_streams).
	// PK: (item_id, stream_index).
	DeleteMediaStreamsByItem(ctx context.Context, itemID string) error
	// Subquery aliased to 's' because sqlc needs unambiguous column resolution
	// when the same table appears twice in scope.
	DeleteOldestSessionByUser(ctx context.Context, userID string) error
	DeleteProvider(ctx context.Context, name string) error
	DeleteRetiredSigningKeysBefore(ctx context.Context, retiredAt sql.NullTime) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) error
	DeleteUser(ctx context.Context, id string) (int64, error)
	GetExternalIDByProvider(ctx context.Context, arg GetExternalIDByProviderParams) (ExternalID, error)
	GetProvider(ctx context.Context, name string) (Provider, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSigningKey(ctx context.Context, id string) (JwtSigningKey, error)
	// User accounts.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE users).
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	InsertMediaStream(ctx context.Context, arg InsertMediaStreamParams) error
	ListActiveProviders(ctx context.Context) ([]Provider, error)
	ListActiveSigningKeys(ctx context.Context) ([]JwtSigningKey, error)
	ListExternalIDsByItem(ctx context.Context, itemID string) ([]ExternalID, error)
	ListMediaStreamsByItem(ctx context.Context, itemID string) ([]ListMediaStreamsByItemRow, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListProvidersByType(ctx context.Context, type_ string) ([]Provider, error)
	ListSessionsByUser(ctx context.Context, userID string) ([]Session, error)
	ListSigningKeys(ctx context.Context) ([]JwtSigningKey, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SetProviderStatus(ctx context.Context, arg SetProviderStatusParams) (int64, error)
	SetSigningKeyRetiredAt(ctx context.Context, arg SetSigningKeyRetiredAtParams) (int64, error)
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	// External ID mappings (tmdb, imdb, tvdb, ...) for items.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE external_ids).
	// PK: (item_id, provider).
	UpsertExternalID(ctx context.Context, arg UpsertExternalIDParams) error
	// Provider configurations (TMDb, Fanart, OpenSubtitles, ...).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE providers).
	// Runtime registry + api-key sourcing lives in internal/provider/manager.go.
	UpsertProvider(ctx context.Context, arg UpsertProviderParams) error
}

var _ Querier = (*Queries)(nil)
