// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countSessionsByUser = `-- name: CountSessionsByUser :one
SELECT COUNT(*) FROM sessions WHERE user_id = ?
`

func (q *Queries) CountSessionsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO sessions (
    id, user_id, device_name, device_id, ip_address,
    refresh_token_hash, created_at, last_active_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	UserID           string         `json:"user_id"`
	DeviceName       string         `json:"device_name"`
	DeviceID         string         `json:"device_id"`
	IpAddress        sql.NullString `json:"ip_address"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	CreatedAt        time.Time      `json:"created_at"`
	LastActiveAt     time.Time      `json:"last_active_at"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

// Auth sessions: one row per active login (refresh token lives here hashed).
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE sessions).
// Rotation/max-sessions policy lives in internal/auth/service.go.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceName,
		arg.DeviceID,
		arg.IpAddress,
		arg.RefreshTokenHash,
		arg.CreatedAt,
		arg.LastActiveAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAllSessionsByUser = `-- name: DeleteAllSessionsByUser :execrows
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteAllSessionsByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllSessionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOldestSessionByUser = `-- name: DeleteOldestSessionByUser :exec
DELETE FROM sessions WHERE id = (
    SELECT s.id FROM sessions s
    WHERE s.user_id = ?
    ORDER BY s.last_active_at ASC, s.created_at ASC
    LIMIT 1
)
`

// Subquery aliased to 's' because sqlc needs unambiguous column resolution
// when the same table appears twice in scope.
func (q *Queries) DeleteOldestSessionByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteOldestSessionByUser, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionByRefreshTokenHash = `-- name: DeleteSessionByRefreshTokenHash :exec
DELETE FROM sessions WHERE refresh_token_hash = ?
`

func (q *Queries) DeleteSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByRefreshTokenHash, refreshTokenHash)
	return err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, device_name, device_id, ip_address,
       refresh_token_hash, created_at, last_active_at, expires_at
FROM sessions
WHERE refresh_token_hash = ?
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceID,
		&i.IpAddress,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, device_name, device_id, ip_address,
       refresh_token_hash, created_at, last_active_at, expires_at
FROM sessions
WHERE user_id = ?
ORDER BY last_active_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceID,
			&i.IpAddress,
			&i.RefreshTokenHash,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionLastActive = `-- name: UpdateSessionLastActive :exec
UPDATE sessions SET last_active_at = ? WHERE id = ?
`

type UpdateSessionLastActiveParams struct {
	LastActiveAt time.Time `json:"last_active_at"`
	ID           string    `json:"id"`
}

func (q *Queries) UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastActive, arg.LastActiveAt, arg.ID)
	return err
}
