// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signing_keys.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createSigningKey = `-- name: CreateSigningKey :exec

INSERT INTO jwt_signing_keys (id, secret, created_at, retired_at)
VALUES (?, ?, ?, ?)
`

type CreateSigningKeyParams struct {
	ID        string       `json:"id"`
	Secret    string       `json:"secret"`
	CreatedAt time.Time    `json:"created_at"`
	RetiredAt sql.NullTime `json:"retired_at"`
}

// JWT signing keys for rotation with overlap.
//
// Table schema lives in migrations/sqlite/004_jwt_signing_keys.sql.
// The repository (signing_key_repository.go) is a thin adapter around
// these queries. Rotation/overlap policy lives in internal/auth/keystore.go.
func (q *Queries) CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error {
	_, err := q.db.ExecContext(ctx, createSigningKey,
		arg.ID,
		arg.Secret,
		arg.CreatedAt,
		arg.RetiredAt,
	)
	return err
}

const deleteRetiredSigningKeysBefore = `-- name: DeleteRetiredSigningKeysBefore :execrows
DELETE FROM jwt_signing_keys
WHERE retired_at IS NOT NULL
  AND retired_at < ?
`

func (q *Queries) DeleteRetiredSigningKeysBefore(ctx context.Context, retiredAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetiredSigningKeysBefore, retiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSigningKey = `-- name: GetSigningKey :one
SELECT id, secret, created_at, retired_at
FROM jwt_signing_keys
WHERE id = ?
`

func (q *Queries) GetSigningKey(ctx context.Context, id string) (JwtSigningKey, error) {
	row := q.db.QueryRowContext(ctx, getSigningKey, id)
	var i JwtSigningKey
	err := row.Scan(
		&i.ID,
		&i.Secret,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const listActiveSigningKeys = `-- name: ListActiveSigningKeys :many
SELECT id, secret, created_at, retired_at
FROM jwt_signing_keys
WHERE retired_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSigningKeys(ctx context.Context) ([]JwtSigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JwtSigningKey{}
	for rows.Next() {
		var i JwtSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.Secret,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigningKeys = `-- name: ListSigningKeys :many
SELECT id, secret, created_at, retired_at
FROM jwt_signing_keys
ORDER BY created_at DESC
`

func (q *Queries) ListSigningKeys(ctx context.Context) ([]JwtSigningKey, error) {
	rows, err := q.db.QueryContext(ctx, listSigningKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JwtSigningKey{}
	for rows.Next() {
		var i JwtSigningKey
		if err := rows.Scan(
			&i.ID,
			&i.Secret,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSigningKeyRetiredAt = `-- name: SetSigningKeyRetiredAt :execrows
UPDATE jwt_signing_keys
SET retired_at = ?
WHERE id = ?
`

type SetSigningKeyRetiredAtParams struct {
	RetiredAt sql.NullTime `json:"retired_at"`
	ID        string       `json:"id"`
}

func (q *Queries) SetSigningKeyRetiredAt(ctx context.Context, arg SetSigningKeyRetiredAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSigningKeyRetiredAt, arg.RetiredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
