// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: studios.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getStudioBySlug = `-- name: GetStudioBySlug :one

SELECT id, tmdb_id, name, slug, logo_url, created_at
FROM studios
WHERE slug = ?
`

// Studios (production companies + TV networks).
//
// Schema: migrations/sqlite/032_studios.sql.
// The slug is URL-safe; ListItemsForStudio is intentionally raw SQL
// (lives in studio_repository.go) because the trailing ORDER BY hits
// the sqlc v1.31.1 parser truncation we already work around for
// ListGenres + GetItemIDByExternalID.
func (q *Queries) GetStudioBySlug(ctx context.Context, slug string) (Studio, error) {
	row := q.db.QueryRowContext(ctx, getStudioBySlug, slug)
	var i Studio
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getStudioByTMDBID = `-- name: GetStudioByTMDBID :one
SELECT id, tmdb_id, name, slug, logo_url, created_at
FROM studios
WHERE tmdb_id = ?
`

func (q *Queries) GetStudioByTMDBID(ctx context.Context, tmdbID sql.NullInt64) (Studio, error) {
	row := q.db.QueryRowContext(ctx, getStudioByTMDBID, tmdbID)
	var i Studio
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listStudios = `-- name: ListStudios :many
SELECT
    s.id,
    s.name,
    s.slug,
    s.logo_url,
    (SELECT COUNT(*) FROM metadata m WHERE m.studio_id = s.id) AS item_count
FROM studios s
WHERE EXISTS (SELECT 1 FROM metadata m WHERE m.studio_id = s.id)
ORDER BY item_count DESC, s.name ASC
`

type ListStudiosRow struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	LogoUrl   string `json:"logo_url"`
	ItemCount int64  `json:"item_count"`
}

// Browse-page listing: every studio that has at least one item linked
// to it, ordered by item count desc. The COUNT subquery is fine
// (one studio thousand-items at most) and keeps the index touched
// to (studio_id) which we already created in 032_studios.sql.
func (q *Queries) ListStudios(ctx context.Context) ([]ListStudiosRow, error) {
	rows, err := q.db.QueryContext(ctx, listStudios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudiosRow{}
	for rows.Next() {
		var i ListStudiosRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStudio = `-- name: UpsertStudio :exec
INSERT INTO studios (id, tmdb_id, name, slug, logo_url)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(tmdb_id) DO UPDATE SET
    logo_url = excluded.logo_url
WHERE excluded.logo_url <> ''
`

type UpsertStudioParams struct {
	ID      string        `json:"id"`
	TmdbID  sql.NullInt64 `json:"tmdb_id"`
	Name    string        `json:"name"`
	Slug    string        `json:"slug"`
	LogoUrl string        `json:"logo_url"`
}

// The scanner calls this every time it processes a movie/series with
// a TMDb production company match. Conflict on tmdb_id keeps a single
// row per upstream studio even when the slug recipe would diverge
// (e.g. "Lucasfilm" vs "Lucasfilm Ltd."); conflict on slug catches
// the rare case of a studio with no tmdb_id (legacy backfill rows).
// We refresh the logo_url on conflict so a re-scan with a richer
// TMDb response upgrades the brand mark, but we keep `name` and
// `slug` stable so the URL stays valid even if TMDb renames.
func (q *Queries) UpsertStudio(ctx context.Context, arg UpsertStudioParams) error {
	_, err := q.db.ExecContext(ctx, upsertStudio,
		arg.ID,
		arg.TmdbID,
		arg.Name,
		arg.Slug,
		arg.LogoUrl,
	)
	return err
}

const upsertStudioBySlug = `-- name: UpsertStudioBySlug :exec
INSERT INTO studios (id, tmdb_id, name, slug, logo_url)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    logo_url = excluded.logo_url
WHERE excluded.logo_url <> ''
`

type UpsertStudioBySlugParams struct {
	ID      string        `json:"id"`
	TmdbID  sql.NullInt64 `json:"tmdb_id"`
	Name    string        `json:"name"`
	Slug    string        `json:"slug"`
	LogoUrl string        `json:"logo_url"`
}

// Fallback when the scanner has no tmdb_id (legacy items, providers
// other than TMDb). The slug is the dedupe key.
func (q *Queries) UpsertStudioBySlug(ctx context.Context, arg UpsertStudioBySlugParams) error {
	_, err := q.db.ExecContext(ctx, upsertStudioBySlug,
		arg.ID,
		arg.TmdbID,
		arg.Name,
		arg.Slug,
		arg.LogoUrl,
	)
	return err
}
