// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS cnt FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, display_name, password_hash, role, created_at,
                   parent_user_id, password_change_required)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID                     string         `json:"id"`
	Username               string         `json:"username"`
	DisplayName            string         `json:"display_name"`
	PasswordHash           string         `json:"password_hash"`
	Role                   string         `json:"role"`
	CreatedAt              time.Time      `json:"created_at"`
	ParentUserID           sql.NullString `json:"parent_user_id"`
	PasswordChangeRequired bool           `json:"password_change_required"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
		arg.ParentUserID,
		arg.PasswordChangeRequired,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPrimaryAdminID = `-- name: GetPrimaryAdminID :one
SELECT id FROM users
WHERE role = 'admin' AND parent_user_id IS NULL
ORDER BY created_at ASC
LIMIT 1
`

// Returns the user_id of the oldest admin row. The primary admin
// is identified positionally, not by an explicit flag, so a fresh
// DB starts with the setup-wizard user as primary automatically.
// Empty result when no admin exists yet (cold-start install).
func (q *Queries) GetPrimaryAdminID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPrimaryAdminID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, username, display_name, password_hash, COALESCE(avatar_path, '') AS avatar_path,
       role, is_active, max_sessions, created_at, last_login_at,
       parent_user_id, pin_hash, max_content_rating, password_change_required,
       access_expires_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID                     string         `json:"id"`
	Username               string         `json:"username"`
	DisplayName            string         `json:"display_name"`
	PasswordHash           string         `json:"password_hash"`
	AvatarPath             string         `json:"avatar_path"`
	Role                   string         `json:"role"`
	IsActive               bool           `json:"is_active"`
	MaxSessions            int64          `json:"max_sessions"`
	CreatedAt              time.Time      `json:"created_at"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	ParentUserID           sql.NullString `json:"parent_user_id"`
	PinHash                sql.NullString `json:"pin_hash"`
	MaxContentRating       sql.NullString `json:"max_content_rating"`
	PasswordChangeRequired bool           `json:"password_change_required"`
	AccessExpiresAt        sql.NullTime   `json:"access_expires_at"`
}

// User accounts.
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE users)
// + migrations/sqlite/034_user_profiles.sql (parent_user_id, pin_hash,
// max_content_rating, password_change_required).
func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarPath,
		&i.Role,
		&i.IsActive,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.ParentUserID,
		&i.PinHash,
		&i.MaxContentRating,
		&i.PasswordChangeRequired,
		&i.AccessExpiresAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, COALESCE(avatar_path, '') AS avatar_path,
       role, is_active, max_sessions, created_at, last_login_at,
       parent_user_id, pin_hash, max_content_rating, password_change_required,
       access_expires_at
FROM users
WHERE username = ?
`

type GetUserByUsernameRow struct {
	ID                     string         `json:"id"`
	Username               string         `json:"username"`
	DisplayName            string         `json:"display_name"`
	PasswordHash           string         `json:"password_hash"`
	AvatarPath             string         `json:"avatar_path"`
	Role                   string         `json:"role"`
	IsActive               bool           `json:"is_active"`
	MaxSessions            int64          `json:"max_sessions"`
	CreatedAt              time.Time      `json:"created_at"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	ParentUserID           sql.NullString `json:"parent_user_id"`
	PinHash                sql.NullString `json:"pin_hash"`
	MaxContentRating       sql.NullString `json:"max_content_rating"`
	PasswordChangeRequired bool           `json:"password_change_required"`
	AccessExpiresAt        sql.NullTime   `json:"access_expires_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarPath,
		&i.Role,
		&i.IsActive,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.ParentUserID,
		&i.PinHash,
		&i.MaxContentRating,
		&i.PasswordChangeRequired,
		&i.AccessExpiresAt,
	)
	return i, err
}

const listProfilesForOwner = `-- name: ListProfilesForOwner :many
SELECT id, username, display_name, COALESCE(avatar_path, '') AS avatar_path,
       role, is_active, created_at, last_login_at,
       parent_user_id, pin_hash, max_content_rating, password_change_required,
       access_expires_at
FROM users
WHERE id = ? OR parent_user_id = ?
ORDER BY parent_user_id IS NOT NULL, display_name COLLATE NOCASE
`

type ListProfilesForOwnerParams struct {
	ID           string         `json:"id"`
	ParentUserID sql.NullString `json:"parent_user_id"`
}

type ListProfilesForOwnerRow struct {
	ID                     string         `json:"id"`
	Username               string         `json:"username"`
	DisplayName            string         `json:"display_name"`
	AvatarPath             string         `json:"avatar_path"`
	Role                   string         `json:"role"`
	IsActive               bool           `json:"is_active"`
	CreatedAt              time.Time      `json:"created_at"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	ParentUserID           sql.NullString `json:"parent_user_id"`
	PinHash                sql.NullString `json:"pin_hash"`
	MaxContentRating       sql.NullString `json:"max_content_rating"`
	PasswordChangeRequired bool           `json:"password_change_required"`
	AccessExpiresAt        sql.NullTime   `json:"access_expires_at"`
}

// Returns the parent account row plus every profile that hangs off
// it, ordered by the parent first, then profiles alphabetically.
// Drives both the post-login "Who's watching?" payload and the admin
// profile list under a user. The username column is unique, so
// profiles synthesise theirs as "<parent.username>:<display_name>"
// via the handler — we don't expose them for login anyway.
// ASC is redundant for collation but works around a sqlc 1.31.x
// bug that truncates `COLLATE NOCASE;` (with the trailing semicolon
// directly after) to `COLLATE NOCA` in the generated Go string —
// which then errors at runtime ("no such collation sequence: NOCA").
// The other queries in this codebase that use COLLATE happen to
// carry ASC/DESC and render fine. See git history of this file
// for the diagnosis.
func (q *Queries) ListProfilesForOwner(ctx context.Context, arg ListProfilesForOwnerParams) ([]ListProfilesForOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listProfilesForOwner, arg.ID, arg.ParentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilesForOwnerRow{}
	for rows.Next() {
		var i ListProfilesForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarPath,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.ParentUserID,
			&i.PinHash,
			&i.MaxContentRating,
			&i.PasswordChangeRequired,
			&i.AccessExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, COALESCE(avatar_path, '') AS avatar_path,
       role, is_active, created_at, last_login_at,
       parent_user_id, pin_hash, max_content_rating, password_change_required,
       access_expires_at
FROM users
ORDER BY username
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListUsersRow struct {
	ID                     string         `json:"id"`
	Username               string         `json:"username"`
	DisplayName            string         `json:"display_name"`
	AvatarPath             string         `json:"avatar_path"`
	Role                   string         `json:"role"`
	IsActive               bool           `json:"is_active"`
	CreatedAt              time.Time      `json:"created_at"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	ParentUserID           sql.NullString `json:"parent_user_id"`
	PinHash                sql.NullString `json:"pin_hash"`
	MaxContentRating       sql.NullString `json:"max_content_rating"`
	PasswordChangeRequired bool           `json:"password_change_required"`
	AccessExpiresAt        sql.NullTime   `json:"access_expires_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarPath,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.ParentUserID,
			&i.PinHash,
			&i.MaxContentRating,
			&i.PasswordChangeRequired,
			&i.AccessExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = ? WHERE id = ?
`

type UpdateLastLoginParams struct {
	LastLoginAt sql.NullTime `json:"last_login_at"`
	ID          string       `json:"id"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET display_name = ?, role = ?, is_active = ? WHERE id = ?
`

type UpdateUserParams struct {
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	IsActive    bool   `json:"is_active"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.DisplayName,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateUserAccessExpiresAt = `-- name: UpdateUserAccessExpiresAt :exec
UPDATE users SET access_expires_at = ? WHERE id = ?
`

type UpdateUserAccessExpiresAtParams struct {
	AccessExpiresAt sql.NullTime `json:"access_expires_at"`
	ID              string       `json:"id"`
}

// NULL = no expiry (permanent). Non-null = JWT middleware + login
// reject after this timestamp. Lazy: no background job needed.
func (q *Queries) UpdateUserAccessExpiresAt(ctx context.Context, arg UpdateUserAccessExpiresAtParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAccessExpiresAt, arg.AccessExpiresAt, arg.ID)
	return err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users SET is_active = ? WHERE id = ?
`

type UpdateUserActiveParams struct {
	IsActive bool   `json:"is_active"`
	ID       string `json:"id"`
}

// Soft-disable a user without deleting. Login rejects on
// is_active=false; the row + every per-user table stays intact so
// re-enabling is a one-flag flip.
func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateUserActive, arg.IsActive, arg.ID)
	return err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET display_name = ? WHERE id = ?
`

type UpdateUserDisplayNameParams struct {
	DisplayName string `json:"display_name"`
	ID          string `json:"id"`
}

// Per-field update so callers (renaming a profile, an admin
// relabelling a user) don't need to round-trip the rest of the
// mutable surface.
func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.DisplayName, arg.ID)
	return err
}

const updateUserMaxContentRating = `-- name: UpdateUserMaxContentRating :exec
UPDATE users SET max_content_rating = ? WHERE id = ?
`

type UpdateUserMaxContentRatingParams struct {
	MaxContentRating sql.NullString `json:"max_content_rating"`
	ID               string         `json:"id"`
}

// max_content_rating NULL means "no restriction". Empty string is
// normalised to NULL by the handler so callers don't have to choose.
func (q *Queries) UpdateUserMaxContentRating(ctx context.Context, arg UpdateUserMaxContentRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateUserMaxContentRating, arg.MaxContentRating, arg.ID)
	return err
}

const updateUserPIN = `-- name: UpdateUserPIN :exec
UPDATE users SET pin_hash = ? WHERE id = ?
`

type UpdateUserPINParams struct {
	PinHash sql.NullString `json:"pin_hash"`
	ID      string         `json:"id"`
}

// pin_hash NULL clears the PIN; non-null sets it. The handler always
// bcrypt-hashes the value before reaching the repo.
func (q *Queries) UpdateUserPIN(ctx context.Context, arg UpdateUserPINParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPIN, arg.PinHash, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, password_change_required = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash           string `json:"password_hash"`
	PasswordChangeRequired bool   `json:"password_change_required"`
	ID                     string `json:"id"`
}

// Used by both the admin reset-password endpoint and the user's own
// change-password flow. Resetting must clear the must-change flag so
// the user isn't bounced back to the change screen forever; setting
// a fresh password from the admin path SETs it so the new password
// triggers a forced change on first login.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.PasswordChangeRequired, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   string `json:"id"`
}

// Promote / demote between user and admin. Caller-side gate keeps
// the primary admin (oldest role=admin row) immutable.
func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
