// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS cnt FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, display_name, password_hash, role, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, username, display_name, password_hash, COALESCE(avatar_path, '') AS avatar_path,
       role, is_active, max_sessions, created_at, last_login_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID           string       `json:"id"`
	Username     string       `json:"username"`
	DisplayName  string       `json:"display_name"`
	PasswordHash string       `json:"password_hash"`
	AvatarPath   string       `json:"avatar_path"`
	Role         string       `json:"role"`
	IsActive     bool         `json:"is_active"`
	MaxSessions  int64        `json:"max_sessions"`
	CreatedAt    time.Time    `json:"created_at"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
}

// User accounts.
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE users).
func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarPath,
		&i.Role,
		&i.IsActive,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, COALESCE(avatar_path, '') AS avatar_path,
       role, is_active, max_sessions, created_at, last_login_at
FROM users
WHERE username = ?
`

type GetUserByUsernameRow struct {
	ID           string       `json:"id"`
	Username     string       `json:"username"`
	DisplayName  string       `json:"display_name"`
	PasswordHash string       `json:"password_hash"`
	AvatarPath   string       `json:"avatar_path"`
	Role         string       `json:"role"`
	IsActive     bool         `json:"is_active"`
	MaxSessions  int64        `json:"max_sessions"`
	CreatedAt    time.Time    `json:"created_at"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarPath,
		&i.Role,
		&i.IsActive,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, COALESCE(avatar_path, '') AS avatar_path,
       role, is_active, created_at, last_login_at
FROM users
ORDER BY username
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListUsersRow struct {
	ID          string       `json:"id"`
	Username    string       `json:"username"`
	DisplayName string       `json:"display_name"`
	AvatarPath  string       `json:"avatar_path"`
	Role        string       `json:"role"`
	IsActive    bool         `json:"is_active"`
	CreatedAt   time.Time    `json:"created_at"`
	LastLoginAt sql.NullTime `json:"last_login_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarPath,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = ? WHERE id = ?
`

type UpdateLastLoginParams struct {
	LastLoginAt sql.NullTime `json:"last_login_at"`
	ID          string       `json:"id"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, updateLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET display_name = ?, role = ?, is_active = ? WHERE id = ?
`

type UpdateUserParams struct {
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	IsActive    bool   `json:"is_active"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.DisplayName,
		arg.Role,
		arg.IsActive,
		arg.ID,
	)
	return err
}
