// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_data.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const continueWatching = `-- name: ContinueWatching :many
SELECT ud.item_id, ud.position_ticks, ud.last_played_at,
       i.title, i.type, i.duration_ticks, COALESCE(i.parent_id, '') AS parent_id,
       COALESCE(i.container, '') AS container
FROM user_data ud
JOIN items i ON i.id = ud.item_id
WHERE ud.user_id = ? AND ud.completed = 0 AND ud.position_ticks > 0
  AND i.is_available = 1
ORDER BY ud.last_played_at DESC
LIMIT ?
`

type ContinueWatchingParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
}

type ContinueWatchingRow struct {
	ItemID        string        `json:"item_id"`
	PositionTicks sql.NullInt64 `json:"position_ticks"`
	LastPlayedAt  sql.NullTime  `json:"last_played_at"`
	Title         string        `json:"title"`
	Type          string        `json:"type"`
	DurationTicks sql.NullInt64 `json:"duration_ticks"`
	ParentID      string        `json:"parent_id"`
	Container     string        `json:"container"`
}

func (q *Queries) ContinueWatching(ctx context.Context, arg ContinueWatchingParams) ([]ContinueWatchingRow, error) {
	rows, err := q.db.QueryContext(ctx, continueWatching, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContinueWatchingRow{}
	for rows.Next() {
		var i ContinueWatchingRow
		if err := rows.Scan(
			&i.ItemID,
			&i.PositionTicks,
			&i.LastPlayedAt,
			&i.Title,
			&i.Type,
			&i.DurationTicks,
			&i.ParentID,
			&i.Container,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserData = `-- name: DeleteUserData :exec
DELETE FROM user_data WHERE user_id = ? AND item_id = ?
`

type DeleteUserDataParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) DeleteUserData(ctx context.Context, arg DeleteUserDataParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserData, arg.UserID, arg.ItemID)
	return err
}

const getUserData = `-- name: GetUserData :one
SELECT user_id, item_id, position_ticks, play_count, completed,
       is_favorite, liked, audio_stream_index, subtitle_stream_index,
       last_played_at, updated_at
FROM user_data
WHERE user_id = ? AND item_id = ?
`

type GetUserDataParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) GetUserData(ctx context.Context, arg GetUserDataParams) (UserDatum, error) {
	row := q.db.QueryRowContext(ctx, getUserData, arg.UserID, arg.ItemID)
	var i UserDatum
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.PositionTicks,
		&i.PlayCount,
		&i.Completed,
		&i.IsFavorite,
		&i.Liked,
		&i.AudioStreamIndex,
		&i.SubtitleStreamIndex,
		&i.LastPlayedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT ud.item_id, ud.updated_at,
       i.title, i.type, i.year, i.duration_ticks
FROM user_data ud
JOIN items i ON i.id = ud.item_id
WHERE ud.user_id = ? AND ud.is_favorite = 1
  AND i.is_available = 1
ORDER BY ud.updated_at DESC
LIMIT ? OFFSET ?
`

type ListFavoritesParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListFavoritesRow struct {
	ItemID        string        `json:"item_id"`
	UpdatedAt     time.Time     `json:"updated_at"`
	Title         string        `json:"title"`
	Type          string        `json:"type"`
	Year          sql.NullInt64 `json:"year"`
	DurationTicks sql.NullInt64 `json:"duration_ticks"`
}

func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavorites, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritesRow{}
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.UpdatedAt,
			&i.Title,
			&i.Type,
			&i.Year,
			&i.DurationTicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlayed = `-- name: MarkPlayed :exec
INSERT INTO user_data (user_id, item_id, play_count, completed, last_played_at, updated_at)
VALUES (?, ?, 1, 1, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    play_count = user_data.play_count + 1,
    completed = 1,
    position_ticks = 0,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type MarkPlayedParams struct {
	UserID       string       `json:"user_id"`
	ItemID       string       `json:"item_id"`
	LastPlayedAt sql.NullTime `json:"last_played_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

func (q *Queries) MarkPlayed(ctx context.Context, arg MarkPlayedParams) error {
	_, err := q.db.ExecContext(ctx, markPlayed,
		arg.UserID,
		arg.ItemID,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const setFavorite = `-- name: SetFavorite :exec
INSERT INTO user_data (user_id, item_id, is_favorite, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    is_favorite = excluded.is_favorite,
    updated_at = excluded.updated_at
`

type SetFavoriteParams struct {
	UserID     string       `json:"user_id"`
	ItemID     string       `json:"item_id"`
	IsFavorite sql.NullBool `json:"is_favorite"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, setFavorite,
		arg.UserID,
		arg.ItemID,
		arg.IsFavorite,
		arg.UpdatedAt,
	)
	return err
}

const updateProgress = `-- name: UpdateProgress :exec
INSERT INTO user_data (user_id, item_id, position_ticks, completed, last_played_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    position_ticks = excluded.position_ticks,
    completed = excluded.completed,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type UpdateProgressParams struct {
	UserID        string        `json:"user_id"`
	ItemID        string        `json:"item_id"`
	PositionTicks sql.NullInt64 `json:"position_ticks"`
	Completed     sql.NullBool  `json:"completed"`
	LastPlayedAt  sql.NullTime  `json:"last_played_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateProgress,
		arg.UserID,
		arg.ItemID,
		arg.PositionTicks,
		arg.Completed,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserData = `-- name: UpsertUserData :exec

INSERT INTO user_data (user_id, item_id, position_ticks, play_count, completed,
    is_favorite, liked, audio_stream_index, subtitle_stream_index, last_played_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    position_ticks = excluded.position_ticks,
    play_count = excluded.play_count,
    completed = excluded.completed,
    is_favorite = excluded.is_favorite,
    liked = excluded.liked,
    audio_stream_index = excluded.audio_stream_index,
    subtitle_stream_index = excluded.subtitle_stream_index,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type UpsertUserDataParams struct {
	UserID              string        `json:"user_id"`
	ItemID              string        `json:"item_id"`
	PositionTicks       sql.NullInt64 `json:"position_ticks"`
	PlayCount           sql.NullInt64 `json:"play_count"`
	Completed           sql.NullBool  `json:"completed"`
	IsFavorite          sql.NullBool  `json:"is_favorite"`
	Liked               sql.NullBool  `json:"liked"`
	AudioStreamIndex    sql.NullInt64 `json:"audio_stream_index"`
	SubtitleStreamIndex sql.NullInt64 `json:"subtitle_stream_index"`
	LastPlayedAt        sql.NullTime  `json:"last_played_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

// Per-user per-item interaction data (progress, favorites, play history).
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE user_data).
// PK: (user_id, item_id).
func (q *Queries) UpsertUserData(ctx context.Context, arg UpsertUserDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserData,
		arg.UserID,
		arg.ItemID,
		arg.PositionTicks,
		arg.PlayCount,
		arg.Completed,
		arg.IsFavorite,
		arg.Liked,
		arg.AudioStreamIndex,
		arg.SubtitleStreamIndex,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}
