// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_data.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const continueWatching = `-- name: ContinueWatching :many
SELECT ud.item_id, ud.position_ticks, ud.last_played_at,
       i.title, i.type, i.duration_ticks, COALESCE(i.parent_id, '') AS parent_id,
       COALESCE(i.container, '') AS container,
       COALESCE(i.season_number, 0) AS season_number,
       COALESCE(i.episode_number, 0) AS episode_number,
       COALESCE(season.parent_id, '') AS series_id,
       COALESCE(series.title, '') AS series_title
FROM user_data ud
JOIN items i ON i.id = ud.item_id
LEFT JOIN items season ON season.id = i.parent_id
LEFT JOIN items series ON series.id = season.parent_id
WHERE ud.user_id = ? AND ud.completed = 0 AND ud.position_ticks > 0
  AND i.is_available = 1
  AND NOT (
    i.duration_ticks > 0
    AND ud.position_ticks * 100 >= i.duration_ticks * 90
  )
  AND ud.last_played_at IS NOT NULL
  AND (
    ud.last_played_at >= ?  -- abandoned threshold (sqlc auto-names it LastPlayedAt)
    OR i.duration_ticks = 0
    OR ud.position_ticks * 2 >= i.duration_ticks
  )
ORDER BY ud.last_played_at DESC
LIMIT ?
`

type ContinueWatchingParams struct {
	UserID       string       `json:"user_id"`
	LastPlayedAt sql.NullTime `json:"last_played_at"`
	Limit        int64        `json:"limit"`
}

type ContinueWatchingRow struct {
	ItemID        string        `json:"item_id"`
	PositionTicks sql.NullInt64 `json:"position_ticks"`
	LastPlayedAt  sql.NullTime  `json:"last_played_at"`
	Title         string        `json:"title"`
	Type          string        `json:"type"`
	DurationTicks sql.NullInt64 `json:"duration_ticks"`
	ParentID      string        `json:"parent_id"`
	Container     string        `json:"container"`
	SeasonNumber  int64         `json:"season_number"`
	EpisodeNumber int64         `json:"episode_number"`
	SeriesID      string        `json:"series_id"`
	SeriesTitle   string        `json:"series_title"`
}

// Two extra filters vs. the obvious "started but not completed" rail:
//  1. Near-complete drop: position >= 90% of duration. Treat as
//     effectively done -- the user almost certainly finished and the
//     rail showing it as in-progress is noise.
//  2. Abandoned drop: last_played_at older than the caller-supplied
//     threshold AND position < 50%. The user moved on; the rail
//     should not keep nagging about the same start-of-S1E1 forever.
//
// Both checks are integer-safe (ticks * 100 / 90 and ticks * 2 / 1)
// and both require a known duration; rows with duration_ticks = 0
// are kept (we can't reason about progress without it).
//
// The abandoned filter is expressed positively (DeMorgan equivalent of
// the obvious NOT (...) form) to dodge a sqlc parser bug where ?
// placeholders nested inside NOT (...) clauses are silently dropped
// from the generated Params struct. The IS NOT NULL guard preserves
// the original three-valued-logic behaviour where a NULL last_played_at
// excluded the row -- in practice the position_ticks > 0 above means
// last_played_at is always set; this is belt and braces. See
// docs/memory/conventions.md (Regeneracion sqlc section) for the full
// story. NOTE: keep this comment pure ASCII -- multi-byte chars
// (em-dashes, accents, backticks) trigger another parser bug that
// silently truncates queries below.
func (q *Queries) ContinueWatching(ctx context.Context, arg ContinueWatchingParams) ([]ContinueWatchingRow, error) {
	rows, err := q.db.QueryContext(ctx, continueWatching, arg.UserID, arg.LastPlayedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContinueWatchingRow{}
	for rows.Next() {
		var i ContinueWatchingRow
		if err := rows.Scan(
			&i.ItemID,
			&i.PositionTicks,
			&i.LastPlayedAt,
			&i.Title,
			&i.Type,
			&i.DurationTicks,
			&i.ParentID,
			&i.Container,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.SeriesID,
			&i.SeriesTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserData = `-- name: DeleteUserData :exec
DELETE FROM user_data WHERE user_id = ? AND item_id = ?
`

type DeleteUserDataParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) DeleteUserData(ctx context.Context, arg DeleteUserDataParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserData, arg.UserID, arg.ItemID)
	return err
}

const getUserData = `-- name: GetUserData :one
SELECT user_id, item_id, position_ticks, play_count, completed,
       is_favorite, liked, audio_stream_index, subtitle_stream_index,
       last_played_at, updated_at
FROM user_data
WHERE user_id = ? AND item_id = ?
`

type GetUserDataParams struct {
	UserID string `json:"user_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) GetUserData(ctx context.Context, arg GetUserDataParams) (UserDatum, error) {
	row := q.db.QueryRowContext(ctx, getUserData, arg.UserID, arg.ItemID)
	var i UserDatum
	err := row.Scan(
		&i.UserID,
		&i.ItemID,
		&i.PositionTicks,
		&i.PlayCount,
		&i.Completed,
		&i.IsFavorite,
		&i.Liked,
		&i.AudioStreamIndex,
		&i.SubtitleStreamIndex,
		&i.LastPlayedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT ud.item_id, ud.updated_at,
       i.title, i.type, i.year, i.duration_ticks
FROM user_data ud
JOIN items i ON i.id = ud.item_id
WHERE ud.user_id = ? AND ud.is_favorite = 1
  AND i.is_available = 1
ORDER BY ud.updated_at DESC
LIMIT ? OFFSET ?
`

type ListFavoritesParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

type ListFavoritesRow struct {
	ItemID        string        `json:"item_id"`
	UpdatedAt     time.Time     `json:"updated_at"`
	Title         string        `json:"title"`
	Type          string        `json:"type"`
	Year          sql.NullInt64 `json:"year"`
	DurationTicks sql.NullInt64 `json:"duration_ticks"`
}

func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavorites, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritesRow{}
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.ItemID,
			&i.UpdatedAt,
			&i.Title,
			&i.Type,
			&i.Year,
			&i.DurationTicks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlayed = `-- name: MarkPlayed :exec
INSERT INTO user_data (user_id, item_id, play_count, completed, last_played_at, updated_at)
VALUES (?, ?, 1, 1, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    play_count = user_data.play_count + 1,
    completed = 1,
    position_ticks = 0,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type MarkPlayedParams struct {
	UserID       string       `json:"user_id"`
	ItemID       string       `json:"item_id"`
	LastPlayedAt sql.NullTime `json:"last_played_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

func (q *Queries) MarkPlayed(ctx context.Context, arg MarkPlayedParams) error {
	_, err := q.db.ExecContext(ctx, markPlayed,
		arg.UserID,
		arg.ItemID,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const seriesEpisodeProgress = `-- name: SeriesEpisodeProgress :one
SELECT
    COUNT(e.id) AS total_episodes,
    COUNT(CASE WHEN ud.completed = 1 THEN 1 END) AS watched_episodes
FROM items s
JOIN items e ON e.parent_id = s.id AND e.type = 'episode'
LEFT JOIN user_data ud ON ud.user_id = ? AND ud.item_id = e.id
WHERE s.parent_id = ? AND s.type = 'season'
`

type SeriesEpisodeProgressParams struct {
	UserID   string         `json:"user_id"`
	ParentID sql.NullString `json:"parent_id"`
}

type SeriesEpisodeProgressRow struct {
	TotalEpisodes   int64 `json:"total_episodes"`
	WatchedEpisodes int64 `json:"watched_episodes"`
}

// Aggregate "X of Y episodes watched" for a single series.
// The grid is series -> seasons -> episodes via parent_id; LEFT JOIN
// on user_data so episodes the user has never touched count as
// unwatched without forcing an INNER row to exist. Both columns come
// back as plain integers; SQLite COUNT() is well-typed for sqlc.
func (q *Queries) SeriesEpisodeProgress(ctx context.Context, arg SeriesEpisodeProgressParams) (SeriesEpisodeProgressRow, error) {
	row := q.db.QueryRowContext(ctx, seriesEpisodeProgress, arg.UserID, arg.ParentID)
	var i SeriesEpisodeProgressRow
	err := row.Scan(&i.TotalEpisodes, &i.WatchedEpisodes)
	return i, err
}

const setFavorite = `-- name: SetFavorite :exec
INSERT INTO user_data (user_id, item_id, is_favorite, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    is_favorite = excluded.is_favorite,
    updated_at = excluded.updated_at
`

type SetFavoriteParams struct {
	UserID     string       `json:"user_id"`
	ItemID     string       `json:"item_id"`
	IsFavorite sql.NullBool `json:"is_favorite"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

func (q *Queries) SetFavorite(ctx context.Context, arg SetFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, setFavorite,
		arg.UserID,
		arg.ItemID,
		arg.IsFavorite,
		arg.UpdatedAt,
	)
	return err
}

const updateProgress = `-- name: UpdateProgress :exec
INSERT INTO user_data (user_id, item_id, position_ticks, completed, last_played_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    position_ticks = excluded.position_ticks,
    completed = excluded.completed,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type UpdateProgressParams struct {
	UserID        string        `json:"user_id"`
	ItemID        string        `json:"item_id"`
	PositionTicks sql.NullInt64 `json:"position_ticks"`
	Completed     sql.NullBool  `json:"completed"`
	LastPlayedAt  sql.NullTime  `json:"last_played_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateProgress,
		arg.UserID,
		arg.ItemID,
		arg.PositionTicks,
		arg.Completed,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserData = `-- name: UpsertUserData :exec

INSERT INTO user_data (user_id, item_id, position_ticks, play_count, completed,
    is_favorite, liked, audio_stream_index, subtitle_stream_index, last_played_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, item_id) DO UPDATE SET
    position_ticks = excluded.position_ticks,
    play_count = excluded.play_count,
    completed = excluded.completed,
    is_favorite = excluded.is_favorite,
    liked = excluded.liked,
    audio_stream_index = excluded.audio_stream_index,
    subtitle_stream_index = excluded.subtitle_stream_index,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type UpsertUserDataParams struct {
	UserID              string        `json:"user_id"`
	ItemID              string        `json:"item_id"`
	PositionTicks       sql.NullInt64 `json:"position_ticks"`
	PlayCount           sql.NullInt64 `json:"play_count"`
	Completed           sql.NullBool  `json:"completed"`
	IsFavorite          sql.NullBool  `json:"is_favorite"`
	Liked               sql.NullBool  `json:"liked"`
	AudioStreamIndex    sql.NullInt64 `json:"audio_stream_index"`
	SubtitleStreamIndex sql.NullInt64 `json:"subtitle_stream_index"`
	LastPlayedAt        sql.NullTime  `json:"last_played_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

// Per-user per-item interaction data (progress, favorites, play history).
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE user_data).
// PK: (user_id, item_id).
func (q *Queries) UpsertUserData(ctx context.Context, arg UpsertUserDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserData,
		arg.UserID,
		arg.ItemID,
		arg.PositionTicks,
		arg.PlayCount,
		arg.Completed,
		arg.IsFavorite,
		arg.Liked,
		arg.AudioStreamIndex,
		arg.SubtitleStreamIndex,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}
