-- +goose Up
-- Federation: server identity + peer registry + invite codes.
--
-- This is the foundation for HubPlay-to-HubPlay federation (peering with
-- another self-hosted HubPlay so users on either side can browse / play
-- each other's content with admin-controlled scopes). Three tables are
-- introduced here; later phases add library_shares, audit_log,
-- remote_users, federation_progress, and rate-limit-state.
--
-- Design notes:
--
--   server_identity   — exactly one row, enforced by CHECK(id = 1). Holds
--                       this server's Ed25519 keypair and stable UUID.
--                       Generated on first boot and held forever; key
--                       rotation (Phase 2+) sets rotated_at.
--
--   federation_peers  — peers we've handshaken with. Each row pins the
--                       remote's Ed25519 pubkey, name, and advertised URL.
--                       status transitions: pending → paired → revoked
--                       (terminal). A revoked peer is kept for audit but
--                       its rows in downstream tables (Phase 3+) cascade.
--
--   federation_invites — single-use codes generated by the local admin
--                       and pasted into the remote admin's UI. Expire
--                       after the configured window (default 24h). The
--                       code carries enough entropy that brute-force
--                       guessing during the validity window is impossible.
--
-- Why TEXT for IDs vs INTEGER: matches the rest of the schema (libraries,
-- channels, users — all TEXT UUIDs). Federation peer IDs end up in JWT
-- claims travelling between servers; opaque strings are nicer than
-- monotonically increasing ints which leak peer count via timing.

CREATE TABLE server_identity (
    id          INTEGER PRIMARY KEY CHECK (id = 1),
    server_uuid TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    private_key BLOB NOT NULL,                          -- Ed25519 seed, 32 bytes
    public_key  BLOB NOT NULL,                          -- Ed25519 public key, 32 bytes
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rotated_at  DATETIME                                -- non-null after a rotation
);

CREATE TABLE federation_peers (
    id                    TEXT PRIMARY KEY,
    server_uuid           TEXT NOT NULL UNIQUE,         -- the remote's server_identity.server_uuid
    name                  TEXT NOT NULL,
    base_url              TEXT NOT NULL,                -- e.g. "https://pedro.tailnet.ts.net"
    public_key            BLOB NOT NULL,                -- pinned Ed25519 pubkey, 32 bytes
    status                TEXT NOT NULL DEFAULT 'pending',
    created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paired_at             DATETIME,                     -- set when status flipped to 'paired'
    last_seen_at          DATETIME,
    last_seen_status_code INTEGER,                      -- 200 = healthy on last ping
    revoked_at            DATETIME,
    CHECK (status IN ('pending', 'paired', 'revoked'))
);

-- Hot path: list non-revoked peers for admin UI + outbound calls.
-- Revoked peers stay in the table for audit but never participate in
-- federation flows.
CREATE INDEX idx_fed_peers_status ON federation_peers(status)
    WHERE status != 'revoked';

CREATE TABLE federation_invites (
    id                  TEXT PRIMARY KEY,
    code                TEXT NOT NULL UNIQUE,           -- e.g. "hp-invite-a8f3k2m9x4p1c7e2"
    created_by_user_id  TEXT NOT NULL,                  -- admin who minted the code
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at          DATETIME NOT NULL,
    accepted_by_peer_id TEXT REFERENCES federation_peers(id) ON DELETE SET NULL,
    accepted_at         DATETIME
);

-- Hot path: lookups by code at handshake time. Partial index to keep
-- the active set tight (expired/accepted invites stay for audit but
-- don't pollute the hot index).
CREATE INDEX idx_fed_invites_unused ON federation_invites(code)
    WHERE accepted_at IS NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_fed_invites_unused;
DROP TABLE IF EXISTS federation_invites;
DROP INDEX IF EXISTS idx_fed_peers_status;
DROP TABLE IF EXISTS federation_peers;
DROP TABLE IF EXISTS server_identity;
