-- +goose Up
-- Federation Phase 2: per-request audit log + per-peer rate limit
-- state. See SQLite sibling for full design notes.
--
-- Postgres translation:
--   • INTEGER PRIMARY KEY AUTOINCREMENT → BIGSERIAL PRIMARY KEY
--     (more idiomatic than GENERATED BY DEFAULT AS IDENTITY for an
--     append-only audit-log id).
--   • REAL (token-bucket counter) → DOUBLE PRECISION
--   • DATETIME → TIMESTAMPTZ
--   • INTEGER for bytes_out → BIGINT (a single hot federated stream
--     transfer easily exceeds 2^31 bytes; SQLite is dynamic and
--     coerces, Postgres is strict and would overflow).

CREATE TABLE federation_audit_log (
    id              BIGSERIAL PRIMARY KEY,
    peer_id         TEXT NOT NULL REFERENCES federation_peers(id) ON DELETE CASCADE,
    remote_user_id  TEXT,
    method          TEXT NOT NULL,
    endpoint        TEXT NOT NULL,
    status_code     INTEGER NOT NULL,
    bytes_out       BIGINT NOT NULL DEFAULT 0,
    item_id         TEXT,
    session_id      TEXT,
    error_kind      TEXT,
    duration_ms     INTEGER,
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fed_audit_peer_time ON federation_audit_log(peer_id, occurred_at DESC);
CREATE INDEX idx_fed_audit_endpoint ON federation_audit_log(endpoint, occurred_at DESC);
CREATE INDEX idx_fed_audit_occurred ON federation_audit_log(occurred_at);


CREATE TABLE federation_rate_limit_state (
    peer_id                  TEXT PRIMARY KEY REFERENCES federation_peers(id) ON DELETE CASCADE,
    tokens                   DOUBLE PRECISION NOT NULL,
    last_refill_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    daily_bytes              BIGINT NOT NULL DEFAULT 0,
    daily_window_started_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- +goose Down
DROP INDEX IF EXISTS idx_fed_audit_occurred;
DROP INDEX IF EXISTS idx_fed_audit_endpoint;
DROP INDEX IF EXISTS idx_fed_audit_peer_time;
DROP TABLE IF EXISTS federation_audit_log;
DROP TABLE IF EXISTS federation_rate_limit_state;
