// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episode_segments.sql

package sqlc_pg

import (
	"context"
)

const deleteEpisodeSegmentsByItem = `-- name: DeleteEpisodeSegmentsByItem :exec
DELETE FROM episode_segments WHERE item_id = $1
`

func (q *Queries) DeleteEpisodeSegmentsByItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteEpisodeSegmentsByItem, itemID)
	return err
}

const deleteEpisodeSegmentsByItemAndSource = `-- name: DeleteEpisodeSegmentsByItemAndSource :exec
DELETE FROM episode_segments WHERE item_id = $1 AND source = $2
`

type DeleteEpisodeSegmentsByItemAndSourceParams struct {
	ItemID string `json:"item_id"`
	Source string `json:"source"`
}

func (q *Queries) DeleteEpisodeSegmentsByItemAndSource(ctx context.Context, arg DeleteEpisodeSegmentsByItemAndSourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteEpisodeSegmentsByItemAndSource, arg.ItemID, arg.Source)
	return err
}

const insertEpisodeSegment = `-- name: InsertEpisodeSegment :exec

INSERT INTO episode_segments (item_id, kind, source, start_ticks, end_ticks, confidence, detected_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertEpisodeSegmentParams struct {
	ItemID     string  `json:"item_id"`
	Kind       string  `json:"kind"`
	Source     string  `json:"source"`
	StartTicks int64   `json:"start_ticks"`
	EndTicks   int64   `json:"end_ticks"`
	Confidence float64 `json:"confidence"`
	DetectedAt int64   `json:"detected_at"`
}

// Skip-intro / skip-credits markers per item.
//
// Schema: migrations/sqlite/037_episode_segments.sql.
// PK: (item_id, kind, source). Repository.Replace() wraps DELETE+INSERT
// in a transaction so a re-run of one detector replaces only its own
// rows; segments from other sources stay untouched.
func (q *Queries) InsertEpisodeSegment(ctx context.Context, arg InsertEpisodeSegmentParams) error {
	_, err := q.db.ExecContext(ctx, insertEpisodeSegment,
		arg.ItemID,
		arg.Kind,
		arg.Source,
		arg.StartTicks,
		arg.EndTicks,
		arg.Confidence,
		arg.DetectedAt,
	)
	return err
}

const listEpisodeSegmentsByItem = `-- name: ListEpisodeSegmentsByItem :many
SELECT item_id, kind, source, start_ticks, end_ticks, confidence, detected_at
FROM episode_segments
WHERE item_id = $1
ORDER BY kind, source
`

func (q *Queries) ListEpisodeSegmentsByItem(ctx context.Context, itemID string) ([]EpisodeSegment, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeSegmentsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EpisodeSegment{}
	for rows.Next() {
		var i EpisodeSegment
		if err := rows.Scan(
			&i.ItemID,
			&i.Kind,
			&i.Source,
			&i.StartTicks,
			&i.EndTicks,
			&i.Confidence,
			&i.DetectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
