// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: federation.sql

package sqlc_pg

import (
	"context"
	"database/sql"
	"time"
)

const countAndNewestCachedItems = `-- name: CountAndNewestCachedItems :one
SELECT COUNT(*) AS total, MAX(cached_at) AS newest_cached_at
FROM federation_item_cache
WHERE peer_id = $1 AND library_id = $2
`

type CountAndNewestCachedItemsParams struct {
	PeerID    string `json:"peer_id"`
	LibraryID string `json:"library_id"`
}

type CountAndNewestCachedItemsRow struct {
	Total          int64       `json:"total"`
	NewestCachedAt interface{} `json:"newest_cached_at"`
}

func (q *Queries) CountAndNewestCachedItems(ctx context.Context, arg CountAndNewestCachedItemsParams) (CountAndNewestCachedItemsRow, error) {
	row := q.db.QueryRowContext(ctx, countAndNewestCachedItems, arg.PeerID, arg.LibraryID)
	var i CountAndNewestCachedItemsRow
	err := row.Scan(&i.Total, &i.NewestCachedAt)
	return i, err
}

const countSharedItems = `-- name: CountSharedItems :one
SELECT COUNT(*)
FROM items i
JOIN federation_library_shares s ON s.library_id = i.library_id
WHERE i.library_id = $1 AND s.peer_id = $2 AND s.can_browse
  AND i.parent_id IS NULL
`

type CountSharedItemsParams struct {
	LibraryID string `json:"library_id"`
	PeerID    string `json:"peer_id"`
}

func (q *Queries) CountSharedItems(ctx context.Context, arg CountSharedItemsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSharedItems, arg.LibraryID, arg.PeerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCachedItemsForLibrary = `-- name: DeleteCachedItemsForLibrary :exec

DELETE FROM federation_item_cache
WHERE peer_id = $1 AND library_id = $2
`

type DeleteCachedItemsForLibraryParams struct {
	PeerID    string `json:"peer_id"`
	LibraryID string `json:"library_id"`
}

// ============================================================
// catalog cache (Phase 4 + 027)
// ============================================================
func (q *Queries) DeleteCachedItemsForLibrary(ctx context.Context, arg DeleteCachedItemsForLibraryParams) error {
	_, err := q.db.ExecContext(ctx, deleteCachedItemsForLibrary, arg.PeerID, arg.LibraryID)
	return err
}

const deleteFederationProgress = `-- name: DeleteFederationProgress :exec
DELETE FROM federation_progress
WHERE user_id = $1 AND peer_id = $2 AND remote_item_id = $3
`

type DeleteFederationProgressParams struct {
	UserID       string `json:"user_id"`
	PeerID       string `json:"peer_id"`
	RemoteItemID string `json:"remote_item_id"`
}

func (q *Queries) DeleteFederationProgress(ctx context.Context, arg DeleteFederationProgressParams) error {
	_, err := q.db.ExecContext(ctx, deleteFederationProgress, arg.UserID, arg.PeerID, arg.RemoteItemID)
	return err
}

const deleteLibraryShare = `-- name: DeleteLibraryShare :exec
DELETE FROM federation_library_shares
WHERE peer_id = $1 AND id = $2
`

type DeleteLibraryShareParams struct {
	PeerID string `json:"peer_id"`
	ID     string `json:"id"`
}

func (q *Queries) DeleteLibraryShare(ctx context.Context, arg DeleteLibraryShareParams) error {
	_, err := q.db.ExecContext(ctx, deleteLibraryShare, arg.PeerID, arg.ID)
	return err
}

const getFederationProgress = `-- name: GetFederationProgress :one
SELECT user_id, peer_id, remote_item_id, position_ticks, duration_ticks,
       completed, last_played_at, updated_at
FROM federation_progress
WHERE user_id = $1 AND peer_id = $2 AND remote_item_id = $3
`

type GetFederationProgressParams struct {
	UserID       string `json:"user_id"`
	PeerID       string `json:"peer_id"`
	RemoteItemID string `json:"remote_item_id"`
}

func (q *Queries) GetFederationProgress(ctx context.Context, arg GetFederationProgressParams) (FederationProgress, error) {
	row := q.db.QueryRowContext(ctx, getFederationProgress, arg.UserID, arg.PeerID, arg.RemoteItemID)
	var i FederationProgress
	err := row.Scan(
		&i.UserID,
		&i.PeerID,
		&i.RemoteItemID,
		&i.PositionTicks,
		&i.DurationTicks,
		&i.Completed,
		&i.LastPlayedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, code, created_by_user_id, created_at, expires_at,
       accepted_by_peer_id, accepted_at
FROM federation_invites
WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (FederationInvite, error) {
	row := q.db.QueryRowContext(ctx, getInviteByCode, code)
	var i FederationInvite
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedByPeerID,
		&i.AcceptedAt,
	)
	return i, err
}

const getLibraryShare = `-- name: GetLibraryShare :one
SELECT id, peer_id, library_id, can_browse, can_play,
       can_download, can_livetv, extra_scopes, created_by, created_at
FROM federation_library_shares
WHERE peer_id = $1 AND library_id = $2
`

type GetLibraryShareParams struct {
	PeerID    string `json:"peer_id"`
	LibraryID string `json:"library_id"`
}

func (q *Queries) GetLibraryShare(ctx context.Context, arg GetLibraryShareParams) (FederationLibraryShare, error) {
	row := q.db.QueryRowContext(ctx, getLibraryShare, arg.PeerID, arg.LibraryID)
	var i FederationLibraryShare
	err := row.Scan(
		&i.ID,
		&i.PeerID,
		&i.LibraryID,
		&i.CanBrowse,
		&i.CanPlay,
		&i.CanDownload,
		&i.CanLivetv,
		&i.ExtraScopes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPeerByID = `-- name: GetPeerByID :one
SELECT id, server_uuid, name, base_url, public_key, status,
       created_at, paired_at, last_seen_at, last_seen_status_code, revoked_at
FROM federation_peers
WHERE id = $1
`

func (q *Queries) GetPeerByID(ctx context.Context, id string) (FederationPeer, error) {
	row := q.db.QueryRowContext(ctx, getPeerByID, id)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.ServerUuid,
		&i.Name,
		&i.BaseUrl,
		&i.PublicKey,
		&i.Status,
		&i.CreatedAt,
		&i.PairedAt,
		&i.LastSeenAt,
		&i.LastSeenStatusCode,
		&i.RevokedAt,
	)
	return i, err
}

const getPeerByServerUUID = `-- name: GetPeerByServerUUID :one
SELECT id, server_uuid, name, base_url, public_key, status,
       created_at, paired_at, last_seen_at, last_seen_status_code, revoked_at
FROM federation_peers
WHERE server_uuid = $1
`

func (q *Queries) GetPeerByServerUUID(ctx context.Context, serverUuid string) (FederationPeer, error) {
	row := q.db.QueryRowContext(ctx, getPeerByServerUUID, serverUuid)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.ServerUuid,
		&i.Name,
		&i.BaseUrl,
		&i.PublicKey,
		&i.Status,
		&i.CreatedAt,
		&i.PairedAt,
		&i.LastSeenAt,
		&i.LastSeenStatusCode,
		&i.RevokedAt,
	)
	return i, err
}

const getServerIdentity = `-- name: GetServerIdentity :one


SELECT server_uuid, name, private_key, public_key, created_at, rotated_at
FROM server_identity
WHERE id = 1
`

type GetServerIdentityRow struct {
	ServerUuid string       `json:"server_uuid"`
	Name       string       `json:"name"`
	PrivateKey []byte       `json:"private_key"`
	PublicKey  []byte       `json:"public_key"`
	CreatedAt  time.Time    `json:"created_at"`
	RotatedAt  sql.NullTime `json:"rotated_at"`
}

// Federation: server identity, peers, invites, library shares, audit
// log, item-cache. Schema: migrations/sqlite/020-023, 027.
//
// Adapter wrapping these queries lives in
// internal/db/federation_repository.go and is the public surface the
// federation package consumes.
// ============================================================
// server identity (one row, enforced by CHECK(id=1))
// ============================================================
func (q *Queries) GetServerIdentity(ctx context.Context) (GetServerIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getServerIdentity)
	var i GetServerIdentityRow
	err := row.Scan(
		&i.ServerUuid,
		&i.Name,
		&i.PrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const insertCachedItem = `-- name: InsertCachedItem :exec
INSERT INTO federation_item_cache
    (peer_id, library_id, remote_id, type, title, year, overview, has_poster, cached_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertCachedItemParams struct {
	PeerID    string         `json:"peer_id"`
	LibraryID string         `json:"library_id"`
	RemoteID  string         `json:"remote_id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Year      sql.NullInt32  `json:"year"`
	Overview  sql.NullString `json:"overview"`
	HasPoster bool           `json:"has_poster"`
	CachedAt  time.Time      `json:"cached_at"`
}

func (q *Queries) InsertCachedItem(ctx context.Context, arg InsertCachedItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCachedItem,
		arg.PeerID,
		arg.LibraryID,
		arg.RemoteID,
		arg.Type,
		arg.Title,
		arg.Year,
		arg.Overview,
		arg.HasPoster,
		arg.CachedAt,
	)
	return err
}

const insertFederationAuditEntry = `-- name: InsertFederationAuditEntry :exec

INSERT INTO federation_audit_log
    (peer_id, remote_user_id, method, endpoint, status_code,
     bytes_out, item_id, session_id, error_kind, duration_ms,
     occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertFederationAuditEntryParams struct {
	PeerID       string         `json:"peer_id"`
	RemoteUserID sql.NullString `json:"remote_user_id"`
	Method       string         `json:"method"`
	Endpoint     string         `json:"endpoint"`
	StatusCode   int32          `json:"status_code"`
	BytesOut     int64          `json:"bytes_out"`
	ItemID       sql.NullString `json:"item_id"`
	SessionID    sql.NullString `json:"session_id"`
	ErrorKind    sql.NullString `json:"error_kind"`
	DurationMs   sql.NullInt32  `json:"duration_ms"`
	OccurredAt   time.Time      `json:"occurred_at"`
}

// ============================================================
// audit log
// ============================================================
func (q *Queries) InsertFederationAuditEntry(ctx context.Context, arg InsertFederationAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertFederationAuditEntry,
		arg.PeerID,
		arg.RemoteUserID,
		arg.Method,
		arg.Endpoint,
		arg.StatusCode,
		arg.BytesOut,
		arg.ItemID,
		arg.SessionID,
		arg.ErrorKind,
		arg.DurationMs,
		arg.OccurredAt,
	)
	return err
}

const insertInvite = `-- name: InsertInvite :exec

INSERT INTO federation_invites
    (id, code, created_by_user_id, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInviteParams struct {
	ID              string    `json:"id"`
	Code            string    `json:"code"`
	CreatedByUserID string    `json:"created_by_user_id"`
	CreatedAt       time.Time `json:"created_at"`
	ExpiresAt       time.Time `json:"expires_at"`
}

// ============================================================
// invites
// ============================================================
func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, insertInvite,
		arg.ID,
		arg.Code,
		arg.CreatedByUserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const insertPeer = `-- name: InsertPeer :exec

INSERT INTO federation_peers
    (id, server_uuid, name, base_url, public_key, status, created_at, paired_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPeerParams struct {
	ID         string       `json:"id"`
	ServerUuid string       `json:"server_uuid"`
	Name       string       `json:"name"`
	BaseUrl    string       `json:"base_url"`
	PublicKey  []byte       `json:"public_key"`
	Status     string       `json:"status"`
	CreatedAt  time.Time    `json:"created_at"`
	PairedAt   sql.NullTime `json:"paired_at"`
}

// ============================================================
// peers
// ============================================================
func (q *Queries) InsertPeer(ctx context.Context, arg InsertPeerParams) error {
	_, err := q.db.ExecContext(ctx, insertPeer,
		arg.ID,
		arg.ServerUuid,
		arg.Name,
		arg.BaseUrl,
		arg.PublicKey,
		arg.Status,
		arg.CreatedAt,
		arg.PairedAt,
	)
	return err
}

const insertServerIdentity = `-- name: InsertServerIdentity :exec
INSERT INTO server_identity
    (id, server_uuid, name, private_key, public_key, created_at)
VALUES (1, $1, $2, $3, $4, $5)
`

type InsertServerIdentityParams struct {
	ServerUuid string    `json:"server_uuid"`
	Name       string    `json:"name"`
	PrivateKey []byte    `json:"private_key"`
	PublicKey  []byte    `json:"public_key"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) InsertServerIdentity(ctx context.Context, arg InsertServerIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertServerIdentity,
		arg.ServerUuid,
		arg.Name,
		arg.PrivateKey,
		arg.PublicKey,
		arg.CreatedAt,
	)
	return err
}

const listActiveInvites = `-- name: ListActiveInvites :many
SELECT id, code, created_by_user_id, created_at, expires_at,
       accepted_by_peer_id, accepted_at
FROM federation_invites
WHERE accepted_at IS NULL AND expires_at > $1
ORDER BY created_at DESC
`

func (q *Queries) ListActiveInvites(ctx context.Context, expiresAt time.Time) ([]FederationInvite, error) {
	rows, err := q.db.QueryContext(ctx, listActiveInvites, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationInvite{}
	for rows.Next() {
		var i FederationInvite
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedByPeerID,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCachedItems = `-- name: ListCachedItems :many
SELECT remote_id, type, title,
       COALESCE(year, 0) AS year,
       COALESCE(overview, '') AS overview,
       has_poster
FROM federation_item_cache
WHERE peer_id = $1 AND library_id = $2
ORDER BY LOWER(title) ASC
LIMIT $3 OFFSET $4
`

type ListCachedItemsParams struct {
	PeerID    string `json:"peer_id"`
	LibraryID string `json:"library_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListCachedItemsRow struct {
	RemoteID  string `json:"remote_id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Year      int32  `json:"year"`
	Overview  string `json:"overview"`
	HasPoster bool   `json:"has_poster"`
}

func (q *Queries) ListCachedItems(ctx context.Context, arg ListCachedItemsParams) ([]ListCachedItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCachedItems,
		arg.PeerID,
		arg.LibraryID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCachedItemsRow{}
	for rows.Next() {
		var i ListCachedItemsRow
		if err := rows.Scan(
			&i.RemoteID,
			&i.Type,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.HasPoster,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederationAuditEntries = `-- name: ListFederationAuditEntries :many
SELECT peer_id, remote_user_id, method, endpoint, status_code,
       bytes_out, item_id, session_id, error_kind, duration_ms,
       occurred_at
FROM federation_audit_log
WHERE peer_id = $1
ORDER BY occurred_at DESC
LIMIT $2
`

type ListFederationAuditEntriesParams struct {
	PeerID string `json:"peer_id"`
	Limit  int32  `json:"limit"`
}

type ListFederationAuditEntriesRow struct {
	PeerID       string         `json:"peer_id"`
	RemoteUserID sql.NullString `json:"remote_user_id"`
	Method       string         `json:"method"`
	Endpoint     string         `json:"endpoint"`
	StatusCode   int32          `json:"status_code"`
	BytesOut     int64          `json:"bytes_out"`
	ItemID       sql.NullString `json:"item_id"`
	SessionID    sql.NullString `json:"session_id"`
	ErrorKind    sql.NullString `json:"error_kind"`
	DurationMs   sql.NullInt32  `json:"duration_ms"`
	OccurredAt   time.Time      `json:"occurred_at"`
}

func (q *Queries) ListFederationAuditEntries(ctx context.Context, arg ListFederationAuditEntriesParams) ([]ListFederationAuditEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFederationAuditEntries, arg.PeerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFederationAuditEntriesRow{}
	for rows.Next() {
		var i ListFederationAuditEntriesRow
		if err := rows.Scan(
			&i.PeerID,
			&i.RemoteUserID,
			&i.Method,
			&i.Endpoint,
			&i.StatusCode,
			&i.BytesOut,
			&i.ItemID,
			&i.SessionID,
			&i.ErrorKind,
			&i.DurationMs,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederationContinueWatching = `-- name: ListFederationContinueWatching :many
SELECT fp.peer_id, fp.remote_item_id, fp.position_ticks,
       fp.duration_ticks, fp.last_played_at,
       c.library_id, c.type, c.title,
       COALESCE(c.year, 0) AS year,
       COALESCE(c.overview, '') AS overview,
       c.has_poster,
       p.name AS peer_name
FROM federation_progress fp
JOIN federation_item_cache c
  ON c.peer_id = fp.peer_id AND c.remote_id = fp.remote_item_id
JOIN federation_peers p
  ON p.id = fp.peer_id
WHERE fp.user_id = $1
  AND NOT fp.completed
  AND fp.position_ticks > 0
  AND p.status = 'paired'
  AND NOT (
    fp.duration_ticks > 0
    AND fp.position_ticks * 100 >= fp.duration_ticks * 90
  )
ORDER BY fp.last_played_at DESC
LIMIT $2
`

type ListFederationContinueWatchingParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type ListFederationContinueWatchingRow struct {
	PeerID        string    `json:"peer_id"`
	RemoteItemID  string    `json:"remote_item_id"`
	PositionTicks int64     `json:"position_ticks"`
	DurationTicks int64     `json:"duration_ticks"`
	LastPlayedAt  time.Time `json:"last_played_at"`
	LibraryID     string    `json:"library_id"`
	Type          string    `json:"type"`
	Title         string    `json:"title"`
	Year          int32     `json:"year"`
	Overview      string    `json:"overview"`
	HasPoster     bool      `json:"has_poster"`
	PeerName      string    `json:"peer_name"`
}

// Cross-peer Continue Watching rail. Only rows that look genuinely
// "in progress" are returned: not completed, position > 0, and (when
// duration is known) less than 90 percent played -- mirrors the local
// ContinueWatching filter so peer rows behave the same way the user
// already expects from local rows. Joins the catalog cache for
// title / poster availability so the rail can render without a
// per-row hop. Rows whose cache entry has been evicted (peer
// catalog refreshed against newer state) are dropped from the rail
// rather than rendered title-less.
func (q *Queries) ListFederationContinueWatching(ctx context.Context, arg ListFederationContinueWatchingParams) ([]ListFederationContinueWatchingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFederationContinueWatching, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFederationContinueWatchingRow{}
	for rows.Next() {
		var i ListFederationContinueWatchingRow
		if err := rows.Scan(
			&i.PeerID,
			&i.RemoteItemID,
			&i.PositionTicks,
			&i.DurationTicks,
			&i.LastPlayedAt,
			&i.LibraryID,
			&i.Type,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.HasPoster,
			&i.PeerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeers = `-- name: ListPeers :many
SELECT id, server_uuid, name, base_url, public_key, status,
       created_at, paired_at, last_seen_at, last_seen_status_code, revoked_at
FROM federation_peers
ORDER BY created_at DESC
`

func (q *Queries) ListPeers(ctx context.Context) ([]FederationPeer, error) {
	rows, err := q.db.QueryContext(ctx, listPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationPeer{}
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.ServerUuid,
			&i.Name,
			&i.BaseUrl,
			&i.PublicKey,
			&i.Status,
			&i.CreatedAt,
			&i.PairedAt,
			&i.LastSeenAt,
			&i.LastSeenStatusCode,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSharedItems = `-- name: ListRecentSharedItems :many

SELECT i.id, i.type, i.title,
       COALESCE(i.year, 0) AS year,
       COALESCE(m.overview, '') AS overview,
       EXISTS (
         SELECT 1 FROM images img
          WHERE img.item_id = i.id
            AND img.type = 'primary'
            AND img.is_primary
       ) AS has_poster,
       i.library_id
FROM items i
JOIN federation_library_shares s ON s.library_id = i.library_id
LEFT JOIN metadata m ON m.item_id = i.id
WHERE s.peer_id = $1 AND s.can_browse
  AND i.parent_id IS NULL
ORDER BY i.added_at DESC
LIMIT $2
`

type ListRecentSharedItemsParams struct {
	PeerID string `json:"peer_id"`
	Limit  int32  `json:"limit"`
}

type ListRecentSharedItemsRow struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Year      int32  `json:"year"`
	Overview  string `json:"overview"`
	HasPoster bool   `json:"has_poster"`
	LibraryID string `json:"library_id"`
}

// NOTE: SearchSharedItems is implemented as raw SQL in
// federation_repository.go because sqlc does not parse FTS5 virtual
// tables (items_fts MATCH $5). Same precedent as item_repository.go's
// List path.
// Most recently added items across every library shared with `peerID`
// (CanBrowse gate). Powers the consumer-side "Recently added on
// peers" rail: each paired peer answers with its top-N freshest
// titles, the consumer fan-out merges them. library_id is selected
// so the consumer can route a click into
// /peers/{peerID}/libraries/{libraryID}/items/{id} (same shape as
// the search hits).
func (q *Queries) ListRecentSharedItems(ctx context.Context, arg ListRecentSharedItemsParams) ([]ListRecentSharedItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSharedItems, arg.PeerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentSharedItemsRow{}
	for rows.Next() {
		var i ListRecentSharedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.HasPoster,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedItems = `-- name: ListSharedItems :many
SELECT i.id, i.type, i.title,
       COALESCE(i.year, 0) AS year,
       COALESCE(m.overview, '') AS overview,
       EXISTS (
         SELECT 1 FROM images img
          WHERE img.item_id = i.id
            AND img.type = 'primary'
            AND img.is_primary
       ) AS has_poster
FROM items i
JOIN federation_library_shares s ON s.library_id = i.library_id
LEFT JOIN metadata m ON m.item_id = i.id
WHERE i.library_id = $1 AND s.peer_id = $2 AND s.can_browse
  AND i.parent_id IS NULL
ORDER BY LOWER(i.sort_title) ASC
LIMIT $3 OFFSET $4
`

type ListSharedItemsParams struct {
	LibraryID string `json:"library_id"`
	PeerID    string `json:"peer_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListSharedItemsRow struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Year      int32  `json:"year"`
	Overview  string `json:"overview"`
	HasPoster bool   `json:"has_poster"`
}

// Overview lives in the metadata sidecar (LEFT JOIN so items without
// metadata still surface with empty overview). HasPoster is an EXISTS
// subquery against the images table so the listing path does not
// need to pull the image id; the actual bytes flow through
// /peer/items/{id}/poster on demand.
func (q *Queries) ListSharedItems(ctx context.Context, arg ListSharedItemsParams) ([]ListSharedItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSharedItems,
		arg.LibraryID,
		arg.PeerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedItemsRow{}
	for rows.Next() {
		var i ListSharedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Year,
			&i.Overview,
			&i.HasPoster,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedLibrariesForPeer = `-- name: ListSharedLibrariesForPeer :many
SELECT l.id, l.name, l.content_type,
       s.can_browse, s.can_play, s.can_download, s.can_livetv
FROM federation_library_shares s
JOIN libraries l ON l.id = s.library_id
WHERE s.peer_id = $1
ORDER BY LOWER(l.name) ASC
`

type ListSharedLibrariesForPeerRow struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	ContentType string `json:"content_type"`
	CanBrowse   bool   `json:"can_browse"`
	CanPlay     bool   `json:"can_play"`
	CanDownload bool   `json:"can_download"`
	CanLivetv   bool   `json:"can_livetv"`
}

func (q *Queries) ListSharedLibrariesForPeer(ctx context.Context, peerID string) ([]ListSharedLibrariesForPeerRow, error) {
	rows, err := q.db.QueryContext(ctx, listSharedLibrariesForPeer, peerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharedLibrariesForPeerRow{}
	for rows.Next() {
		var i ListSharedLibrariesForPeerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentType,
			&i.CanBrowse,
			&i.CanPlay,
			&i.CanDownload,
			&i.CanLivetv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesByPeer = `-- name: ListSharesByPeer :many
SELECT id, peer_id, library_id, can_browse, can_play,
       can_download, can_livetv, extra_scopes, created_by, created_at
FROM federation_library_shares
WHERE peer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSharesByPeer(ctx context.Context, peerID string) ([]FederationLibraryShare, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByPeer, peerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FederationLibraryShare{}
	for rows.Next() {
		var i FederationLibraryShare
		if err := rows.Scan(
			&i.ID,
			&i.PeerID,
			&i.LibraryID,
			&i.CanBrowse,
			&i.CanPlay,
			&i.CanDownload,
			&i.CanLivetv,
			&i.ExtraScopes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE federation_invites
SET accepted_by_peer_id = $1, accepted_at = $2
WHERE id = $3 AND accepted_at IS NULL
`

type MarkInviteUsedParams struct {
	AcceptedByPeerID sql.NullString `json:"accepted_by_peer_id"`
	AcceptedAt       sql.NullTime   `json:"accepted_at"`
	ID               string         `json:"id"`
}

func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error {
	_, err := q.db.ExecContext(ctx, markInviteUsed, arg.AcceptedByPeerID, arg.AcceptedAt, arg.ID)
	return err
}

const pruneFederationAuditBefore = `-- name: PruneFederationAuditBefore :execrows
DELETE FROM federation_audit_log
WHERE occurred_at < $1
`

func (q *Queries) PruneFederationAuditBefore(ctx context.Context, occurredAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneFederationAuditBefore, occurredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePeerLastSeen = `-- name: UpdatePeerLastSeen :exec
UPDATE federation_peers
SET last_seen_at = $1, last_seen_status_code = $2
WHERE id = $3
`

type UpdatePeerLastSeenParams struct {
	LastSeenAt         sql.NullTime  `json:"last_seen_at"`
	LastSeenStatusCode sql.NullInt32 `json:"last_seen_status_code"`
	ID                 string        `json:"id"`
}

func (q *Queries) UpdatePeerLastSeen(ctx context.Context, arg UpdatePeerLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updatePeerLastSeen, arg.LastSeenAt, arg.LastSeenStatusCode, arg.ID)
	return err
}

const updatePeerPaired = `-- name: UpdatePeerPaired :exec
UPDATE federation_peers
SET status = 'paired', paired_at = $1
WHERE id = $2
`

type UpdatePeerPairedParams struct {
	PairedAt sql.NullTime `json:"paired_at"`
	ID       string       `json:"id"`
}

func (q *Queries) UpdatePeerPaired(ctx context.Context, arg UpdatePeerPairedParams) error {
	_, err := q.db.ExecContext(ctx, updatePeerPaired, arg.PairedAt, arg.ID)
	return err
}

const updatePeerRevoked = `-- name: UpdatePeerRevoked :execrows
UPDATE federation_peers
SET status = 'revoked', revoked_at = $1
WHERE id = $2 AND status != 'revoked'
`

type UpdatePeerRevokedParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdatePeerRevoked(ctx context.Context, arg UpdatePeerRevokedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePeerRevoked, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertFederationProgress = `-- name: UpsertFederationProgress :exec

INSERT INTO federation_progress
    (user_id, peer_id, remote_item_id, position_ticks, duration_ticks,
     completed, last_played_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(user_id, peer_id, remote_item_id) DO UPDATE SET
    position_ticks = excluded.position_ticks,
    -- Only overwrite duration when the caller actually knows it.
    -- The player learns duration from the manifest after a few
    -- segments; the first save typically arrives before that, so
    -- the first row may be inserted with duration_ticks = 0 and
    -- later upserts replace it with the real value.
    duration_ticks = CASE WHEN excluded.duration_ticks > 0
                          THEN excluded.duration_ticks
                          ELSE federation_progress.duration_ticks END,
    completed = excluded.completed,
    last_played_at = excluded.last_played_at,
    updated_at = excluded.updated_at
`

type UpsertFederationProgressParams struct {
	UserID        string    `json:"user_id"`
	PeerID        string    `json:"peer_id"`
	RemoteItemID  string    `json:"remote_item_id"`
	PositionTicks int64     `json:"position_ticks"`
	DurationTicks int64     `json:"duration_ticks"`
	Completed     bool      `json:"completed"`
	LastPlayedAt  time.Time `json:"last_played_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// ============================================================
// federation_progress (028) -- cross-peer Continue Watching
// ============================================================
func (q *Queries) UpsertFederationProgress(ctx context.Context, arg UpsertFederationProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertFederationProgress,
		arg.UserID,
		arg.PeerID,
		arg.RemoteItemID,
		arg.PositionTicks,
		arg.DurationTicks,
		arg.Completed,
		arg.LastPlayedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertLibraryShare = `-- name: UpsertLibraryShare :exec

INSERT INTO federation_library_shares
    (id, peer_id, library_id, can_browse, can_play, can_download,
     can_livetv, extra_scopes, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT(peer_id, library_id) DO UPDATE SET
    can_browse   = excluded.can_browse,
    can_play     = excluded.can_play,
    can_download = excluded.can_download,
    can_livetv   = excluded.can_livetv,
    extra_scopes = excluded.extra_scopes
`

type UpsertLibraryShareParams struct {
	ID          string         `json:"id"`
	PeerID      string         `json:"peer_id"`
	LibraryID   string         `json:"library_id"`
	CanBrowse   bool           `json:"can_browse"`
	CanPlay     bool           `json:"can_play"`
	CanDownload bool           `json:"can_download"`
	CanLivetv   bool           `json:"can_livetv"`
	ExtraScopes sql.NullString `json:"extra_scopes"`
	CreatedBy   string         `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
}

// ============================================================
// library shares
// ============================================================
func (q *Queries) UpsertLibraryShare(ctx context.Context, arg UpsertLibraryShareParams) error {
	_, err := q.db.ExecContext(ctx, upsertLibraryShare,
		arg.ID,
		arg.PeerID,
		arg.LibraryID,
		arg.CanBrowse,
		arg.CanPlay,
		arg.CanDownload,
		arg.CanLivetv,
		arg.ExtraScopes,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}
