// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_values.sql

package sqlc_pg

import (
	"context"
)

const clearItemValuesForItem = `-- name: ClearItemValuesForItem :exec
DELETE FROM item_value_map
WHERE item_id = $1 AND value_id IN (
    SELECT id FROM item_values WHERE type = $2
)
`

type ClearItemValuesForItemParams struct {
	ItemID string `json:"item_id"`
	Type   string `json:"type"`
}

// Used before re-populating an item's tags during a metadata refresh,
// so removed genres don't linger after a TMDb update changes them.
func (q *Queries) ClearItemValuesForItem(ctx context.Context, arg ClearItemValuesForItemParams) error {
	_, err := q.db.ExecContext(ctx, clearItemValuesForItem, arg.ItemID, arg.Type)
	return err
}

const linkItemValue = `-- name: LinkItemValue :exec
INSERT INTO item_value_map (item_id, value_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkItemValueParams struct {
	ItemID  string `json:"item_id"`
	ValueID string `json:"value_id"`
}

// Postgres: INSERT OR IGNORE → ON CONFLICT DO NOTHING. La PK
// compuesta (item_id, value_id) cubre el dedup natural.
func (q *Queries) LinkItemValue(ctx context.Context, arg LinkItemValueParams) error {
	_, err := q.db.ExecContext(ctx, linkItemValue, arg.ItemID, arg.ValueID)
	return err
}

const upsertItemValue = `-- name: UpsertItemValue :exec

INSERT INTO item_values (id, type, value, clean_value)
VALUES ($1, $2, $3, $4)
ON CONFLICT(type, clean_value) DO UPDATE SET value = excluded.value
`

type UpsertItemValueParams struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Value      string `json:"value"`
	CleanValue string `json:"clean_value"`
}

// Normalized tag store reused for genres (and future tag-like facets).
//
// Table schema: migrations/sqlite/001_initial_schema.sql (item_values, item_value_map).
// Backfill: migrations/sqlite/031_item_values_genres_backfill.sql.
//
// The synthetic id format ("<type>:<clean_value>", lowercased) makes
// INSERT-OR-IGNORE idempotent across items sharing the same value, so
// the scanner can re-run UpsertItemValue per scan without dedup logic.
func (q *Queries) UpsertItemValue(ctx context.Context, arg UpsertItemValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertItemValue,
		arg.ID,
		arg.Type,
		arg.Value,
		arg.CleanValue,
	)
	return err
}
