// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: libraries.sql

package sqlc_pg

import (
	"context"
	"database/sql"
	"time"
)

const deleteLibrary = `-- name: DeleteLibrary :execrows
DELETE FROM libraries WHERE id = $1
`

func (q *Queries) DeleteLibrary(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLibrary, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePathsByLibrary = `-- name: DeletePathsByLibrary :exec
DELETE FROM library_paths WHERE library_id = $1
`

func (q *Queries) DeletePathsByLibrary(ctx context.Context, libraryID string) error {
	_, err := q.db.ExecContext(ctx, deletePathsByLibrary, libraryID)
	return err
}

const getLibraryByID = `-- name: GetLibraryByID :one
SELECT id, name, content_type, scan_mode, COALESCE(scan_interval, '6h') AS scan_interval,
       COALESCE(m3u_url, '') AS m3u_url, COALESCE(epg_url, '') AS epg_url,
       COALESCE(refresh_interval, '24h') AS refresh_interval,
       language_filter, tls_insecure,
       created_at, updated_at
FROM libraries
WHERE id = $1
`

type GetLibraryByIDRow struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	ContentType     string    `json:"content_type"`
	ScanMode        string    `json:"scan_mode"`
	ScanInterval    string    `json:"scan_interval"`
	M3uUrl          string    `json:"m3u_url"`
	EpgUrl          string    `json:"epg_url"`
	RefreshInterval string    `json:"refresh_interval"`
	LanguageFilter  string    `json:"language_filter"`
	TlsInsecure     int32     `json:"tls_insecure"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetLibraryByID(ctx context.Context, id string) (GetLibraryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getLibraryByID, id)
	var i GetLibraryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContentType,
		&i.ScanMode,
		&i.ScanInterval,
		&i.M3uUrl,
		&i.EpgUrl,
		&i.RefreshInterval,
		&i.LanguageFilter,
		&i.TlsInsecure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantLibraryAccess = `-- name: GrantLibraryAccess :exec
INSERT INTO library_access (user_id, library_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantLibraryAccessParams struct {
	UserID    string `json:"user_id"`
	LibraryID string `json:"library_id"`
}

// Postgres: INSERT OR IGNORE → ON CONFLICT DO NOTHING (sin target =
// match cualquier constraint, mismo comportamiento que SQLite).
func (q *Queries) GrantLibraryAccess(ctx context.Context, arg GrantLibraryAccessParams) error {
	_, err := q.db.ExecContext(ctx, grantLibraryAccess, arg.UserID, arg.LibraryID)
	return err
}

const grantPrimaryAdminLibraryAccess = `-- name: GrantPrimaryAdminLibraryAccess :exec
INSERT INTO library_access (user_id, library_id)
SELECT u.id, $1
FROM users u
WHERE u.role = 'admin' AND u.parent_user_id IS NULL
ORDER BY u.created_at ASC
LIMIT 1
ON CONFLICT DO NOTHING
`

// Grants the given library_id to the primary admin (oldest top-level
// role=admin row, same definition as GetPrimaryAdminID). Idempotent
// via ON CONFLICT DO NOTHING; no-op when no admin exists yet (cold-
// start pre setup-wizard). Called from LibraryRepository.Create
// inside the same tx so the invariant "primary admin sees every
// library" holds for libraries created after migration 041.
func (q *Queries) GrantPrimaryAdminLibraryAccess(ctx context.Context, libraryID string) error {
	_, err := q.db.ExecContext(ctx, grantPrimaryAdminLibraryAccess, libraryID)
	return err
}

const insertLibrary = `-- name: InsertLibrary :exec

INSERT INTO libraries (id, name, content_type, scan_mode, scan_interval,
    m3u_url, epg_url, refresh_interval, language_filter, tls_insecure, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertLibraryParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	ContentType     string         `json:"content_type"`
	ScanMode        string         `json:"scan_mode"`
	ScanInterval    sql.NullString `json:"scan_interval"`
	M3uUrl          sql.NullString `json:"m3u_url"`
	EpgUrl          sql.NullString `json:"epg_url"`
	RefreshInterval sql.NullString `json:"refresh_interval"`
	LanguageFilter  string         `json:"language_filter"`
	TlsInsecure     int32          `json:"tls_insecure"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

// Library management (media libraries, paths, access control).
//
// Tables: libraries, library_paths, library_access.
func (q *Queries) InsertLibrary(ctx context.Context, arg InsertLibraryParams) error {
	_, err := q.db.ExecContext(ctx, insertLibrary,
		arg.ID,
		arg.Name,
		arg.ContentType,
		arg.ScanMode,
		arg.ScanInterval,
		arg.M3uUrl,
		arg.EpgUrl,
		arg.RefreshInterval,
		arg.LanguageFilter,
		arg.TlsInsecure,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertLibraryPath = `-- name: InsertLibraryPath :exec
INSERT INTO library_paths (library_id, path) VALUES ($1, $2)
`

type InsertLibraryPathParams struct {
	LibraryID string `json:"library_id"`
	Path      string `json:"path"`
}

func (q *Queries) InsertLibraryPath(ctx context.Context, arg InsertLibraryPathParams) error {
	_, err := q.db.ExecContext(ctx, insertLibraryPath, arg.LibraryID, arg.Path)
	return err
}

const listAllPaths = `-- name: ListAllPaths :many
SELECT library_id, path FROM library_paths ORDER BY library_id, path
`

func (q *Queries) ListAllPaths(ctx context.Context) ([]LibraryPath, error) {
	rows, err := q.db.QueryContext(ctx, listAllPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryPath{}
	for rows.Next() {
		var i LibraryPath
		if err := rows.Scan(&i.LibraryID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, content_type, scan_mode, COALESCE(scan_interval, '6h') AS scan_interval,
       COALESCE(m3u_url, '') AS m3u_url, COALESCE(epg_url, '') AS epg_url,
       COALESCE(refresh_interval, '24h') AS refresh_interval,
       language_filter, tls_insecure,
       created_at, updated_at
FROM libraries
ORDER BY name
`

type ListLibrariesRow struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	ContentType     string    `json:"content_type"`
	ScanMode        string    `json:"scan_mode"`
	ScanInterval    string    `json:"scan_interval"`
	M3uUrl          string    `json:"m3u_url"`
	EpgUrl          string    `json:"epg_url"`
	RefreshInterval string    `json:"refresh_interval"`
	LanguageFilter  string    `json:"language_filter"`
	TlsInsecure     int32     `json:"tls_insecure"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) ListLibraries(ctx context.Context) ([]ListLibrariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibrariesRow{}
	for rows.Next() {
		var i ListLibrariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContentType,
			&i.ScanMode,
			&i.ScanInterval,
			&i.M3uUrl,
			&i.EpgUrl,
			&i.RefreshInterval,
			&i.LanguageFilter,
			&i.TlsInsecure,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryAccessByUser = `-- name: ListLibraryAccessByUser :many
SELECT library_id FROM library_access WHERE user_id = $1 ORDER BY library_id
`

// Returns library_ids the user_id has explicit grants for. Admin-only
// surface (the user's library list goes through ListLibrariesForUser
// which applies the profile-inheritance predicate). Callers pass the
// top-level user id; for profile rows the caller must resolve to the
// parent first. See ADR-014.
func (q *Queries) ListLibraryAccessByUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryAccessByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var library_id string
		if err := rows.Scan(&library_id); err != nil {
			return nil, err
		}
		items = append(items, library_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPathsByLibrary = `-- name: ListPathsByLibrary :many
SELECT path FROM library_paths WHERE library_id = $1 ORDER BY path
`

func (q *Queries) ListPathsByLibrary(ctx context.Context, libraryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPathsByLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLibraryAccess = `-- name: RevokeLibraryAccess :exec
DELETE FROM library_access WHERE user_id = $1 AND library_id = $2
`

type RevokeLibraryAccessParams struct {
	UserID    string `json:"user_id"`
	LibraryID string `json:"library_id"`
}

func (q *Queries) RevokeLibraryAccess(ctx context.Context, arg RevokeLibraryAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokeLibraryAccess, arg.UserID, arg.LibraryID)
	return err
}

const updateLibrary = `-- name: UpdateLibrary :execrows
UPDATE libraries SET name = $1, content_type = $2, scan_mode = $3, scan_interval = $4,
       m3u_url = $5, epg_url = $6, refresh_interval = $7, language_filter = $8,
       tls_insecure = $9, updated_at = $10
WHERE id = $11
`

type UpdateLibraryParams struct {
	Name            string         `json:"name"`
	ContentType     string         `json:"content_type"`
	ScanMode        string         `json:"scan_mode"`
	ScanInterval    sql.NullString `json:"scan_interval"`
	M3uUrl          sql.NullString `json:"m3u_url"`
	EpgUrl          sql.NullString `json:"epg_url"`
	RefreshInterval sql.NullString `json:"refresh_interval"`
	LanguageFilter  string         `json:"language_filter"`
	TlsInsecure     int32          `json:"tls_insecure"`
	UpdatedAt       time.Time      `json:"updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLibrary,
		arg.Name,
		arg.ContentType,
		arg.ScanMode,
		arg.ScanInterval,
		arg.M3uUrl,
		arg.EpgUrl,
		arg.RefreshInterval,
		arg.LanguageFilter,
		arg.TlsInsecure,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
