// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_streams.sql

package sqlc_pg

import (
	"context"
	"database/sql"
)

const deleteMediaStreamsByItem = `-- name: DeleteMediaStreamsByItem :exec

DELETE FROM media_streams WHERE item_id = $1
`

// Media stream tracks (video, audio, subtitle) per item.
//
// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE media_streams).
// PK: (item_id, stream_index).
func (q *Queries) DeleteMediaStreamsByItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteMediaStreamsByItem, itemID)
	return err
}

const insertMediaStream = `-- name: InsertMediaStream :exec
INSERT INTO media_streams (
    item_id, stream_index, stream_type, codec, profile, bitrate,
    width, height, frame_rate, hdr_type, color_space, channels, sample_rate,
    language, title, is_default, is_forced, is_hearing_impaired
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertMediaStreamParams struct {
	ItemID            string          `json:"item_id"`
	StreamIndex       int32           `json:"stream_index"`
	StreamType        string          `json:"stream_type"`
	Codec             sql.NullString  `json:"codec"`
	Profile           sql.NullString  `json:"profile"`
	Bitrate           sql.NullInt32   `json:"bitrate"`
	Width             sql.NullInt32   `json:"width"`
	Height            sql.NullInt32   `json:"height"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	HdrType           sql.NullString  `json:"hdr_type"`
	ColorSpace        sql.NullString  `json:"color_space"`
	Channels          sql.NullInt32   `json:"channels"`
	SampleRate        sql.NullInt32   `json:"sample_rate"`
	Language          sql.NullString  `json:"language"`
	Title             sql.NullString  `json:"title"`
	IsDefault         sql.NullBool    `json:"is_default"`
	IsForced          sql.NullBool    `json:"is_forced"`
	IsHearingImpaired sql.NullBool    `json:"is_hearing_impaired"`
}

func (q *Queries) InsertMediaStream(ctx context.Context, arg InsertMediaStreamParams) error {
	_, err := q.db.ExecContext(ctx, insertMediaStream,
		arg.ItemID,
		arg.StreamIndex,
		arg.StreamType,
		arg.Codec,
		arg.Profile,
		arg.Bitrate,
		arg.Width,
		arg.Height,
		arg.FrameRate,
		arg.HdrType,
		arg.ColorSpace,
		arg.Channels,
		arg.SampleRate,
		arg.Language,
		arg.Title,
		arg.IsDefault,
		arg.IsForced,
		arg.IsHearingImpaired,
	)
	return err
}

const listMediaStreamsByItem = `-- name: ListMediaStreamsByItem :many
SELECT item_id, stream_index, stream_type,
       COALESCE(codec, '') AS codec,
       COALESCE(profile, '') AS profile,
       COALESCE(bitrate, 0) AS bitrate,
       COALESCE(width, 0) AS width,
       COALESCE(height, 0) AS height,
       COALESCE(frame_rate, 0) AS frame_rate,
       COALESCE(hdr_type, '') AS hdr_type,
       COALESCE(color_space, '') AS color_space,
       COALESCE(channels, 0) AS channels,
       COALESCE(sample_rate, 0) AS sample_rate,
       COALESCE(language, '') AS language,
       COALESCE(title, '') AS title,
       COALESCE(is_default, 0) AS is_default,
       COALESCE(is_forced, 0) AS is_forced,
       COALESCE(is_hearing_impaired, 0) AS is_hearing_impaired
FROM media_streams
WHERE item_id = $1
ORDER BY stream_index
`

type ListMediaStreamsByItemRow struct {
	ItemID            string  `json:"item_id"`
	StreamIndex       int32   `json:"stream_index"`
	StreamType        string  `json:"stream_type"`
	Codec             string  `json:"codec"`
	Profile           string  `json:"profile"`
	Bitrate           int32   `json:"bitrate"`
	Width             int32   `json:"width"`
	Height            int32   `json:"height"`
	FrameRate         float64 `json:"frame_rate"`
	HdrType           string  `json:"hdr_type"`
	ColorSpace        string  `json:"color_space"`
	Channels          int32   `json:"channels"`
	SampleRate        int32   `json:"sample_rate"`
	Language          string  `json:"language"`
	Title             string  `json:"title"`
	IsDefault         bool    `json:"is_default"`
	IsForced          bool    `json:"is_forced"`
	IsHearingImpaired bool    `json:"is_hearing_impaired"`
}

func (q *Queries) ListMediaStreamsByItem(ctx context.Context, itemID string) ([]ListMediaStreamsByItemRow, error) {
	rows, err := q.db.QueryContext(ctx, listMediaStreamsByItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMediaStreamsByItemRow{}
	for rows.Next() {
		var i ListMediaStreamsByItemRow
		if err := rows.Scan(
			&i.ItemID,
			&i.StreamIndex,
			&i.StreamType,
			&i.Codec,
			&i.Profile,
			&i.Bitrate,
			&i.Width,
			&i.Height,
			&i.FrameRate,
			&i.HdrType,
			&i.ColorSpace,
			&i.Channels,
			&i.SampleRate,
			&i.Language,
			&i.Title,
			&i.IsDefault,
			&i.IsForced,
			&i.IsHearingImpaired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
