// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc_pg

import (
	"database/sql"
	"time"
)

type ActivityLog struct {
	ID        string         `json:"id"`
	UserID    sql.NullString `json:"user_id"`
	Type      string         `json:"type"`
	ItemID    sql.NullString `json:"item_id"`
	Severity  sql.NullString `json:"severity"`
	Message   string         `json:"message"`
	DataJson  sql.NullString `json:"data_json"`
	CreatedAt time.Time      `json:"created_at"`
}

type AncestorID struct {
	ItemID     string `json:"item_id"`
	AncestorID string `json:"ancestor_id"`
}

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Channel struct {
	ID                  string         `json:"id"`
	LibraryID           string         `json:"library_id"`
	Name                string         `json:"name"`
	Number              sql.NullInt32  `json:"number"`
	GroupName           sql.NullString `json:"group_name"`
	LogoUrl             sql.NullString `json:"logo_url"`
	StreamUrl           string         `json:"stream_url"`
	TvgID               sql.NullString `json:"tvg_id"`
	Language            sql.NullString `json:"language"`
	Country             sql.NullString `json:"country"`
	IsActive            bool           `json:"is_active"`
	AddedAt             time.Time      `json:"added_at"`
	LastProbeAt         sql.NullTime   `json:"last_probe_at"`
	LastProbeStatus     string         `json:"last_probe_status"`
	LastProbeError      string         `json:"last_probe_error"`
	ConsecutiveFailures int32          `json:"consecutive_failures"`
}

type ChannelLogoOverride struct {
	LibraryID string    `json:"library_id"`
	StreamUrl string    `json:"stream_url"`
	LogoUrl   string    `json:"logo_url"`
	LogoFile  string    `json:"logo_file"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ChannelOverride struct {
	LibraryID string    `json:"library_id"`
	StreamUrl string    `json:"stream_url"`
	TvgID     string    `json:"tvg_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ChannelWatchHistory struct {
	UserID        string    `json:"user_id"`
	StreamUrl     string    `json:"stream_url"`
	LastWatchedAt time.Time `json:"last_watched_at"`
}

type Chapter struct {
	ItemID     string         `json:"item_id"`
	StartTicks int64          `json:"start_ticks"`
	EndTicks   int64          `json:"end_ticks"`
	Title      sql.NullString `json:"title"`
	ImagePath  sql.NullString `json:"image_path"`
}

type Collection struct {
	ID          string    `json:"id"`
	TmdbID      int32     `json:"tmdb_id"`
	Name        string    `json:"name"`
	Overview    string    `json:"overview"`
	PosterUrl   string    `json:"poster_url"`
	BackdropUrl string    `json:"backdrop_url"`
	CreatedAt   time.Time `json:"created_at"`
}

type CollectionImageOverride struct {
	CollectionID string    `json:"collection_id"`
	ImageType    string    `json:"image_type"`
	Url          string    `json:"url"`
	File         string    `json:"file"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type DeviceCode struct {
	DeviceCode   string         `json:"device_code"`
	UserCode     string         `json:"user_code"`
	DeviceName   string         `json:"device_name"`
	UserID       sql.NullString `json:"user_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	ApprovedAt   sql.NullTime   `json:"approved_at"`
	ConsumedAt   sql.NullTime   `json:"consumed_at"`
	LastPolledAt sql.NullTime   `json:"last_polled_at"`
}

type EpgProgram struct {
	ID          string         `json:"id"`
	ChannelID   string         `json:"channel_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	IconUrl     sql.NullString `json:"icon_url"`
	StartTime   time.Time      `json:"start_time"`
	EndTime     time.Time      `json:"end_time"`
}

type EpisodeSegment struct {
	ItemID     string  `json:"item_id"`
	Kind       string  `json:"kind"`
	Source     string  `json:"source"`
	StartTicks int64   `json:"start_ticks"`
	EndTicks   int64   `json:"end_ticks"`
	Confidence float64 `json:"confidence"`
	DetectedAt int64   `json:"detected_at"`
}

type ExternalID struct {
	ItemID     string `json:"item_id"`
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

type FederationAuditLog struct {
	ID           string         `json:"id"`
	PeerID       string         `json:"peer_id"`
	RemoteUserID sql.NullString `json:"remote_user_id"`
	Method       string         `json:"method"`
	Endpoint     string         `json:"endpoint"`
	StatusCode   int32          `json:"status_code"`
	BytesOut     int64          `json:"bytes_out"`
	ItemID       sql.NullString `json:"item_id"`
	SessionID    sql.NullString `json:"session_id"`
	ErrorKind    sql.NullString `json:"error_kind"`
	DurationMs   sql.NullInt32  `json:"duration_ms"`
	OccurredAt   time.Time      `json:"occurred_at"`
}

type FederationInvite struct {
	ID               string         `json:"id"`
	Code             string         `json:"code"`
	CreatedByUserID  string         `json:"created_by_user_id"`
	CreatedAt        time.Time      `json:"created_at"`
	ExpiresAt        time.Time      `json:"expires_at"`
	AcceptedByPeerID sql.NullString `json:"accepted_by_peer_id"`
	AcceptedAt       sql.NullTime   `json:"accepted_at"`
}

type FederationItemCache struct {
	PeerID           string         `json:"peer_id"`
	LibraryID        string         `json:"library_id"`
	RemoteID         string         `json:"remote_id"`
	Type             string         `json:"type"`
	Title            string         `json:"title"`
	Year             sql.NullInt32  `json:"year"`
	Overview         sql.NullString `json:"overview"`
	CachedAt         time.Time      `json:"cached_at"`
	HasPoster        bool           `json:"has_poster"`
	PosterColor      string         `json:"poster_color"`
	PosterColorMuted string         `json:"poster_color_muted"`
}

type FederationLibraryShare struct {
	ID          string         `json:"id"`
	PeerID      string         `json:"peer_id"`
	LibraryID   string         `json:"library_id"`
	CanBrowse   bool           `json:"can_browse"`
	CanPlay     bool           `json:"can_play"`
	CanDownload bool           `json:"can_download"`
	CanLivetv   bool           `json:"can_livetv"`
	ExtraScopes sql.NullString `json:"extra_scopes"`
	CreatedBy   string         `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
}

type FederationPeer struct {
	ID                 string        `json:"id"`
	ServerUuid         string        `json:"server_uuid"`
	Name               string        `json:"name"`
	BaseUrl            string        `json:"base_url"`
	PublicKey          []byte        `json:"public_key"`
	Status             string        `json:"status"`
	CreatedAt          time.Time     `json:"created_at"`
	PairedAt           sql.NullTime  `json:"paired_at"`
	LastSeenAt         sql.NullTime  `json:"last_seen_at"`
	LastSeenStatusCode sql.NullInt32 `json:"last_seen_status_code"`
	RevokedAt          sql.NullTime  `json:"revoked_at"`
	AvatarColor        string        `json:"avatar_color"`
	AvatarImageUrl     string        `json:"avatar_image_url"`
}

type FederationPendingRequest struct {
	ID                 string         `json:"id"`
	Direction          string         `json:"direction"`
	PeerServerUuid     string         `json:"peer_server_uuid"`
	PeerName           string         `json:"peer_name"`
	PeerBaseUrl        string         `json:"peer_base_url"`
	PeerPublicKey      []byte         `json:"peer_public_key"`
	PeerAvatarColor    string         `json:"peer_avatar_color"`
	PeerAvatarImageUrl string         `json:"peer_avatar_image_url"`
	RequestToken       string         `json:"request_token"`
	CreatedAt          time.Time      `json:"created_at"`
	ExpiresAt          time.Time      `json:"expires_at"`
	Status             string         `json:"status"`
	RespondedAt        sql.NullTime   `json:"responded_at"`
	RespondedByUserID  sql.NullString `json:"responded_by_user_id"`
}

type FederationProgress struct {
	UserID        string    `json:"user_id"`
	PeerID        string    `json:"peer_id"`
	RemoteItemID  string    `json:"remote_item_id"`
	PositionTicks int64     `json:"position_ticks"`
	DurationTicks int64     `json:"duration_ticks"`
	Completed     bool      `json:"completed"`
	LastPlayedAt  time.Time `json:"last_played_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type FederationRateLimitState struct {
	PeerID               string    `json:"peer_id"`
	Tokens               float64   `json:"tokens"`
	LastRefillAt         time.Time `json:"last_refill_at"`
	DailyBytes           int64     `json:"daily_bytes"`
	DailyWindowStartedAt time.Time `json:"daily_window_started_at"`
}

type Image struct {
	ID                 string         `json:"id"`
	ItemID             string         `json:"item_id"`
	Type               string         `json:"type"`
	Path               string         `json:"path"`
	Width              sql.NullInt32  `json:"width"`
	Height             sql.NullInt32  `json:"height"`
	Blurhash           sql.NullString `json:"blurhash"`
	Provider           sql.NullString `json:"provider"`
	IsPrimary          sql.NullBool   `json:"is_primary"`
	AddedAt            time.Time      `json:"added_at"`
	IsLocked           bool           `json:"is_locked"`
	DominantColor      string         `json:"dominant_color"`
	DominantColorMuted string         `json:"dominant_color_muted"`
}

type IptvScheduledJob struct {
	LibraryID      string       `json:"library_id"`
	Kind           string       `json:"kind"`
	IntervalHours  int32        `json:"interval_hours"`
	Enabled        bool         `json:"enabled"`
	LastRunAt      sql.NullTime `json:"last_run_at"`
	LastStatus     string       `json:"last_status"`
	LastError      string       `json:"last_error"`
	LastDurationMs int32        `json:"last_duration_ms"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}

type Item struct {
	ID              string          `json:"id"`
	LibraryID       string          `json:"library_id"`
	ParentID        sql.NullString  `json:"parent_id"`
	Type            string          `json:"type"`
	Title           string          `json:"title"`
	SortTitle       string          `json:"sort_title"`
	OriginalTitle   sql.NullString  `json:"original_title"`
	Year            sql.NullInt32   `json:"year"`
	Path            sql.NullString  `json:"path"`
	Size            sql.NullInt64   `json:"size"`
	DurationTicks   sql.NullInt64   `json:"duration_ticks"`
	Container       sql.NullString  `json:"container"`
	Fingerprint     sql.NullString  `json:"fingerprint"`
	SeasonNumber    sql.NullInt32   `json:"season_number"`
	EpisodeNumber   sql.NullInt32   `json:"episode_number"`
	CommunityRating sql.NullFloat64 `json:"community_rating"`
	ContentRating   sql.NullString  `json:"content_rating"`
	PremiereDate    sql.NullTime    `json:"premiere_date"`
	AddedAt         time.Time       `json:"added_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	IsAvailable     bool            `json:"is_available"`
	SearchVector    interface{}     `json:"search_vector"`
}

type ItemMetadataLock struct {
	ItemID   string    `json:"item_id"`
	LockedAt time.Time `json:"locked_at"`
}

type ItemPerson struct {
	ItemID        string         `json:"item_id"`
	PersonID      string         `json:"person_id"`
	Role          string         `json:"role"`
	CharacterName sql.NullString `json:"character_name"`
	SortOrder     sql.NullInt32  `json:"sort_order"`
}

type ItemValue struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Value      string `json:"value"`
	CleanValue string `json:"clean_value"`
}

type ItemValueMap struct {
	ItemID  string `json:"item_id"`
	ValueID string `json:"value_id"`
}

type JwtSigningKey struct {
	ID        string       `json:"id"`
	Secret    string       `json:"secret"`
	CreatedAt time.Time    `json:"created_at"`
	RetiredAt sql.NullTime `json:"retired_at"`
}

type Library struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	ContentType     string         `json:"content_type"`
	ScanMode        string         `json:"scan_mode"`
	ScanInterval    sql.NullString `json:"scan_interval"`
	M3uUrl          sql.NullString `json:"m3u_url"`
	EpgUrl          sql.NullString `json:"epg_url"`
	RefreshInterval sql.NullString `json:"refresh_interval"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	LanguageFilter  string         `json:"language_filter"`
	TlsInsecure     int32          `json:"tls_insecure"`
}

type LibraryAccess struct {
	UserID    string `json:"user_id"`
	LibraryID string `json:"library_id"`
}

type LibraryChannelOrder struct {
	LibraryID string    `json:"library_id"`
	ChannelID string    `json:"channel_id"`
	Position  int32     `json:"position"`
	Hidden    bool      `json:"hidden"`
	UpdatedAt time.Time `json:"updated_at"`
}

type LibraryEpgSource struct {
	ID               string         `json:"id"`
	LibraryID        string         `json:"library_id"`
	CatalogID        sql.NullString `json:"catalog_id"`
	Url              string         `json:"url"`
	Priority         int32          `json:"priority"`
	LastRefreshedAt  sql.NullTime   `json:"last_refreshed_at"`
	LastStatus       sql.NullString `json:"last_status"`
	LastError        sql.NullString `json:"last_error"`
	LastProgramCount int32          `json:"last_program_count"`
	LastChannelCount int32          `json:"last_channel_count"`
	CreatedAt        time.Time      `json:"created_at"`
}

type LibraryPath struct {
	LibraryID string `json:"library_id"`
	Path      string `json:"path"`
}

type MediaSegment struct {
	ID         string `json:"id"`
	ItemID     string `json:"item_id"`
	Type       string `json:"type"`
	StartTicks int64  `json:"start_ticks"`
	EndTicks   int64  `json:"end_ticks"`
}

type MediaStream struct {
	ItemID            string          `json:"item_id"`
	StreamIndex       int32           `json:"stream_index"`
	StreamType        string          `json:"stream_type"`
	Codec             sql.NullString  `json:"codec"`
	Profile           sql.NullString  `json:"profile"`
	Bitrate           sql.NullInt32   `json:"bitrate"`
	Width             sql.NullInt32   `json:"width"`
	Height            sql.NullInt32   `json:"height"`
	FrameRate         sql.NullFloat64 `json:"frame_rate"`
	HdrType           sql.NullString  `json:"hdr_type"`
	ColorSpace        sql.NullString  `json:"color_space"`
	Channels          sql.NullInt32   `json:"channels"`
	SampleRate        sql.NullInt32   `json:"sample_rate"`
	Language          sql.NullString  `json:"language"`
	Title             sql.NullString  `json:"title"`
	IsDefault         sql.NullBool    `json:"is_default"`
	IsForced          sql.NullBool    `json:"is_forced"`
	IsHearingImpaired sql.NullBool    `json:"is_hearing_impaired"`
}

type Metadata struct {
	ItemID        string         `json:"item_id"`
	Overview      sql.NullString `json:"overview"`
	Tagline       sql.NullString `json:"tagline"`
	Studio        sql.NullString `json:"studio"`
	GenresJson    sql.NullString `json:"genres_json"`
	TagsJson      sql.NullString `json:"tags_json"`
	TrailerKey    string         `json:"trailer_key"`
	TrailerSite   string         `json:"trailer_site"`
	StudioLogoUrl string         `json:"studio_logo_url"`
	StudioID      sql.NullString `json:"studio_id"`
	CollectionID  sql.NullString `json:"collection_id"`
}

type Notification struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Kind      string       `json:"kind"`
	Title     string       `json:"title"`
	Body      string       `json:"body"`
	Link      string       `json:"link"`
	Payload   string       `json:"payload"`
	CreatedAt time.Time    `json:"created_at"`
	ReadAt    sql.NullTime `json:"read_at"`
}

type Person struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Type      sql.NullString `json:"type"`
	ThumbPath sql.NullString `json:"thumb_path"`
}

type Provider struct {
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	Version    string         `json:"version"`
	Status     string         `json:"status"`
	Priority   int32          `json:"priority"`
	ConfigJson sql.NullString `json:"config_json"`
	ApiKey     sql.NullString `json:"api_key"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type ServerIdentity struct {
	ID              string       `json:"id"`
	ServerUuid      string       `json:"server_uuid"`
	Name            string       `json:"name"`
	PrivateKey      []byte       `json:"private_key"`
	PublicKey       []byte       `json:"public_key"`
	CreatedAt       time.Time    `json:"created_at"`
	RotatedAt       sql.NullTime `json:"rotated_at"`
	AvatarColor     string       `json:"avatar_color"`
	AvatarImagePath string       `json:"avatar_image_path"`
}

type Session struct {
	ID                       string         `json:"id"`
	UserID                   string         `json:"user_id"`
	DeviceName               string         `json:"device_name"`
	DeviceID                 string         `json:"device_id"`
	IpAddress                sql.NullString `json:"ip_address"`
	RefreshTokenHash         string         `json:"refresh_token_hash"`
	CreatedAt                time.Time      `json:"created_at"`
	LastActiveAt             time.Time      `json:"last_active_at"`
	ExpiresAt                time.Time      `json:"expires_at"`
	PreviousRefreshTokenHash string         `json:"previous_refresh_token_hash"`
}

type Studio struct {
	ID        string        `json:"id"`
	TmdbID    sql.NullInt32 `json:"tmdb_id"`
	Name      string        `json:"name"`
	Slug      string        `json:"slug"`
	LogoUrl   string        `json:"logo_url"`
	CreatedAt time.Time     `json:"created_at"`
}

type TrickplayInfo struct {
	ItemID     string `json:"item_id"`
	Width      int32  `json:"width"`
	Height     int32  `json:"height"`
	TileWidth  int32  `json:"tile_width"`
	TileHeight int32  `json:"tile_height"`
	ThumbCount int32  `json:"thumb_count"`
	IntervalMs int32  `json:"interval_ms"`
	SpritePath string `json:"sprite_path"`
}

type UploadAudit struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	LibraryID    sql.NullString `json:"library_id"`
	OriginalName string         `json:"original_name"`
	FinalPath    sql.NullString `json:"final_path"`
	Bytes        int64          `json:"bytes"`
	Sha256       sql.NullString `json:"sha256"`
	MimeDetected sql.NullString `json:"mime_detected"`
	Outcome      string         `json:"outcome"`
	ErrorMessage sql.NullString `json:"error_message"`
	StartedAt    time.Time      `json:"started_at"`
	FinishedAt   time.Time      `json:"finished_at"`
	DurationMs   int64          `json:"duration_ms"`
}

type User struct {
	ID                     string         `json:"id"`
	Username               string         `json:"username"`
	DisplayName            string         `json:"display_name"`
	PasswordHash           string         `json:"password_hash"`
	AvatarPath             sql.NullString `json:"avatar_path"`
	Role                   string         `json:"role"`
	IsActive               bool           `json:"is_active"`
	MaxSessions            int32          `json:"max_sessions"`
	SubtitleLanguage       sql.NullString `json:"subtitle_language"`
	AudioLanguage          sql.NullString `json:"audio_language"`
	MaxStreamingQuality    sql.NullString `json:"max_streaming_quality"`
	EnableAutoPlay         bool           `json:"enable_auto_play"`
	Theme                  sql.NullString `json:"theme"`
	CreatedAt              time.Time      `json:"created_at"`
	LastLoginAt            sql.NullTime   `json:"last_login_at"`
	ParentUserID           sql.NullString `json:"parent_user_id"`
	PinHash                sql.NullString `json:"pin_hash"`
	MaxContentRating       sql.NullString `json:"max_content_rating"`
	PasswordChangeRequired bool           `json:"password_change_required"`
	AccessExpiresAt        sql.NullTime   `json:"access_expires_at"`
	AvatarColor            sql.NullString `json:"avatar_color"`
	CanUpload              bool           `json:"can_upload"`
	UploadQuotaBytes       int64          `json:"upload_quota_bytes"`
	UploadUsedBytes        int64          `json:"upload_used_bytes"`
	IsOwner                bool           `json:"is_owner"`
	CanManageAdmins        bool           `json:"can_manage_admins"`
	CanManageUsers         bool           `json:"can_manage_users"`
	CanManageLibraries     bool           `json:"can_manage_libraries"`
	CanManageIptv          bool           `json:"can_manage_iptv"`
	CanEditMetadata        bool           `json:"can_edit_metadata"`
	CanChangeArtwork       bool           `json:"can_change_artwork"`
	CanViewAudit           bool           `json:"can_view_audit"`
}

type UserChannelFavorite struct {
	UserID    string    `json:"user_id"`
	ChannelID string    `json:"channel_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserChannelOrder struct {
	UserID    string    `json:"user_id"`
	ChannelID string    `json:"channel_id"`
	Position  int32     `json:"position"`
	Hidden    bool      `json:"hidden"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserDatum struct {
	UserID              string        `json:"user_id"`
	ItemID              string        `json:"item_id"`
	PositionTicks       sql.NullInt64 `json:"position_ticks"`
	PlayCount           sql.NullInt32 `json:"play_count"`
	Completed           sql.NullBool  `json:"completed"`
	IsFavorite          sql.NullBool  `json:"is_favorite"`
	Liked               sql.NullBool  `json:"liked"`
	AudioStreamIndex    sql.NullInt32 `json:"audio_stream_index"`
	SubtitleStreamIndex sql.NullInt32 `json:"subtitle_stream_index"`
	LastPlayedAt        sql.NullTime  `json:"last_played_at"`
	UpdatedAt           time.Time     `json:"updated_at"`
}

type UserPreference struct {
	UserID    string    `json:"user_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type WebhookConfig struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Url          string         `json:"url"`
	Method       string         `json:"method"`
	EventsJson   string         `json:"events_json"`
	HeadersJson  sql.NullString `json:"headers_json"`
	BodyTemplate sql.NullString `json:"body_template"`
	RetryCount   sql.NullInt32  `json:"retry_count"`
	TimeoutSec   sql.NullInt32  `json:"timeout_sec"`
	IsActive     bool           `json:"is_active"`
	CreatedAt    time.Time      `json:"created_at"`
}

type WebhookLog struct {
	ID           string         `json:"id"`
	WebhookID    string         `json:"webhook_id"`
	EventType    string         `json:"event_type"`
	Status       string         `json:"status"`
	ResponseCode sql.NullInt32  `json:"response_code"`
	ResponseBody sql.NullString `json:"response_body"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
}
