// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc_pg

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	// Per-user IPTV channel favorites.
	//
	// Table schema: migrations/sqlite/006_channel_favorites.sql.
	// PK: (user_id, channel_id).
	AddChannelFavorite(ctx context.Context, arg AddChannelFavoriteParams) error
	// ApplyChannelOverride is the per-row hook the post-import pass uses.
	// Returns rows affected so the caller can count "actually applied"
	// vs orphan (stream_url no longer in playlist).
	ApplyChannelOverride(ctx context.Context, arg ApplyChannelOverrideParams) (int64, error)
	ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) error
	CleanupOldPrograms(ctx context.Context, endTime time.Time) (int64, error)
	// Used before re-populating an item's tags during a metadata refresh,
	// so removed genres don't linger after a TMDb update changes them.
	ClearItemValuesForItem(ctx context.Context, arg ClearItemValuesForItemParams) error
	// Drop the row from "Seguir viendo" / Continue Watching without touching
	// play_count, is_favorite or last_played_at. The CW SQL gates on
	// position_ticks > 0, so zeroing it is enough to make the item vanish
	// from the rail; everything else stays intact so a future Play resumes
	// the play-count history and a favorited title remains favorited.
	ClearProgress(ctx context.Context, arg ClearProgressParams) error
	ConsumeDeviceCode(ctx context.Context, arg ConsumeDeviceCodeParams) error
	// Two extra filters vs. the obvious "started but not completed" rail:
	//   1. Near-complete drop: position >= 90% of duration. Treat as
	//      effectively done -- the user almost certainly finished and the
	//      rail showing it as in-progress is noise.
	//   2. Abandoned drop: last_played_at older than the caller-supplied
	//      threshold AND position < 50%. The user moved on; the rail
	//      should not keep nagging about the same start-of-S1E1 forever.
	// Both checks are integer-safe (ticks * 100 / 90 and ticks * 2 / 1)
	// and both require a known duration; rows with duration_ticks = 0
	// are kept (we can't reason about progress without it).
	//
	// The abandoned filter is expressed positively (DeMorgan equivalent of
	// the obvious NOT (...) form) to dodge a sqlc parser bug where ?
	// placeholders nested inside NOT (...) clauses are silently dropped
	// from the generated Params struct. The IS NOT NULL guard preserves
	// the original three-valued-logic behaviour where a NULL last_played_at
	// excluded the row -- in practice the position_ticks > 0 above means
	// last_played_at is always set; this is belt and braces. See
	// docs/memory/conventions.md (Regeneracion sqlc section) for the full
	// story. NOTE: keep this comment pure ASCII -- multi-byte chars
	// (em-dashes, accents, backticks) trigger another parser bug that
	// silently truncates queries below.
	ContinueWatching(ctx context.Context, arg ContinueWatchingParams) ([]ContinueWatchingRow, error)
	CountAndNewestCachedItems(ctx context.Context, arg CountAndNewestCachedItemsParams) (CountAndNewestCachedItemsRow, error)
	CountExternalIDsByItem(ctx context.Context, itemID string) (int64, error)
	CountItemsByLibrary(ctx context.Context, libraryID string) (int64, error)
	CountSessionsByUser(ctx context.Context, userID string) (int64, error)
	CountSharedItems(ctx context.Context, arg CountSharedItemsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// IPTV channels per library.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE channels).
	CreateChannel(ctx context.Context, arg CreateChannelParams) error
	// Image assets (poster, backdrop, thumb, logo, banner) per item.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE images)
	// + migration 013_image_lock.sql (is_locked column).
	// NOTE: GetPrimaryURLs uses dynamic IN() and remains raw SQL in the adapter.
	CreateImage(ctx context.Context, arg CreateImageParams) error
	// Items (movies, series, seasons, episodes, albums, etc.).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE items).
	// NOTE: List and LatestItems use dynamic WHERE/FTS/cursor and stay raw SQL.
	CreateItem(ctx context.Context, arg CreateItemParams) error
	CreateLibraryEPGSource(ctx context.Context, arg CreateLibraryEPGSourceParams) error
	CreatePerson(ctx context.Context, arg CreatePersonParams) error
	// Auth sessions: one row per active login (refresh token lives here hashed).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE sessions).
	// Rotation/max-sessions policy lives in internal/auth/service.go.
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// JWT signing keys for rotation with overlap.
	//
	// Table schema lives in migrations/sqlite/004_jwt_signing_keys.sql.
	// The repository (signing_key_repository.go) is a thin adapter around
	// these queries. Rotation/overlap policy lives in internal/auth/keystore.go.
	CreateSigningKey(ctx context.Context, arg CreateSigningKeyParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAllSessionsByUser(ctx context.Context, userID string) (int64, error)
	// ============================================================
	// catalog cache (Phase 4 + 027)
	// ============================================================
	DeleteCachedItemsForLibrary(ctx context.Context, arg DeleteCachedItemsForLibraryParams) error
	DeleteChannelOverride(ctx context.Context, arg DeleteChannelOverrideParams) error
	DeleteChannelWatch(ctx context.Context, arg DeleteChannelWatchParams) error
	DeleteChannelsByLibrary(ctx context.Context, libraryID string) error
	DeleteChaptersByItem(ctx context.Context, itemID string) error
	DeleteEPGProgramsByChannel(ctx context.Context, channelID string) error
	DeleteEpisodeSegmentsByItem(ctx context.Context, itemID string) error
	DeleteEpisodeSegmentsByItemAndSource(ctx context.Context, arg DeleteEpisodeSegmentsByItemAndSourceParams) error
	DeleteExpiredDeviceCodes(ctx context.Context, expiresAt time.Time) error
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteFederationProgress(ctx context.Context, arg DeleteFederationProgressParams) error
	DeleteIPTVScheduledJob(ctx context.Context, arg DeleteIPTVScheduledJobParams) error
	DeleteImageByID(ctx context.Context, id string) error
	DeleteImagesByItem(ctx context.Context, itemID string) error
	DeleteItem(ctx context.Context, id string) (int64, error)
	// Clear an item's existing cast/crew before re-inserting. Avoids
	// having to diff the new list against the old one -- re-scans cost a
	// few writes per item rather than a comparison pass. The composite
	// PK on item_people means simple DELETE WHERE item_id = ? is the
	// whole story.
	DeleteItemPeople(ctx context.Context, itemID string) error
	DeleteItemsByLibrary(ctx context.Context, libraryID string) error
	DeleteLibrary(ctx context.Context, id string) (int64, error)
	DeleteLibraryEPGSource(ctx context.Context, id string) error
	DeleteLibraryShare(ctx context.Context, arg DeleteLibraryShareParams) error
	// Media stream tracks (video, audio, subtitle) per item.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE media_streams).
	// PK: (item_id, stream_index).
	DeleteMediaStreamsByItem(ctx context.Context, itemID string) error
	DeleteMetadata(ctx context.Context, itemID string) error
	// Subquery aliased to 's' because sqlc needs unambiguous column resolution
	// when the same table appears twice in scope.
	DeleteOldestSessionByUser(ctx context.Context, userID string) error
	DeletePathsByLibrary(ctx context.Context, libraryID string) error
	DeleteProvider(ctx context.Context, name string) error
	DeleteRetiredSigningKeysBefore(ctx context.Context, retiredAt sql.NullTime) (int64, error)
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) error
	DeleteUser(ctx context.Context, id string) (int64, error)
	DeleteUserData(ctx context.Context, arg DeleteUserDataParams) error
	GetChannelByID(ctx context.Context, id string) (GetChannelByIDRow, error)
	GetChannelOverride(ctx context.Context, arg GetChannelOverrideParams) (ChannelOverride, error)
	// Movie collections (sagas).
	//
	// Schema: migrations/sqlite/033_collections.sql.
	// Keyed by tmdb_id (UNIQUE) so the same X-Men / MCU / Toy Story
	// saga collapses across every member movie regardless of name drift.
	GetCollectionByID(ctx context.Context, id string) (Collection, error)
	GetCollectionByTMDBID(ctx context.Context, tmdbID int32) (Collection, error)
	GetDeviceCodeByDeviceCode(ctx context.Context, deviceCode string) (DeviceCode, error)
	GetDeviceCodeByUserCode(ctx context.Context, userCode string) (DeviceCode, error)
	GetExternalIDByProvider(ctx context.Context, arg GetExternalIDByProviderParams) (ExternalID, error)
	GetFederationProgress(ctx context.Context, arg GetFederationProgressParams) (FederationProgress, error)
	GetIPTVScheduledJob(ctx context.Context, arg GetIPTVScheduledJobParams) (IptvScheduledJob, error)
	GetImageByID(ctx context.Context, id string) (GetImageByIDRow, error)
	GetInviteByCode(ctx context.Context, code string) (FederationInvite, error)
	GetItemByID(ctx context.Context, id string) (GetItemByIDRow, error)
	GetItemByPath(ctx context.Context, path sql.NullString) (GetItemByPathRow, error)
	GetItemChildren(ctx context.Context, parentID sql.NullString) ([]GetItemChildrenRow, error)
	GetLibraryByID(ctx context.Context, id string) (GetLibraryByIDRow, error)
	GetLibraryEPGSourceByID(ctx context.Context, id string) (GetLibraryEPGSourceByIDRow, error)
	GetLibraryShare(ctx context.Context, arg GetLibraryShareParams) (FederationLibraryShare, error)
	GetMetadataByItemID(ctx context.Context, itemID string) (GetMetadataByItemIDRow, error)
	GetNowPlaying(ctx context.Context, arg GetNowPlayingParams) (GetNowPlayingRow, error)
	GetPeerByID(ctx context.Context, id string) (FederationPeer, error)
	GetPeerByServerUUID(ctx context.Context, serverUuid string) (FederationPeer, error)
	GetPersonByID(ctx context.Context, id string) (GetPersonByIDRow, error)
	// People (cast + crew) and the join table that links them to items.
	//
	// Schema: migrations/sqlite/001_initial_schema.sql
	//   people(id, name, type, thumb_path)
	//   item_people(item_id, person_id, role, character_name, sort_order)  PK on (item_id, person_id, role)
	//
	// Deduplication: people are keyed in DB by uuid id but the scanner
	// needs a stable lookup from "the person TMDb just gave me". For now
	// we dedup by name (case-sensitive -- TMDb is consistent) which is
	// good enough for the 95% case. A future migration can add a
	// person-level external_ids table for the edge cases (alias drift,
	// two actors with the same name).
	GetPersonByName(ctx context.Context, name string) (GetPersonByNameRow, error)
	// Returns the user_id of the oldest admin row. The primary admin
	// is identified positionally, not by an explicit flag, so a fresh
	// DB starts with the setup-wizard user as primary automatically.
	// Empty result when no admin exists yet (cold-start install).
	GetPrimaryAdminID(ctx context.Context) (string, error)
	GetPrimaryImage(ctx context.Context, arg GetPrimaryImageParams) (GetPrimaryImageRow, error)
	GetProvider(ctx context.Context, name string) (Provider, error)
	// Federation: server identity, peers, invites, library shares, audit
	// log, item-cache. Schema: migrations/sqlite/020-023, 027.
	//
	// Adapter wrapping these queries lives in
	// internal/db/federation_repository.go and is the public surface the
	// federation package consumes.
	// ============================================================
	// server identity (one row, enforced by CHECK(id=1))
	// ============================================================
	GetServerIdentity(ctx context.Context) (GetServerIdentityRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSigningKey(ctx context.Context, id string) (JwtSigningKey, error)
	// Studios (production companies + TV networks).
	//
	// Schema: migrations/sqlite/032_studios.sql.
	// The slug is URL-safe; ListItemsForStudio is intentionally raw SQL
	// (lives in studio_repository.go) because the trailing ORDER BY hits
	// the sqlc v1.31.1 parser truncation we already work around for
	// ListGenres + GetItemIDByExternalID.
	GetStudioBySlug(ctx context.Context, slug string) (Studio, error)
	GetStudioByTMDBID(ctx context.Context, tmdbID sql.NullInt32) (Studio, error)
	// User accounts.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE users)
	// + migrations/sqlite/034_user_profiles.sql (parent_user_id, pin_hash,
	// max_content_rating, password_change_required).
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	GetUserData(ctx context.Context, arg GetUserDataParams) (UserDatum, error)
	// Postgres: INSERT OR IGNORE → ON CONFLICT DO NOTHING (sin target =
	// match cualquier constraint, mismo comportamiento que SQLite).
	GrantLibraryAccess(ctx context.Context, arg GrantLibraryAccessParams) error
	// Grants the given library_id to the primary admin (oldest top-level
	// role=admin row, same definition as GetPrimaryAdminID). Idempotent
	// via ON CONFLICT DO NOTHING; no-op when no admin exists yet (cold-
	// start pre setup-wizard). Called from LibraryRepository.Create
	// inside the same tx so the invariant "primary admin sees every
	// library" holds for libraries created after migration 041.
	GrantPrimaryAdminLibraryAccess(ctx context.Context, libraryID string) error
	HasLockedImageForKind(ctx context.Context, arg HasLockedImageForKindParams) (bool, error)
	InsertCachedItem(ctx context.Context, arg InsertCachedItemParams) error
	// Chapter markers per item (movie or episode), keyed by start time.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE chapters).
	// PK: (item_id, start_ticks). Chapters are immutable per scan -- the
	// scanner clears the row set before re-inserting so a re-encode that
	// shifted markers can replace them cleanly without leaving phantom
	// entries from the previous timing.
	InsertChapter(ctx context.Context, arg InsertChapterParams) error
	InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) error
	// Electronic program guide entries per channel.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE epg_programs).
	// NOTE: BulkSchedule uses dynamic IN() and remains as raw SQL in the adapter.
	InsertEPGProgram(ctx context.Context, arg InsertEPGProgramParams) error
	// Skip-intro / skip-credits markers per item.
	//
	// Schema: migrations/sqlite/037_episode_segments.sql.
	// PK: (item_id, kind, source). Repository.Replace() wraps DELETE+INSERT
	// in a transaction so a re-run of one detector replaces only its own
	// rows; segments from other sources stay untouched.
	InsertEpisodeSegment(ctx context.Context, arg InsertEpisodeSegmentParams) error
	// ============================================================
	// audit log
	// ============================================================
	InsertFederationAuditEntry(ctx context.Context, arg InsertFederationAuditEntryParams) error
	// ============================================================
	// invites
	// ============================================================
	InsertInvite(ctx context.Context, arg InsertInviteParams) error
	InsertItemPerson(ctx context.Context, arg InsertItemPersonParams) error
	// Library management (media libraries, paths, access control).
	//
	// Tables: libraries, library_paths, library_access.
	InsertLibrary(ctx context.Context, arg InsertLibraryParams) error
	InsertLibraryPath(ctx context.Context, arg InsertLibraryPathParams) error
	InsertMediaStream(ctx context.Context, arg InsertMediaStreamParams) error
	// ============================================================
	// peers
	// ============================================================
	InsertPeer(ctx context.Context, arg InsertPeerParams) error
	InsertServerIdentity(ctx context.Context, arg InsertServerIdentityParams) error
	IsChannelFavorite(ctx context.Context, arg IsChannelFavoriteParams) (int32, error)
	// Postgres: INSERT OR IGNORE → ON CONFLICT DO NOTHING. La PK
	// compuesta (item_id, value_id) cubre el dedup natural.
	LinkItemValue(ctx context.Context, arg LinkItemValueParams) error
	ListActiveChannelsByLibrary(ctx context.Context, libraryID string) ([]ListActiveChannelsByLibraryRow, error)
	ListActiveInvites(ctx context.Context, expiresAt time.Time) ([]FederationInvite, error)
	ListActiveProviders(ctx context.Context) ([]Provider, error)
	ListActiveSigningKeys(ctx context.Context) ([]JwtSigningKey, error)
	ListAllPaths(ctx context.Context) ([]LibraryPath, error)
	ListCachedItems(ctx context.Context, arg ListCachedItemsParams) ([]ListCachedItemsRow, error)
	ListChannelFavorites(ctx context.Context, userID string) ([]ListChannelFavoritesRow, error)
	ListChannelFavoritesWithChannel(ctx context.Context, userID string) ([]ListChannelFavoritesWithChannelRow, error)
	ListChannelGroups(ctx context.Context, libraryID string) ([]sql.NullString, error)
	ListChannelOverridesByLibrary(ctx context.Context, libraryID string) ([]ListChannelOverridesByLibraryRow, error)
	// ListChannelWatchHistoryByUser joins onto active channels in
	// recency order. Filters applied in SQL so the handler cannot
	// accidentally bypass them: c.is_active = 1 (deactivated channels
	// drop off the rail), and orphan history rows (stream_url no longer
	// in any playlist) are joined out naturally.
	//
	// limit is doubled at the call site to absorb stream_url duplicates
	// across libraries; the repo dedupes in Go.
	ListChannelWatchHistoryByUser(ctx context.Context, arg ListChannelWatchHistoryByUserParams) ([]ListChannelWatchHistoryByUserRow, error)
	ListChannelsByLibrary(ctx context.Context, libraryID string) ([]ListChannelsByLibraryRow, error)
	ListChaptersByItem(ctx context.Context, itemID string) ([]ListChaptersByItemRow, error)
	// Workers hot query. Filtered by enabled in SQL; due-ness is
	// computed in Go (see ListDue) because date arithmetic on the
	// multi-format-tolerant column would invite the same Scan problem
	// we work around elsewhere.
	ListEnabledIPTVScheduledJobs(ctx context.Context) ([]IptvScheduledJob, error)
	ListEpisodeSegmentsByItem(ctx context.Context, itemID string) ([]EpisodeSegment, error)
	ListExternalIDsByItem(ctx context.Context, itemID string) ([]ExternalID, error)
	ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error)
	ListFederationAuditEntries(ctx context.Context, arg ListFederationAuditEntriesParams) ([]ListFederationAuditEntriesRow, error)
	// Cross-peer Continue Watching rail. Only rows that look genuinely
	// "in progress" are returned: not completed, position > 0, and (when
	// duration is known) less than 90 percent played -- mirrors the local
	// ContinueWatching filter so peer rows behave the same way the user
	// already expects from local rows. Joins the catalog cache for
	// title / poster availability so the rail can render without a
	// per-row hop. Rows whose cache entry has been evicted (peer
	// catalog refreshed against newer state) are dropped from the rail
	// rather than rendered title-less.
	ListFederationContinueWatching(ctx context.Context, arg ListFederationContinueWatchingParams) ([]ListFederationContinueWatchingRow, error)
	// Filmography: every movie + series this person has a direct credit
	// on. Episode-level credits drop through for now (parent series
	// usually carries the same person at the top level -- TMDb is
	// consistent there). Sorted newest-first; rows for the same item
	// but different role (e.g. actor + writer on the same movie) are
	// returned both -- the caller dedupes keeping the lowest sort_order.
	//
	// Primary-image LEFT JOIN powers the poster thumbnail on the actor
	// page: still one query per page (the JOIN doesn't multiply rows --
	// there is at most one is_primary=1 row per (item, type='primary')),
	// the wire just gets one extra nullable column.
	ListFilmographyByPerson(ctx context.Context, personID string) ([]ListFilmographyByPersonRow, error)
	// Scheduled IPTV jobs (per-library M3U + EPG refresh automation).
	//
	// Table schema: migrations/sqlite/011_iptv_scheduled_jobs.sql.
	// Composite PK: (library_id, kind in {'m3u_refresh','epg_refresh'}).
	//
	// Time handling: callers MUST normalise time.Time values to UTC
	// before passing them in (see iptv_schedule_repository.go). The
	// modernc.org/sqlite driver serialises time.Time with named-zone
	// locations using a format the default Scan cannot parse, so we
	// treat UTC-on-write as a hard contract. Reads land into stdlib
	// time.Time / sql.NullTime without coerceSQLiteTime needing to
	// intervene.
	ListIPTVScheduledJobsByLibrary(ctx context.Context, libraryID string) ([]IptvScheduledJob, error)
	ListImagesByItem(ctx context.Context, itemID string) ([]ListImagesByItemRow, error)
	// Returns the cast/crew rows for an item joined with the person
	// record so the caller gets one struct per row. Ordered by
	// sort_order so TMDb's "billing position" ranking surfaces directly
	// to the UI without a client-side sort.
	ListItemPeople(ctx context.Context, itemID string) ([]ListItemPeopleRow, error)
	ListLibraries(ctx context.Context) ([]ListLibrariesRow, error)
	// Returns library_ids the user_id has explicit grants for. Admin-only
	// surface (the user's library list goes through ListLibrariesForUser
	// which applies the profile-inheritance predicate). Callers pass the
	// top-level user id; for profile rows the caller must resolve to the
	// parent first. See ADR-014.
	ListLibraryAccessByUser(ctx context.Context, userID string) ([]string, error)
	// Per-library EPG source list (multi-provider XMLTV configuration).
	//
	// Table schema: migrations/sqlite/007_library_epg_sources.sql.
	// PK: (id). UNIQUE on (library_id, url) so a duplicate add raises a
	// detectable constraint failure that the repo maps to
	// ErrEPGSourceAlreadyAttached.
	//
	// COALESCE columns: catalog_id, last_refreshed_at, last_status and
	// last_error are all nullable in storage. Reading them back with
	// COALESCE keeps the consumer code free of NullString / NullTime
	// branching except for last_refreshed_at, which still needs zero-
	// value detection (we cannot tell "never refreshed" from an empty
	// string). Falling back to sql.NullTime there.
	ListLibraryEPGSourcesByLibrary(ctx context.Context, libraryID string) ([]ListLibraryEPGSourcesByLibraryRow, error)
	ListMediaStreamsByItem(ctx context.Context, itemID string) ([]ListMediaStreamsByItemRow, error)
	ListPathsByLibrary(ctx context.Context, libraryID string) ([]string, error)
	ListPeers(ctx context.Context) ([]FederationPeer, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListProvidersByType(ctx context.Context, type_ string) ([]Provider, error)
	// NOTE: SearchSharedItems is implemented as raw SQL in
	// federation_repository.go because sqlc does not parse FTS5 virtual
	// tables (items_fts MATCH $5). Same precedent as item_repository.go's
	// List path.
	// Most recently added items across every library shared with `peerID`
	// (CanBrowse gate). Powers the consumer-side "Recently added on
	// peers" rail: each paired peer answers with its top-N freshest
	// titles, the consumer fan-out merges them. library_id is selected
	// so the consumer can route a click into
	// /peers/{peerID}/libraries/{libraryID}/items/{id} (same shape as
	// the search hits).
	ListRecentSharedItems(ctx context.Context, arg ListRecentSharedItemsParams) ([]ListRecentSharedItemsRow, error)
	ListSchedule(ctx context.Context, arg ListScheduleParams) ([]ListScheduleRow, error)
	ListSessionsByUser(ctx context.Context, userID string) ([]Session, error)
	// Overview lives in the metadata sidecar (LEFT JOIN so items without
	// metadata still surface with empty overview). HasPoster is an EXISTS
	// subquery against the images table so the listing path does not
	// need to pull the image id; the actual bytes flow through
	// /peer/items/{id}/poster on demand.
	ListSharedItems(ctx context.Context, arg ListSharedItemsParams) ([]ListSharedItemsRow, error)
	ListSharedLibrariesForPeer(ctx context.Context, peerID string) ([]ListSharedLibrariesForPeerRow, error)
	ListSharesByPeer(ctx context.Context, peerID string) ([]FederationLibraryShare, error)
	ListSigningKeys(ctx context.Context) ([]JwtSigningKey, error)
	// Browse-page listing: every studio that has at least one item linked
	// to it, ordered by item count desc. The COUNT subquery is fine
	// (one studio thousand-items at most) and keeps the index touched
	// to (studio_id) which we already created in 032_studios.sql.
	ListStudios(ctx context.Context) ([]ListStudiosRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error
	MarkPlayed(ctx context.Context, arg MarkPlayedParams) error
	// The default-priority slot for a freshly-added source: one past the
	// current max, so it runs last and can be reordered from the UI.
	// COALESCE returns -1 for "no rows yet" so the repo can lift it to 0
	// without splitting NullInt branches.
	NextLibraryEPGSourcePriority(ctx context.Context, libraryID string) (interface{}, error)
	PruneFederationAuditBefore(ctx context.Context, occurredAt time.Time) (int64, error)
	// Per-user "continue watching" history for LiveTV channels.
	//
	// Table schema: migrations/sqlite/012_channel_watch_history.sql.
	// Composite PK: (user_id, stream_url).
	//
	// Keyed by stream_url so the rail survives M3U refreshes (channel
	// UUIDs regenerate). The list query joins back to channels by
	// stream_url at read time.
	RecordChannelWatch(ctx context.Context, arg RecordChannelWatchParams) error
	RecordIPTVScheduledJobRun(ctx context.Context, arg RecordIPTVScheduledJobRunParams) error
	RecordLibraryEPGSourceRefresh(ctx context.Context, arg RecordLibraryEPGSourceRefreshParams) error
	RemoveChannelFavorite(ctx context.Context, arg RemoveChannelFavoriteParams) error
	RevokeLibraryAccess(ctx context.Context, arg RevokeLibraryAccessParams) error
	// Aggregate "X of Y episodes watched" for a single series.
	// The grid is series -> seasons -> episodes via parent_id; LEFT JOIN
	// on user_data so episodes the user has never touched count as
	// unwatched without forcing an INNER row to exist. Both columns come
	// back as plain integers; SQLite COUNT() is well-typed for sqlc.
	SeriesEpisodeProgress(ctx context.Context, arg SeriesEpisodeProgressParams) (SeriesEpisodeProgressRow, error)
	SetChannelActive(ctx context.Context, arg SetChannelActiveParams) (int64, error)
	SetFavorite(ctx context.Context, arg SetFavoriteParams) error
	SetImageLocked(ctx context.Context, arg SetImageLockedParams) error
	SetImagePrimary(ctx context.Context, arg SetImagePrimaryParams) error
	SetPersonThumbPath(ctx context.Context, arg SetPersonThumbPathParams) error
	SetProviderStatus(ctx context.Context, arg SetProviderStatusParams) (int64, error)
	SetServerAvatarPath(ctx context.Context, avatarImagePath string) error
	SetSigningKeyRetiredAt(ctx context.Context, arg SetSigningKeyRetiredAtParams) (int64, error)
	TouchDeviceCodePollAt(ctx context.Context, arg TouchDeviceCodePollAtParams) error
	UnsetPrimaryImages(ctx context.Context, arg UnsetPrimaryImagesParams) error
	UpdateItem(ctx context.Context, arg UpdateItemParams) (int64, error)
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (int64, error)
	UpdateLibraryEPGSourcePriority(ctx context.Context, arg UpdateLibraryEPGSourcePriorityParams) error
	UpdatePeerLastSeen(ctx context.Context, arg UpdatePeerLastSeenParams) error
	UpdatePeerPaired(ctx context.Context, arg UpdatePeerPairedParams) error
	UpdatePeerRevoked(ctx context.Context, arg UpdatePeerRevokedParams) (int64, error)
	UpdateProgress(ctx context.Context, arg UpdateProgressParams) error
	// Personalizacion editable del servidor: nombre visible para peers
	// y color hex de fallback para el avatar. La foto se actualiza por
	// separado para no reenviar los otros campos en cada upload.
	UpdateServerIdentityProfile(ctx context.Context, arg UpdateServerIdentityProfileParams) error
	UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	// NULL = no expiry (permanent). Non-null = JWT middleware + login
	// reject after this timestamp. Lazy: no background job needed.
	UpdateUserAccessExpiresAt(ctx context.Context, arg UpdateUserAccessExpiresAtParams) error
	// Soft-disable a user without deleting. Login rejects on
	// is_active=false; the row + every per-user table stays intact so
	// re-enabling is a one-flag flip.
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error
	// avatar_color NULL = use the deterministic FNV-1a → palette
	// fallback the frontend already has. Non-null = explicit hex
	// override. Service-layer enforces the value is in the known
	// palette (or empty) before reaching the repo.
	UpdateUserAvatarColor(ctx context.Context, arg UpdateUserAvatarColorParams) error
	// Quita el avatar subido. El fichero en disco lo borra el service
	// antes de llamar; aquí sólo desreferenciamos.
	ClearUserAvatarPath(ctx context.Context, id string) error
	// Sube/actualiza la ruta en disco del avatar subido por el usuario.
	// El path es relativo al directorio de avatares (config/avatars/<file>),
	// no absoluto, para que la migración del volumen no rompa nada.
	UpdateUserAvatarPath(ctx context.Context, arg UpdateUserAvatarPathParams) error
	// Per-field update so callers (renaming a profile, an admin
	// relabelling a user) don't need to round-trip the rest of the
	// mutable surface.
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	// max_content_rating NULL means "no restriction". Empty string is
	// normalised to NULL by the handler so callers don't have to choose.
	UpdateUserMaxContentRating(ctx context.Context, arg UpdateUserMaxContentRatingParams) error
	// pin_hash NULL clears the PIN; non-null sets it. The handler always
	// bcrypt-hashes the value before reaching the repo.
	UpdateUserPIN(ctx context.Context, arg UpdateUserPINParams) error
	// Used by both the admin reset-password endpoint and the user's own
	// change-password flow. Resetting must clear the must-change flag so
	// the user isn't bounced back to the change screen forever; setting
	// a fresh password from the admin path SETs it so the new password
	// triggers a forced change on first login.
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Promote / demote between user and admin. Caller-side gate keeps
	// the primary admin (oldest role=admin row) immutable.
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	// Manual channel edits keyed by stream URL so they survive an M3U
	// refresh (channel UUIDs are regenerated on every import).
	//
	// Table schema: migrations/sqlite/009_channel_overrides.sql.
	// Composite PK: (library_id, stream_url).
	UpsertChannelOverride(ctx context.Context, arg UpsertChannelOverrideParams) error
	// External ID mappings (tmdb, imdb, tvdb, ...) for items.
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE external_ids).
	// PK: (item_id, provider).
	UpsertExternalID(ctx context.Context, arg UpsertExternalIDParams) error
	// ============================================================
	// federation_progress (028) -- cross-peer Continue Watching
	// ============================================================
	UpsertFederationProgress(ctx context.Context, arg UpsertFederationProgressParams) error
	// Preserves last_* fields by design: only the configuration
	// (interval_hours / enabled) and updated_at change. The history
	// (last_run_at, last_status, ...) survives reconfiguration.
	UpsertIPTVScheduledJob(ctx context.Context, arg UpsertIPTVScheduledJobParams) error
	// Normalized tag store reused for genres (and future tag-like facets).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (item_values, item_value_map).
	// Backfill: migrations/sqlite/031_item_values_genres_backfill.sql.
	//
	// The synthetic id format ("<type>:<clean_value>", lowercased) makes
	// INSERT-OR-IGNORE idempotent across items sharing the same value, so
	// the scanner can re-run UpsertItemValue per scan without dedup logic.
	UpsertItemValue(ctx context.Context, arg UpsertItemValueParams) error
	// ============================================================
	// library shares
	// ============================================================
	UpsertLibraryShare(ctx context.Context, arg UpsertLibraryShareParams) error
	// Extended metadata for items (overview, tagline, genres, etc.).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE metadata).
	// PK: item_id.
	// NOTE: Batch queries (GetOverviewBatch, GetMetadataBatch) use dynamic IN()
	// and remain as raw SQL in the repository adapter.
	UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) error
	// Provider configurations (TMDb, Fanart, OpenSubtitles, ...).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE providers).
	// Runtime registry + api-key sourcing lives in internal/provider/manager.go.
	UpsertProvider(ctx context.Context, arg UpsertProviderParams) error
	// The scanner calls this every time it processes a movie/series with
	// a TMDb production company match. Conflict on tmdb_id keeps a single
	// row per upstream studio even when the slug recipe would diverge
	// (e.g. "Lucasfilm" vs "Lucasfilm Ltd."); conflict on slug catches
	// the rare case of a studio with no tmdb_id (legacy backfill rows).
	// We refresh the logo_url on conflict so a re-scan with a richer
	// TMDb response upgrades the brand mark, but we keep `name` and
	// `slug` stable so the URL stays valid even if TMDb renames.
	UpsertStudio(ctx context.Context, arg UpsertStudioParams) error
	// Fallback when the scanner has no tmdb_id (legacy items, providers
	// other than TMDb). The slug is the dedupe key.
	UpsertStudioBySlug(ctx context.Context, arg UpsertStudioBySlugParams) error
	// Per-user per-item interaction data (progress, favorites, play history).
	//
	// Table schema: migrations/sqlite/001_initial_schema.sql (CREATE TABLE user_data).
	// PK: (user_id, item_id).
	UpsertUserData(ctx context.Context, arg UpsertUserDataParams) error
}

var _ Querier = (*Queries)(nil)
